# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.13

# Mod Properties
mod_version=4.0-beta-1
maven_group=github.mc_datapck.blocktopia
archives_base_name=blocktopia

# Dependencies
fabric_version=0.115.6+1.21.1
trinkets_version=3.10.0
terrablender_version=1.21.1-4.1.0.8
cloth_config_version=15.0.140
terraform_wood_api_version=11.0.0
mod_menu_version=11.0.3
more_tools_and_armor_version=10.1
custom_portal_api_version=0.0.1-beta67-1.21
continuity_version=3.0.0+1.21
jei_version=19.21.0.247