package github.mcdatapack.blocktopia.block;

import net.minecraft.data.family.BlockFamily;

public interface ModBlockFamilies {
    BlockFamily PALM = new BlockFamily.Builder(ModBlocks.PALM_PLANKS)
            .button(ModBlocks.PALM_BUTTON)
            .fence(ModBlocks.PALM_FENCE)
            .fenceGate(ModBlocks.PALM_FENCE_GATE)
            .pressurePlate(ModBlocks.PALM_PRESSURE_PLATE)
            .slab(ModBlocks.PALM_SLAB)
            .stairs(ModBlocks.PALM_STAIRS)
            .door(ModBlocks.PALM_DOOR)
            .trapdoor(ModBlocks.PALM_TRAPDOOR)
            .sign(ModBlocks.PALM_SIGN, ModBlocks.PALM_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily BANANA = new BlockFamily.Builder(ModBlocks.BANANA_PLANKS)
            .button(ModBlocks.BANANA_BUTTON)
            .fence(ModBlocks.BANANA_FENCE)
            .fenceGate(ModBlocks.BANANA_FENCE_GATE)
            .pressurePlate(ModBlocks.BANANA_PRESSURE_PLATE)
            .slab(ModBlocks.BANANA_SLAB)
            .stairs(ModBlocks.BANANA_STAIRS)
            .door(ModBlocks.BANANA_DOOR)
            .trapdoor(ModBlocks.BANANA_TRAPDOOR)
            .sign(ModBlocks.BANANA_SIGN, ModBlocks.BANANA_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily MAHOGANY = new BlockFamily.Builder(ModBlocks.MAHOGANY_PLANKS)
            .button(ModBlocks.MAHOGANY_BUTTON)
            .fence(ModBlocks.MAHOGANY_FENCE)
            .fenceGate(ModBlocks.MAHOGANY_FENCE_GATE)
            .pressurePlate(ModBlocks.MAHOGANY_PRESSURE_PLATE)
            .slab(ModBlocks.MAHOGANY_SLAB)
            .stairs(ModBlocks.MAHOGANY_STAIRS)
            .door(ModBlocks.MAHOGANY_DOOR)
            .trapdoor(ModBlocks.MAHOGANY_TRAPDOOR)
            .sign(ModBlocks.MAHOGANY_SIGN, ModBlocks.MAHOGANY_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily CORN = new BlockFamily.Builder(ModBlocks.CORN_PLANKS)
            .button(ModBlocks.CORN_BUTTON)
            .fence(ModBlocks.CORN_FENCE)
            .fenceGate(ModBlocks.CORN_FENCE_GATE)
            .pressurePlate(ModBlocks.CORN_PRESSURE_PLATE)
            .slab(ModBlocks.CORN_SLAB)
            .stairs(ModBlocks.CORN_STAIRS)
            .door(ModBlocks.CORN_DOOR)
            .trapdoor(ModBlocks.CORN_TRAPDOOR)
            .sign(ModBlocks.CORN_SIGN, ModBlocks.CORN_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily POISONED = new BlockFamily.Builder(ModBlocks.POISONED_PLANKS)
            .button(ModBlocks.POISONED_BUTTON)
            .fence(ModBlocks.POISONED_FENCE)
            .fenceGate(ModBlocks.POISONED_FENCE_GATE)
            .pressurePlate(ModBlocks.POISONED_PRESSURE_PLATE)
            .slab(ModBlocks.POISONED_SLAB)
            .stairs(ModBlocks.POISONED_STAIRS)
            .door(ModBlocks.POISONED_DOOR)
            .trapdoor(ModBlocks.POISONED_TRAPDOOR)
            .sign(ModBlocks.POISONED_SIGN, ModBlocks.POISONED_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();

    BlockFamily WOODEN_RD20080515 = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_RD20090515)
            .stairs(LegacyBlocks.WOODEN_STAIRS_RD20090515)
            .fence(LegacyBlocks.WOODEN_FENCE_RD20090515)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_RD161348 = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_RD161348)
            .stairs(LegacyBlocks.WOODEN_STAIRS_RD161348)
            .fence(LegacyBlocks.WOODEN_FENCE_RD161348)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_C0_0_14A = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_C0_0_14A)
            .stairs(LegacyBlocks.WOODEN_STAIRS_C0_0_14A)
            .fence(LegacyBlocks.WOODEN_FENCE_C0_0_14A)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_C0_0_15A = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_C0_0_15A)
            .stairs(LegacyBlocks.WOODEN_STAIRS_INF20100629)
            .door(LegacyBlocks.WOODEN_DOOR_INF20100607)
            .fence(LegacyBlocks.WOODEN_FENCE_A1_0_17)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_B1_9PRE5 = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_B1_9PRE5)
            .stairs(LegacyBlocks.WOODEN_STAIRS_B1_9PRE5)
            .fence(LegacyBlocks.WOODEN_FENCE_B1_9PRE5)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily COBBLESTONE_RD20090515 = new BlockFamily.Builder(LegacyBlocks.COBBLESTONE_RD20090515)
            .stairs(LegacyBlocks.COBBLESTONE_STAIRS_RD20090515)
            //.slab(LegacyBlocks.COBBLESTONE_SLAB_RD20090515)
            .group("cobblestone")
            .unlockCriterionName("has_cobblestone")
            .build();
    BlockFamily COBBLESTONE_C0_0_14A = new BlockFamily.Builder(LegacyBlocks.COBBLESTONE_C_0_0_14A)
            .stairs(LegacyBlocks.COBBLESTONE_STAIRS_INF20100629)
            //.slab(LegacyBlocks.COBBLESTONE_SLAB_B1_3)
            .group("cobblestone")
            .unlockCriterionName("has_cobblestone")
            .build();
    BlockFamily COBBLESTONE_B1_7 = new BlockFamily.Builder(LegacyBlocks.COBBLESTONE_B1_7)
            .stairs(LegacyBlocks.COBBLESTONE_STAIRS_B1_7)
            //.slab(LegacyBlocks.COBBLESTONE_SLAB_B1_7)
            .group("cobblestone")
            .unlockCriterionName("has_cobblestone")
            .build();
}
