package github.mcdatapack.blocktopia.block;

import net.minecraft.data.family.BlockFamily;

public interface ModBlockFamilies {
    BlockFamily PALM = new BlockFamily.Builder(ModBlocks.PALM_PLANKS)
            .button(ModBlocks.PALM_BUTTON)
            .fence(ModBlocks.PALM_FENCE)
            .fenceGate(ModBlocks.PALM_FENCE_GATE)
            .pressurePlate(ModBlocks.PALM_PRESSURE_PLATE)
            .slab(ModBlocks.PALM_SLAB)
            .stairs(ModBlocks.PALM_STAIRS)
            .door(ModBlocks.PALM_DOOR)
            .trapdoor(ModBlocks.PALM_TRAPDOOR)
            .sign(ModBlocks.PALM_SIGN, ModBlocks.PALM_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily BANANA = new BlockFamily.Builder(ModBlocks.BANANA_PLANKS)
            .button(ModBlocks.BANANA_BUTTON)
            .fence(ModBlocks.BANANA_FENCE)
            .fenceGate(ModBlocks.BANANA_FENCE_GATE)
            .pressurePlate(ModBlocks.BANANA_PRESSURE_PLATE)
            .slab(ModBlocks.BANANA_SLAB)
            .stairs(ModBlocks.BANANA_STAIRS)
            .door(ModBlocks.BANANA_DOOR)
            .trapdoor(ModBlocks.BANANA_TRAPDOOR)
            .sign(ModBlocks.BANANA_SIGN, ModBlocks.BANANA_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily MAHOGANY = new BlockFamily.Builder(ModBlocks.MAHOGANY_PLANKS)
            .button(ModBlocks.MAHOGANY_BUTTON)
            .fence(ModBlocks.MAHOGANY_FENCE)
            .fenceGate(ModBlocks.MAHOGANY_FENCE_GATE)
            .pressurePlate(ModBlocks.MAHOGANY_PRESSURE_PLATE)
            .slab(ModBlocks.MAHOGANY_SLAB)
            .stairs(ModBlocks.MAHOGANY_STAIRS)
            .door(ModBlocks.MAHOGANY_DOOR)
            .trapdoor(ModBlocks.MAHOGANY_TRAPDOOR)
            .sign(ModBlocks.MAHOGANY_SIGN, ModBlocks.MAHOGANY_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily CORN = new BlockFamily.Builder(ModBlocks.CORN_PLANKS)
            .button(ModBlocks.CORN_BUTTON)
            .fence(ModBlocks.CORN_FENCE)
            .fenceGate(ModBlocks.CORN_FENCE_GATE)
            .pressurePlate(ModBlocks.CORN_PRESSURE_PLATE)
            .slab(ModBlocks.CORN_SLAB)
            .stairs(ModBlocks.CORN_STAIRS)
            .door(ModBlocks.CORN_DOOR)
            .trapdoor(ModBlocks.CORN_TRAPDOOR)
            .sign(ModBlocks.CORN_SIGN, ModBlocks.CORN_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily POISONED = new BlockFamily.Builder(ModBlocks.POISONED_PLANKS)
            .button(ModBlocks.POISONED_BUTTON)
            .fence(ModBlocks.POISONED_FENCE)
            .fenceGate(ModBlocks.POISONED_FENCE_GATE)
            .pressurePlate(ModBlocks.POISONED_PRESSURE_PLATE)
            .slab(ModBlocks.POISONED_SLAB)
            .stairs(ModBlocks.POISONED_STAIRS)
            .door(ModBlocks.POISONED_DOOR)
            .trapdoor(ModBlocks.POISONED_TRAPDOOR)
            //.sign(ModBlocks.POISONED_SIGN, ModBlocks.POISONED_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();

    BlockFamily WOODEN_RD20080515 = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_RD20090515)
            .stairs(LegacyBlocks.WOODEN_STAIRS_RD20090515)
            .slab(LegacyBlocks.WOODEN_SLAB_RD20090515)
            .fence(LegacyBlocks.WOODEN_FENCE_RD20090515)
            .fenceGate(LegacyBlocks.WOODEN_FENCE_GATE_RD20090515)
            .button(LegacyBlocks.WOODEN_BUTTON_RD20090515)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_RD161348 = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_RD161348)
            .stairs(LegacyBlocks.WOODEN_STAIRS_RD161348)
            .slab(LegacyBlocks.WOODEN_SLAB_RD161348)
            .fence(LegacyBlocks.WOODEN_FENCE_RD161348)
            .fenceGate(LegacyBlocks.WOODEN_FENCE_GATE_RD161348)
            .button(LegacyBlocks.WOODEN_BUTTON_RD161348)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_C0_0_14A = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_C0_0_14A)
            .stairs(LegacyBlocks.WOODEN_STAIRS_C0_0_14A)
            .slab(LegacyBlocks.WOODEN_SLAB_C0_0_14A)
            .fence(LegacyBlocks.WOODEN_FENCE_C0_0_14A)
            .fenceGate(LegacyBlocks.WOODEN_FENCE_GATE_C0_0_14A)
            .button(LegacyBlocks.WOODEN_BUTTON_C0_0_14A)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_C0_0_15A = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_C0_0_15A)
            .stairs(LegacyBlocks.WOODEN_STAIRS_INF20100629)
            .slab(LegacyBlocks.WOODEN_SLAB_B1_3)
            .door(LegacyBlocks.WOODEN_DOOR_INF20100607)
            .fence(LegacyBlocks.WOODEN_FENCE_A1_0_17)
            .fenceGate(LegacyBlocks.WOODEN_FENCE_GATE_B1_8)
            .trapdoor(LegacyBlocks.TRAPDOOR_B1_6)
            .sign(LegacyBlocks.SIGN_INF20100607, LegacyBlocks.WALL_SIGN_INF20100607)
            .button(LegacyBlocks.WOODEN_BUTTON_C0_0_15A)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily WOODEN_B1_9PRE5 = new BlockFamily.Builder(LegacyBlocks.WOODEN_PLANKS_B1_9PRE5)
            .stairs(LegacyBlocks.WOODEN_STAIRS_B1_9PRE5)
            .slab(LegacyBlocks.WOODEN_SLAB_B1_9PRE5)
            .fence(LegacyBlocks.WOODEN_FENCE_B1_9PRE5)
            .fenceGate(LegacyBlocks.WOODEN_FENCE_GATE_B1_9PRE5)
            .button(LegacyBlocks.WOODEN_BUTTON_1_4)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily COBBLESTONE_RD20090515 = new BlockFamily.Builder(LegacyBlocks.COBBLESTONE_RD20090515)
            .stairs(LegacyBlocks.COBBLESTONE_STAIRS_RD20090515)
            .slab(LegacyBlocks.COBBLESTONE_SLAB_RD20090515)
            .wall(LegacyBlocks.COBBLESTONE_WALL_RD20090515)
            .group("cobblestone")
            .unlockCriterionName("has_cobblestone")
            .build();
    BlockFamily COBBLESTONE_C0_0_14A = new BlockFamily.Builder(LegacyBlocks.COBBLESTONE_C0_0_14A)
            .stairs(LegacyBlocks.COBBLESTONE_STAIRS_INF20100629)
            .slab(LegacyBlocks.COBBLESTONE_SLAB_B1_3)
            .wall(LegacyBlocks.COBBLESTONE_WALL_C0_0_14A)
            .group("cobblestone")
            .unlockCriterionName("has_cobblestone")
            .build();
    BlockFamily COBBLESTONE_B1_7 = new BlockFamily.Builder(LegacyBlocks.COBBLESTONE_B1_7)
            .stairs(LegacyBlocks.COBBLESTONE_STAIRS_B1_7)
            .slab(LegacyBlocks.COBBLESTONE_SLAB_B1_7)
            .wall(LegacyBlocks.COBBLESTONE_WALL_1_4)
            .group("cobblestone")
            .unlockCriterionName("has_cobblestone")
            .build();
    BlockFamily BRICKS_C0_26ST = new BlockFamily.Builder(LegacyBlocks.BRICKS_C0_26ST)
            .slab(LegacyBlocks.BRICK_SLAB_C0_26ST)
            .stairs(LegacyBlocks.BRICK_STAIRS_C0_26ST)
            .group("bricks")
            .unlockCriterionName("has_bricks")
            .build();
    BlockFamily BRICKS_A1_0_11 = new BlockFamily.Builder(LegacyBlocks.BRICKS_A1_0_11)
            .slab(LegacyBlocks.BRICK_SLAB_B1_8)
            .stairs(LegacyBlocks.BRICK_STAIRS_B1_8)
            .group("bricks")
            .unlockCriterionName("has_bricks")
            .build();
    BlockFamily STONE_BRICKS_B1_8 = new BlockFamily.Builder(LegacyBlocks.STONE_BRICKS_B1_8)
            .slab(LegacyBlocks.STONE_BRICK_SLAB_B1_8)
            .stairs(LegacyBlocks.STONE_BRICK_STAIRS_B1_8)
            .cracked(LegacyBlocks.CRACKED_STONE_BRICKS_B1_8)
            .group("stone_bricks")
            .unlockCriterionName("has_stone_bricks")
            .build();
    BlockFamily SANDSTONE_B1_2 = new BlockFamily.Builder(LegacyBlocks.SANDSTONE_B1_2)
            .slab(LegacyBlocks.SANDSTONE_SLAB_B1_3)
            .stairs(LegacyBlocks.SANDSTONE_STAIRS_B1_2)
            .group("sandstone")
            .unlockCriterionName("has_sandstone")
            .build();
    BlockFamily SANDSTONE_1_2_4 = new BlockFamily.Builder(LegacyBlocks.SANDSTONE_1_2_4)
            .slab(LegacyBlocks.SANDSTONE_SLAB_1_2_4)
            .stairs(LegacyBlocks.SANDSTONE_STAIRS_1_3)
            .cut(LegacyBlocks.CUT_SANDSTONE_1_2_4)
            .chiseled(LegacyBlocks.CHISELED_SANDSTONE_1_2_4)
            .group("sandstone")
            .unlockCriterionName("has_sandstone")
            .build();
    BlockFamily NETHER_BRICKS_B1_9PRE = new BlockFamily.Builder(LegacyBlocks.NETHER_BRICKS_B1_9PRE)
            .stairs(LegacyBlocks.NETHER_BRICK_STAIRS_B1_9PRE)
            .fence(LegacyBlocks.NETHER_BRICK_FENCE_B1_9PRE)
            .slab(LegacyBlocks.NETHER_BRICK_SLAB_1_4_6)
            .group("nether_bricks")
            .unlockCriterionName("has_nether_bricks")
            .build();
    BlockFamily BIRCH_1_2_4 = new BlockFamily.Builder(LegacyBlocks.BIRCH_PLANKS_1_2_4)
            .slab(LegacyBlocks.BIRCH_SLAB_1_3)
            .stairs(LegacyBlocks.BIRCH_STAIRS_1_3)
            .fence(LegacyBlocks.BIRCH_FENCE_1_8)
            .fenceGate(LegacyBlocks.BIRCH_FENCE_GATE_1_8)
            .button(LegacyBlocks.BIRCH_BUTTON_1_13)
            .pressurePlate(LegacyBlocks.BIRCH_PRESSURE_PLATE_1_13)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily SPRUCE_1_2_4 = new BlockFamily.Builder(LegacyBlocks.SPRUCE_PLANKS_1_2_4)
            .slab(LegacyBlocks.SPRUCE_SLAB_1_3)
            .stairs(LegacyBlocks.SPRUCE_STAIRS_1_3)
            .fence(LegacyBlocks.SPRUCE_FENCE_1_8)
            .fenceGate(LegacyBlocks.SPRUCE_FENCE_GATE_1_8)
            .button(LegacyBlocks.SPRUCE_BUTTON_1_13)
            .pressurePlate(LegacyBlocks.SPRUCE_PRESSURE_PLATE_1_13)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily JUNGLE_1_2_4 = new BlockFamily.Builder(LegacyBlocks.JUNGLE_PLANKS_1_2_4)
            .slab(LegacyBlocks.JUNGLE_SLAB_1_3)
            .stairs(LegacyBlocks.JUNGLE_STAIRS_1_3)
            .fence(LegacyBlocks.JUNGLE_FENCE_1_8)
            .fenceGate(LegacyBlocks.JUNGLE_FENCE_GATE_1_8)
            .button(LegacyBlocks.JUNGLE_BUTTON_1_13)
            .pressurePlate(LegacyBlocks.JUNGLE_PRESSURE_PLATE_1_13)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily QUARTZ_1_5 = new BlockFamily.Builder(LegacyBlocks.QUARTZ_BLOCK_1_5)
            .chiseled(LegacyBlocks.CHISELED_QUARTZ_BLOCK_1_5)
            .stairs(LegacyBlocks.QUARTZ_STAIRS_1_5)
            .slab(LegacyBlocks.QUARTZ_SLAB_1_5)
            .group("quartz")
            .unlockCriterionName("has_quartz")
            .build();
    BlockFamily ACACIA_1_7 = new BlockFamily.Builder(LegacyBlocks.ACACIA_PLANKS_1_7)
            .stairs(LegacyBlocks.ACACIA_STAIRS_1_7)
            .slab(LegacyBlocks.ACACIA_SLAB_1_7)
            .button(LegacyBlocks.ACACIA_BUTTON_1_13)
            .pressurePlate(LegacyBlocks.ACACIA_PRESSURE_PLATE_1_13)
            .fence(LegacyBlocks.ACACIA_FENCE_1_8)
            .fenceGate(LegacyBlocks.ACACIA_FENCE_GATE_1_8)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily DARK_OAK_1_7 = new BlockFamily.Builder(LegacyBlocks.DARK_OAK_PLANKS_1_7)
            .stairs(LegacyBlocks.DARK_OAK_STAIRS_1_7)
            .slab(LegacyBlocks.DARK_OAK_SLAB_1_7)
            .button(LegacyBlocks.DARK_OAK_BUTTON_1_13)
            .pressurePlate(LegacyBlocks.DARK_OAK_PRESSURE_PLATE_1_13)
            .fence(LegacyBlocks.DARK_OAK_FENCE_1_8)
            .fenceGate(LegacyBlocks.DARK_OAK_FENCE_GATE_1_8)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily GRANITE_1_8 = new BlockFamily.Builder(LegacyBlocks.GRANITE_1_8)
            .polished(LegacyBlocks.POLISHED_GRANITE_1_8)
            .group("stone")
            .unlockCriterionName("has_stone")
            .build();
    BlockFamily DIORITE_1_8 = new BlockFamily.Builder(LegacyBlocks.DIORITE_1_8)
            .polished(LegacyBlocks.POLISHED_DIORITE_1_8)
            .group("stone")
            .unlockCriterionName("has_stone")
            .build();
    BlockFamily ANDESITE_1_8 = new BlockFamily.Builder(LegacyBlocks.ANDESITE_1_8)
            .polished(LegacyBlocks.POLISHED_ANDESITE_1_8)
            .group("stone")
            .unlockCriterionName("has_stone")
            .build();
    BlockFamily PRISMARINE_1_8 = new BlockFamily.Builder(LegacyBlocks.PRISMARINE_1_8)
            .stairs(LegacyBlocks.PRISMARINE_STAIRS_1_13)
            .slab(LegacyBlocks.PRISMARINE_SLAB_1_13)
            .group("prismarine")
            .unlockCriterionName("has_prismarine")
            .build();
    BlockFamily RED_SANDSTONE_1_8 = new BlockFamily.Builder(LegacyBlocks.RED_SANDSTONE_1_8)
            .cut(LegacyBlocks.CUT_RED_SANDSTONE_1_8)
            .chiseled(LegacyBlocks.CHISELED_RED_SANDSTONE_1_8)
            .slab(LegacyBlocks.RED_SANDSTONE_SLAB_1_8)
            .stairs(LegacyBlocks.RED_SANDSTONE_STAIRS_1_8)
            .group("red_sandstone")
            .unlockCriterionName("has_sandstone")
            .build();
    BlockFamily PURPUR_1_9 = new BlockFamily.Builder(LegacyBlocks.PURPUR_BLOCK_1_9)
            .slab(LegacyBlocks.PURPUR_SLAB_1_9)
            .stairs(LegacyBlocks.PURPUR_STAIRS_1_9)
            .group("purpur")
            .unlockCriterionName("has_purpur")
            .build();

    BlockFamily PALE_OAK = new BlockFamily.Builder(FutureBlocks.PALE_OAK_PLANKS)
            .button(FutureBlocks.PALE_OAK_BUTTON)
            .fence(FutureBlocks.PALE_OAK_FENCE)
            .fenceGate(FutureBlocks.PALE_OAK_FENCE_GATE)
            .pressurePlate(FutureBlocks.PALE_OAK_PRESSURE_PLATE)
            .slab(FutureBlocks.PALE_OAK_SLAB)
            .stairs(FutureBlocks.PALE_OAK_STAIRS)
            .door(FutureBlocks.PALE_OAK_DOOR)
            .trapdoor(FutureBlocks.PALE_OAK_TRAPDOOR)
            .sign(FutureBlocks.PALE_OAK_SIGN, FutureBlocks.PALE_OAK_WALL_SIGN)
            .group("wooden")
            .unlockCriterionName("has_planks")
            .build();
    BlockFamily RESIN_BRICKS = new BlockFamily.Builder(FutureBlocks.RESIN_BRICKS)
            .stairs(FutureBlocks.RESIN_BRICK_STAIRS)
            .slab(FutureBlocks.RESIN_BRICK_SLAB)
            .wall(FutureBlocks.RESIN_BRICK_WALL)
            .chiseled(FutureBlocks.CHISELED_RESIN_BRICKS)
            .group("resin")
            .unlockCriterionName("has_resin")
            .build();
}
