package github.mcdatapack.blocktopia.datagen.provider;

import github.mcdatapack.blocktopia.entity.ModEntityTypes;
import github.mcdatapack.blocktopia.fluid.ModFluids;

import static github.mcdatapack.blocktopia.block.FutureBlocks.*;
import static github.mcdatapack.blocktopia.item.FutureItems.PALE_OAK_BOAT;
import static github.mcdatapack.blocktopia.item.FutureItems.PALE_OAK_CHEST_BOAT;
import static github.mcdatapack.blocktopia.item.ModItems.*;
import static github.mcdatapack.blocktopia.block.ModBlocks.*;
import static github.mcdatapack.blocktopia.block.LegacyBlocks.*;
import static github.mcdatapack.blocktopia.block.LegacyBlocks.TORCH_IN20100124_2;
import static net.minecraft.block.Blocks.*;
import static net.minecraft.item.Items.*;

import github.mcdatapack.blocktopia.block.LegacyBlocks;
import github.mcdatapack.blocktopia.worldgen.biome.ModBiomes;
import github.mcdatapack.blocktopia.item.ModItems;
import github.mcdatapack.blocktopia.util.ModTags;

import java.util.concurrent.CompletableFuture;

import github.mcdatapack.blocktopia.villager.ModVillagers;
import github.mcdatapack.more_tools_and_armor.list.TagList;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.fabricmc.fabric.api.tag.convention.v2.ConventionalBlockTags;
import net.fabricmc.fabric.api.tag.convention.v2.ConventionalItemTags;
import net.minecraft.block.Blocks;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.Item;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.Items;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.*;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.poi.PointOfInterestType;

public class BlocktopiaTagProvider {
    public static class BlocktopiaBlockTagProvider extends FabricTagProvider.BlockTagProvider {
        public BlocktopiaBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
            super(output, registriesFuture);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
            getOrCreateTagBuilder(BlockTags.ANVIL)
                    .add(GOLD_ANVIL, CHIPPED_GOLD_ANVIL, DAMAGED_GOLD_ANVIL, DIAMOND_ANVIL, CHIPPED_DIAMOND_ANVIL, DAMAGED_DIAMOND_ANVIL, NETHERITE_ANVIL, CHIPPED_NETHERITE_ANVIL, DAMAGED_NETHERITE_ANVIL);

            getOrCreateTagBuilder(BlockTags.AXE_MINEABLE)
                    .addTag(ModTags.Blocks.CHAIRS)
                    .add(SMALL_CHEST, BOOKSHELF_C0_26ST, BOOKSHELF_B1_9PRE5, CRAFTING_TABLE_IN20100131, CRAFTING_TABLE_1_14, LADDER_INF20100607, LADDER_INF20100618, CARVED_PUMPKIN_A1_2_0,
                            JACK_O_LANTERN_A1_2_0, NOTE_BLOCK_B1_2, VINES_B1_8, MUSHROOM_STEM_B1_8, RED_MUSHROOM_BLOCK_B1_8, BROWN_MUSHROOM_BLOCK_B1_8, MELON_BLOCK_B1_8, COCOA_1_3);
            getOrCreateTagBuilder(BlockTags.HOE_MINEABLE)
                    .add(PAPER_BLOCK)
                    .add(PALM_LEAVES, BANANA_LEAVES, CORN_LEAVES, POISONED_LEAVES, MAHOGANY_LEAVES, PALE_OAK_LEAVES, FLOWERING_CHERRY_LEAVES, LEAVES_C0_0_14A, LEAVES_C0_0_15A, LEAVES_C0_24ST, SPONGE_C0_0_19A,
                            SPONGE_1_8, WET_SPONGE_1_8, HAY_BALE_1_6, BIRCH_LEAVES_B1_2, SPRUCE_LEAVES_B1_2, JUNGLE_LEAVES_1_2, ACACIA_LEAVES_1_7, DARK_OAK_LEAVES_1_7,
                            NETHER_WART_BLOCK_1_10, NETHER_WART_BLOCK_1_14);
            getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                    .add(COBBLESTONE_RD20090515, COBBLESTONE_C0_0_14A, COBBLESTONE_B1_7, COAL_ORE_C0_0_14A, COAL_ORE_1_14, IRON_ORE_C0_0_14A, IRON_ORE_1_14, IRON_ORE_1_14_1, GOLD_ORE_C0_0_14A,
                            GOLD_ORE_C0_26ST, GOLD_ORE_1_14, GOLD_BLOCK_C0_0_20A, GOLD_BLOCK_C0_26ST, GOLD_BLOCK_A1_2_0, GOLD_BLOCK_B1_9PRE5, STONE_SLAB_C0_26ST, IRON_BLOCK_C0_26ST,
                            IRON_BLOCK_A1_2_0, IRON_BLOCK_B1_9PRE5, MOSSY_COBBLESTONE_C0_26ST, MOSSY_COBBLESTONE_B1_8, BRICKS_C0_26ST, BRICKS_A1_0_11, OBSIDIAN_C0_28A, DIAMOND_ORE_IN20100128,
                            DIAMOND_ORE_1_14, DIAMOND_BLOCK_IN20100128, DIAMOND_BLOCK_A1_2_0, DIAMOND_BLOCK_B1_9PRE5, FURNACE_IN20100219, FURNACE_B1_2,
                            COBBLESTONE_STAIRS_RD20090515, COBBLESTONE_STAIRS_INF20100629, COBBLESTONE_STAIRS_B1_7, REDSTONE_ORE_A1_0_1, REDSTONE_ORE_1_14, ICE_A1_0_4, NETHERRACK_A1_2_0,
                            NETHERRACK_B1_9PRE5, GLOWSTONE_A1_2_0, GLOWSTONE_B1_9PRE5, LEGACY_CUTTER, DUPER, LAPIS_ORE_B1_2, LAPIS_ORE_1_14, LAPIS_BLOCK_B1_2, LAPIS_BLOCK_1_6,
                            SANDSTONE_B1_2, SANDSTONE_1_2_4, CRYING_OBSIDIAN_B1_3, COBBLESTONE_SLAB_RD20090515, COBBLESTONE_SLAB_B1_3, COBBLESTONE_SLAB_B1_7,
                            SANDSTONE_SLAB_B1_3, SANDSTONE_SLAB_1_2_4, SMOOTH_STONE_B1_3, STONE_BRICKS_B1_8, CRACKED_STONE_BRICKS_B1_8, MOSSY_STONE_BRICKS_B1_8, BRICK_SLAB_C0_26ST,
                            BRICK_SLAB_B1_8, STONE_BRICK_SLAB_B1_8, BRICK_STAIRS_C0_26ST, BRICK_STAIRS_B1_8, STONE_BRICK_STAIRS_B1_8, NETHER_BRICKS_B1_9PRE, NETHER_BRICK_STAIRS_B1_9PRE,
                            NETHER_BRICK_FENCE_B1_9PRE, ENDSTONE_B1_9PRE4, CHISELED_STONE_BRICKS_1_2, CUT_SANDSTONE_1_2_4, CHISELED_SANDSTONE_1_2_4, BIRCH_SLAB_1_3,
                            RUBY_ORE, EMERALD_ORE_1_3, EMERALD_ORE_1_14, SANDSTONE_STAIRS_B1_2, SANDSTONE_STAIRS_1_3, EMERALD_BLOCK_1_3, COBBLESTONE_WALL_RD20090515,
                            COBBLESTONE_WALL_C0_0_14A, COBBLESTONE_WALL_1_4, NETHER_BRICK_SLAB_1_4_6, QUARTZ_ORE_1_5, REDSTONE_BLOCK_1_5, QUARTZ_BLOCK_1_5, CHISELED_QUARTZ_BLOCK_1_5,
                            QUARTZ_PILLAR_1_5, QUARTZ_SLAB_1_5, QUARTZ_STAIRS_1_5, SMOOTH_SANDSTONE_1_5, SMOOTH_QUARTZ_1_5, TERRACOTTA_1_6, COAL_BLOCK_1_6, PACKED_ICE_1_7,
                            GRANITE_1_8, POLISHED_GRANITE_1_8, DIORITE_1_8, POLISHED_DIORITE_1_8, ANDESITE_1_8, POLISHED_ANDESITE_1_8, PRISMARINE_1_8, PRISMARINE_BRICKS_1_8, DARK_PRISMARINE_1_8,
                            RED_SANDSTONE_1_8, CUT_RED_SANDSTONE_1_8, CHISELED_RED_SANDSTONE_1_8, SMOOTH_RED_SANDSTONE_1_8, RED_SANDSTONE_SLAB_1_8, RED_SANDSTONE_STAIRS_1_8, ENDSTONE_BRICKS_1_9,
                            PURPUR_BLOCK_1_9, PURPUR_PILLAR_1_9, PURPUR_SLAB_1_9, PURPUR_STAIRS_1_9, BONE_BLOCK_1_10, MAGMA_BLOCK_1_10, RED_NETHER_BRICKS_1_10, PRISMARINE_SLAB_1_13, PRISMARINE_STAIRS_1_13,
                            WOODCUTTER, RESIN_BRICKS, RESIN_BRICK_SLAB, RESIN_BRICK_STAIRS, RESIN_BRICK_WALL, CHISELED_RESIN_BRICKS, FLUID_TANK);
            getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE)
                    .add(SANDY_DIRT, GUNPOWDER_BLOCK, FIREWORK_BLOCK, SAND_C0_0_14A, SAND_C0_0_15A, SAND_B1_9PRE6, GRAVEL_C0_0_14A, GRAVEL_C0_0_15A, GRAVEL_B1_9PRE5, GRAVEL_1_3, SNOW_A1_0_4,
                            SNOW_BLOCK_A1_0_5, CLAY_BLOCK_A1_0_11, SOUL_SAND_A1_2_0, RED_SAND_1_7);
            getOrCreateTagBuilder(TagList.BlockTags.PAXEL_MINEABLE)
                    .add(COBWEB_B1_5, GLASS_C0_0_19A, GLASS_PANE_B1_8, REDSTONE_LAMP_1_2, WHITE_STAINED_GLASS_1_7, ORANGE_STAINED_GLASS_1_7,
                            MAGENTA_STAINED_GLASS_1_7, LIGHT_BLUE_STAINED_GLASS_1_7, YELLOW_STAINED_GLASS_1_7, LIME_STAINED_GLASS_1_7, PINK_STAINED_GLASS_1_7,
                            GRAY_STAINED_GLASS_1_7, LIGHT_GRAY_STAINED_GLASS_1_7, CYAN_STAINED_GLASS_1_7, PURPLE_STAINED_GLASS_1_7, BLUE_STAINED_GLASS_1_7, BROWN_STAINED_GLASS_1_7,
                            GREEN_STAINED_GLASS_1_7, RED_STAINED_GLASS_1_7, BLACK_STAINED_GLASS_1_7, WHITE_STAINED_GLASS_PANE_1_7, ORANGE_STAINED_GLASS_PANE_1_7, MAGENTA_STAINED_GLASS_PANE_1_7,
                            LIGHT_BLUE_STAINED_GLASS_PANE_1_7, YELLOW_STAINED_GLASS_PANE_1_7, LIME_STAINED_GLASS_PANE_1_7, PINK_STAINED_GLASS_PANE_1_7, GRAY_STAINED_GLASS_PANE_1_7,
                            LIGHT_GRAY_STAINED_GLASS_PANE_1_7, CYAN_STAINED_GLASS_PANE_1_7, PURPLE_STAINED_GLASS_PANE_1_7, BLUE_STAINED_GLASS_PANE_1_7, BROWN_STAINED_GLASS_PANE_1_7,
                            GREEN_STAINED_GLASS_PANE_1_7, RED_STAINED_GLASS_PANE_1_7, BLACK_STAINED_GLASS_PANE_1_7, COBWEB_B1_5);
            getOrCreateTagBuilder(BlockTags.SWORD_EFFICIENT)
                    .add(COBWEB_B1_5);
            getOrCreateTagBuilder(BlockTags.NEEDS_DIAMOND_TOOL)
                    .add(OBSIDIAN_C0_28A, CRYING_OBSIDIAN_B1_3);
            getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)
                    .add(GOLD_ORE_C0_0_14A, GOLD_ORE_C0_26ST, GOLD_ORE_1_14, GOLD_BLOCK_C0_0_20A, GOLD_BLOCK_C0_26ST, GOLD_BLOCK_A1_2_0, GOLD_BLOCK_B1_9PRE5, DIAMOND_ORE_IN20100128,
                            DIAMOND_ORE_1_14, DIAMOND_BLOCK_IN20100128, DIAMOND_BLOCK_A1_2_0, DIAMOND_BLOCK_B1_9PRE5, REDSTONE_ORE_A1_0_1, REDSTONE_ORE_1_14, RUBY_ORE, EMERALD_ORE_1_3, EMERALD_ORE_1_14,
                            EMERALD_BLOCK_1_3);
            getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL)
                    .add(IRON_ORE_C0_0_14A, IRON_ORE_1_14, IRON_ORE_1_14_1, IRON_BLOCK_C0_26ST, IRON_BLOCK_A1_2_0, IRON_BLOCK_B1_9PRE5, LAPIS_ORE_B1_2, LAPIS_ORE_1_14,
                            LAPIS_BLOCK_B1_2, LAPIS_BLOCK_1_6);
            getOrCreateTagBuilder(ModTags.Blocks.LEGACY_BLOCKS)
                    .add(COBBLESTONE_RD20090515, COBBLESTONE_C0_0_14A, COBBLESTONE_B1_7, WOODEN_PLANKS_RD20090515, WOODEN_PLANKS_RD161348, WOODEN_PLANKS_C0_0_14A, WOODEN_PLANKS_C0_0_15A,
                            WOODEN_PLANKS_B1_9PRE5, SAPLING_RD161348, SAPLING_C0_0_13A, SAPLING_C0_24ST, BEDROCK_C0_0_12A, SAND_C0_0_14A, SAND_C0_0_15A, SAND_B1_9PRE6, GRAVEL_C0_0_14A,
                            GRAVEL_C0_0_15A, GRAVEL_B1_9PRE5, GRAVEL_1_3, COAL_ORE_C0_0_14A, COAL_ORE_1_14, IRON_ORE_C0_0_14A, IRON_ORE_1_14, IRON_ORE_1_14_1, GOLD_ORE_C0_0_14A, GOLD_ORE_C0_26ST,
                            GOLD_ORE_1_14, LOG_C0_0_14A, LEAVES_C0_0_14A, LEAVES_C0_0_15A, LEAVES_C0_24ST, SPONGE_C0_0_19A, SPONGE_1_8, WET_SPONGE_1_8, GLASS_C0_0_19A, WHITE_CLOTH,
                            LIGHT_GRAY_CLOTH_C0_0_20A, LIGHT_GRAY_CLOTH_C0_28A, DARK_GRAY_CLOTH_C0_0_20A, DARK_GRAY_CLOTH_C0_28A, RED_CLOTH, ORANGE_CLOTH, YELLOW_CLOTH, CHARTREUSE_CLOTH,
                            SPRING_GREEN_CLOTH, CYAN_CLOTH, CAPRI_CLOTH, ULTRAMARINE_CLOTH, VIOLET_CLOTH, PURPLE_CLOTH, MAGENTA_CLOTH, ROSE_CLOTH, GOLD_BLOCK_C0_0_20A, GOLD_BLOCK_C0_26ST,
                            GOLD_BLOCK_A1_2_0, GOLD_BLOCK_B1_9PRE5, DANDELION_C0_0_20A, ROSE_C0_0_20A, POPPY_1_7, RED_MUSHROOM_C0_0_20A, BROWN_MUSHROOM_C0_0_20A, STONE_SLAB_C0_26ST,
                            IRON_BLOCK_C0_26ST, IRON_BLOCK_A1_2_0, IRON_BLOCK_B1_9PRE5, TNT_C0_26ST, TNT_C0_28A, MOSSY_COBBLESTONE_C0_26ST, MOSSY_COBBLESTONE_B1_8, BRICKS_C0_26ST, BRICKS_A1_0_11,
                            BOOKSHELF_C0_26ST, BOOKSHELF_B1_9PRE5, OBSIDIAN_C0_28A, TORCH_IN20100124_2, WALL_TORCH_IN20100124_2, DIAMOND_ORE_IN20100128, DIAMOND_ORE_1_14, DIAMOND_BLOCK_IN20100128,
                            DIAMOND_BLOCK_A1_2_0, DIAMOND_BLOCK_B1_9PRE5, CRAFTING_TABLE_IN20100131, CRAFTING_TABLE_1_14, FURNACE_IN20100219, FURNACE_B1_2,
                            LADDER_INF20100607, LADDER_INF20100618, WOODEN_DOOR_INF20100607, WOODEN_STAIRS_RD20090515, WOODEN_STAIRS_RD161348,
                            WOODEN_STAIRS_C0_0_14A, WOODEN_STAIRS_INF20100629, WOODEN_STAIRS_B1_9PRE5, COBBLESTONE_STAIRS_RD20090515, COBBLESTONE_STAIRS_INF20100629, COBBLESTONE_STAIRS_B1_7,
                            REDSTONE_ORE_A1_0_1, REDSTONE_ORE_1_14, LegacyBlocks.REDSTONE_TORCH_A1_0_1, REDSTONE_WALL_TORCH_A1_0_1, SNOW_A1_0_4, ICE_A1_0_4, SNOW_BLOCK_A1_0_5, CLAY_BLOCK_A1_0_11,
                            WOODEN_FENCE_RD20090515, WOODEN_FENCE_RD161348, WOODEN_FENCE_C0_0_14A, WOODEN_FENCE_A1_0_17, WOODEN_FENCE_B1_9PRE5, NETHERRACK_A1_2_0,
                            NETHERRACK_B1_9PRE5, SOUL_SAND_A1_2_0, GLOWSTONE_A1_2_0, GLOWSTONE_B1_9PRE5, CARVED_PUMPKIN_A1_2_0, JACK_O_LANTERN_A1_2_0,
                            LIGHT_GRAY_WOOL_B1_2, GRAY_WOOL_B1_2, BLACK_WOOL_B1_2, BROWN_WOOL_B1_2, RED_WOOL_B1_2, ORANGE_WOOL_B1_2, YELLOW_WOOL_B1_2, LIME_WOOL_B1_2 , GREEN_WOOL_B1_2, CYAN_WOOL_B1_2,
                            LIGHT_BLUE_WOOL_B1_2, BLUE_WOOL_B1_2 , PURPLE_WOOL_B1_2, MAGENTA_WOOL_B1_2, PINK_WOOL_B1_2, LIGHT_GRAY_WOOL_1_2_4, GRAY_WOOL_1_2_4, BLACK_WOOL_1_2_4, BROWN_WOOL_1_2_4,
                            RED_WOOL_1_2_4, ORANGE_WOOL_1_2_4, YELLOW_WOOL_1_2_4, LIME_WOOL_1_2_4, GREEN_WOOL_1_2_4, CYAN_WOOL_1_2_4, LIGHT_BLUE_WOOL_1_2_4, BLUE_WOOL_1_2_4,
                            PURPLE_WOOL_1_2_4, MAGENTA_WOOL_1_2_4, PINK_WOOL_1_2_4, LAPIS_ORE_B1_2, LAPIS_ORE_1_14, LAPIS_BLOCK_B1_2, LAPIS_BLOCK_1_6, NOTE_BLOCK_B1_2, SANDSTONE_B1_2, SANDSTONE_1_2_4,
                            BIRCH_LOG_B1_2, BIRCH_LOG_1_7, BIRCH_LEAVES_B1_2, SPRUCE_LOG_B1_2, SPRUCE_LOG_1_7, SPRUCE_LEAVES_B1_2, CRYING_OBSIDIAN_B1_3, COBBLESTONE_SLAB_RD20090515, COBBLESTONE_SLAB_B1_3,
                            COBBLESTONE_SLAB_B1_7, WOODEN_SLAB_RD20090515, WOODEN_SLAB_RD161348, WOODEN_SLAB_C0_0_14A, WOODEN_SLAB_B1_3, WOODEN_SLAB_B1_9PRE5, SANDSTONE_SLAB_B1_3,
                            SANDSTONE_SLAB_1_2_4, SMOOTH_STONE_B1_3, BIRCH_SAPLING_B1_5, SPRUCE_SAPLING_B1_5, POWERED_RAIL_B1_5, DETECTOR_RAIL_B1_5, COBWEB_B1_5, DEAD_BUSH_B1_6, SHRUB_B1_6,
                            SHORT_GRASS_B1_6, FERN_B1_6, TRAPDOOR_B1_6, STONE_BRICKS_B1_8, CRACKED_STONE_BRICKS_B1_8, MOSSY_STONE_BRICKS_B1_8, INFESTED_COBBLESTONE_RD20090515,
                            INFESTED_COBBLESTONE_C0_0_14A, INFESTED_COBBLESTONE_B1_8, INFESTED_STONE_BRICKS_B1_8, BRICK_SLAB_C0_26ST, BRICK_SLAB_B1_8, STONE_BRICK_SLAB_B1_8, BRICK_STAIRS_C0_26ST,
                            BRICK_STAIRS_B1_8, STONE_BRICK_STAIRS_B1_8, GLASS_PANE_B1_8, WOODEN_FENCE_GATE_RD20090515, WOODEN_FENCE_GATE_RD161348, WOODEN_FENCE_GATE_C0_0_14A, WOODEN_FENCE_GATE_B1_8,
                            WOODEN_FENCE_GATE_B1_9PRE5, VINES_B1_8, MUSHROOM_STEM_B1_8, RED_MUSHROOM_BLOCK_B1_8, BROWN_MUSHROOM_BLOCK_B1_8, MELON_BLOCK_B1_8, NETHER_BRICKS_B1_9PRE,
                            NETHER_BRICK_STAIRS_B1_9PRE, NETHER_BRICK_FENCE_B1_9PRE, LILY_PAD_B1_9PRE, ENDSTONE_B1_9PRE4, JUNGLE_LOG_1_2, JUNGLE_LOG_1_7, JUNGLE_LEAVES_1_2, JUNGLE_SAPLING_1_2,
                            REDSTONE_LAMP_1_2, CHISELED_STONE_BRICKS_1_2, BIRCH_PLANKS_1_2_4, SPRUCE_PLANKS_1_2_4, JUNGLE_PLANKS_1_2_4, CUT_SANDSTONE_1_2_4, CHISELED_SANDSTONE_1_2_4,
                            BIRCH_SLAB_1_3, SPRUCE_SLAB_1_3, JUNGLE_SLAB_1_3, COCOA_1_3, RUBY_ORE, EMERALD_ORE_1_3, EMERALD_ORE_1_14, SANDSTONE_STAIRS_B1_2, SANDSTONE_STAIRS_1_3, EMERALD_BLOCK_1_3,
                            BIRCH_STAIRS_1_3, SPRUCE_STAIRS_1_3, JUNGLE_STAIRS_1_3, OAK_WOOD_1_3, BIRCH_WOOD_1_3, SPRUCE_WOOD_1_3, JUNGLE_WOOD_1_3, WOODEN_BUTTON_RD20090515, WOODEN_BUTTON_RD161348,
                            WOODEN_BUTTON_C0_0_14A, WOODEN_BUTTON_C0_0_15A, WOODEN_BUTTON_1_4, COBBLESTONE_WALL_RD20090515, COBBLESTONE_WALL_C0_0_14A, COBBLESTONE_WALL_1_4, NETHER_BRICK_SLAB_1_4_6,
                            QUARTZ_ORE_1_5, REDSTONE_BLOCK_1_5, ACTIVATOR_RAIL_1_5, QUARTZ_BLOCK_1_5, CHISELED_QUARTZ_BLOCK_1_5, QUARTZ_PILLAR_1_5, QUARTZ_SLAB_1_5, QUARTZ_STAIRS_1_5,
                            SMOOTH_SANDSTONE_1_5, SMOOTH_QUARTZ_1_5, LIGHT_GRAY_CLOTH_CARPET_C0_0_20A, LIGHT_GRAY_CLOTH_CARPET_C0_28A, DARK_GRAY_CLOTH_CARPET_C0_0_20A, DARK_GRAY_CLOTH_CARPET_C0_28A,
                            RED_CLOTH_CARPET, ORANGE_CLOTH_CARPET, YELLOW_CLOTH_CARPET, CHARTREUSE_CLOTH_CARPET, SPRING_GREEN_CLOTH_CARPET, CYAN_CLOTH_CARPET, CAPRI_CLOTH_CARPET, ULTRAMARINE_CLOTH_CARPET,
                            VIOLET_CLOTH_CARPET, PURPLE_CLOTH_CARPET, MAGENTA_CLOTH_CARPET, ROSE_CLOTH_CARPET, GRAY_CARPET_B1_2, BLACK_CARPET_B1_2, BROWN_CARPET_B1_2, RED_CARPET_B1_2,
                            ORANGE_CARPET_B1_2, YELLOW_CARPET_B1_2, LIME_CARPET_B1_2, GREEN_CARPET_B1_2, CYAN_CARPET_B1_2, LIGHT_BLUE_CARPET_B1_2, BLUE_CARPET_B1_2,
                            PURPLE_CARPET_B1_2, MAGENTA_CARPET_B1_2, PINK_CARPET_B1_2, LIGHT_GRAY_CARPET_1_2_4, GRAY_CARPET_1_2_4, BLACK_CARPET_1_2_4, BROWN_CARPET_1_2_4,
                            RED_CARPET_1_2_4, ORANGE_CARPET_1_2_4, YELLOW_CARPET_1_2_4, LIME_CARPET_1_2_4, GREEN_CARPET_1_2_4, CYAN_CARPET_1_2_4, LIGHT_BLUE_CARPET_1_2_4,
                            BLUE_CARPET_1_2_4, PURPLE_CARPET_1_2_4, MAGENTA_CARPET_1_2_4, PINK_CARPET_1_2_4, HAY_BALE_1_6, TERRACOTTA_1_6, COAL_BLOCK_1_6,
                            ALLIUM_1_7, AZURE_BLUET_1_7, BLUE_ORCHID_1_7, LILAC_1_7, PEONY_1_7, ROSE_BUSH_1_7, SUNFLOWER_1_7, OXEYE_DAISY_1_7,
                            RED_TULIP_1_7, ORANGE_TULIP_1_7, WHITE_TULIP_1_7, PINK_TULIP_1_7, LARGE_FERN_1_7, TALL_GRASS_1_7, PACKED_ICE_1_7, INFESTED_CRACKED_STONE_BRICKS_1_7,
                            INFESTED_MOSSY_STONE_BRICKS_1_7, INFESTED_CHISELED_STONE_BRICKS_1_7, RED_SAND_1_7, WHITE_STAINED_GLASS_1_7, ORANGE_STAINED_GLASS_1_7,
                            MAGENTA_STAINED_GLASS_1_7, LIGHT_BLUE_STAINED_GLASS_1_7, YELLOW_STAINED_GLASS_1_7, LIME_STAINED_GLASS_1_7, PINK_STAINED_GLASS_1_7,
                            GRAY_STAINED_GLASS_1_7, LIGHT_GRAY_STAINED_GLASS_1_7, CYAN_STAINED_GLASS_1_7, PURPLE_STAINED_GLASS_1_7, BLUE_STAINED_GLASS_1_7, BROWN_STAINED_GLASS_1_7,
                            GREEN_STAINED_GLASS_1_7, RED_STAINED_GLASS_1_7, BLACK_STAINED_GLASS_1_7, WHITE_STAINED_GLASS_PANE_1_7, ORANGE_STAINED_GLASS_PANE_1_7, MAGENTA_STAINED_GLASS_PANE_1_7,
                            LIGHT_BLUE_STAINED_GLASS_PANE_1_7, YELLOW_STAINED_GLASS_PANE_1_7, LIME_STAINED_GLASS_PANE_1_7, PINK_STAINED_GLASS_PANE_1_7, GRAY_STAINED_GLASS_PANE_1_7,
                            LIGHT_GRAY_STAINED_GLASS_PANE_1_7, CYAN_STAINED_GLASS_PANE_1_7, PURPLE_STAINED_GLASS_PANE_1_7, BLUE_STAINED_GLASS_PANE_1_7, BROWN_STAINED_GLASS_PANE_1_7,
                            GREEN_STAINED_GLASS_PANE_1_7, RED_STAINED_GLASS_PANE_1_7, BLACK_STAINED_GLASS_PANE_1_7, ACACIA_LOG_1_7, ACACIA_WOOD_1_7, ACACIA_LEAVES_1_7, ACACIA_SAPLING_1_7,
                            DARK_OAK_LOG_1_7, DARK_OAK_WOOD_1_7, DARK_OAK_LEAVES_1_7, DARK_OAK_SAPLING_1_7, ACACIA_PLANKS_1_7, ACACIA_STAIRS_1_7, ACACIA_SLAB_1_7, DARK_OAK_PLANKS_1_7,
                            DARK_OAK_STAIRS_1_7, DARK_OAK_SLAB_1_7, GRANITE_1_8, POLISHED_GRANITE_1_8, DIORITE_1_8, POLISHED_DIORITE_1_8, ANDESITE_1_8, POLISHED_ANDESITE_1_8, SLIME_BLOCK_1_8,
                            PRISMARINE_1_8, PRISMARINE_BRICKS_1_8, DARK_PRISMARINE_1_8, RED_SANDSTONE_1_8, CUT_RED_SANDSTONE_1_8, CHISELED_RED_SANDSTONE_1_8, SMOOTH_RED_SANDSTONE_1_8,
                            RED_SANDSTONE_SLAB_1_8, RED_SANDSTONE_STAIRS_1_8, BIRCH_FENCE_1_8, SPRUCE_FENCE_1_8, JUNGLE_FENCE_1_8, ACACIA_FENCE_1_8, DARK_OAK_FENCE_1_8, END_ROD_1_9, ENDSTONE_BRICKS_1_9,
                            PURPUR_BLOCK_1_9, PURPUR_PILLAR_1_9, PURPUR_SLAB_1_9, PURPUR_STAIRS_1_9, BONE_BLOCK_1_10, MAGMA_BLOCK_1_10, NETHER_WART_BLOCK_1_10, NETHER_WART_BLOCK_1_14,
                            RED_NETHER_BRICKS_1_10, BIRCH_BUTTON_1_13, SPRUCE_BUTTON_1_13, JUNGLE_BUTTON_1_13, ACACIA_BUTTON_1_13, DARK_OAK_BUTTON_1_13,
                            BIRCH_PRESSURE_PLATE_1_13, SPRUCE_PRESSURE_PLATE_1_13, JUNGLE_PRESSURE_PLATE_1_13, ACACIA_PRESSURE_PLATE_1_13, DARK_OAK_PRESSURE_PLATE_1_13, PRISMARINE_SLAB_1_13,
                            PRISMARINE_STAIRS_1_13);
            getOrCreateTagBuilder(ModTags.Blocks.PALM_LOGS)
                    .add(PALM_LOG, STRIPPED_PALM_LOG, PALM_WOOD, STRIPPED_PALM_WOOD);
            getOrCreateTagBuilder(ModTags.Blocks.LEGACY_COBBLESTONE)
                    .add(COBBLESTONE_RD20090515, COBBLESTONE_C0_0_14A, COBBLESTONE_B1_7);
            getOrCreateTagBuilder(ModTags.Blocks.BANANA_LOGS)
                    .add(BANANA_LOG, STRIPPED_BANANA_LOG, BANANA_WOOD, STRIPPED_BANANA_WOOD);
            getOrCreateTagBuilder(ModTags.Blocks.CORN_LOGS)
                    .add(CORN_LOG, STRIPPED_CORN_LOG, CORN_WOOD, STRIPPED_CORN_WOOD);
            getOrCreateTagBuilder(ModTags.Blocks.POISONED_LOGS)
                    .add(POISONED_LOG, STRIPPED_POISONED_LOG, POISONED_WOOD, STRIPPED_POISONED_WOOD);
            getOrCreateTagBuilder(ModTags.Blocks.MAHOGANY_LOGS)
                    .add(MAHOGANY_LOG, STRIPPED_MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_WOOD);
            getOrCreateTagBuilder(ModTags.Blocks.PALE_OAK_LOGS)
                    .add(PALE_OAK_LOG, STRIPPED_PALE_OAK_LOG, PALE_OAK_WOOD, STRIPPED_PALE_OAK_WOOD);
            getOrCreateTagBuilder(BlockTags.INFINIBURN_OVERWORLD)
                    .add(NETHERRACK_A1_2_0, NETHERRACK_B1_9PRE5);
            getOrCreateTagBuilder(BlockTags.SOUL_FIRE_BASE_BLOCKS)
                    .add(SOUL_SAND_A1_2_0);
            getOrCreateTagBuilder(BlockTags.DRAGON_IMMUNE)
                    .add(BEDROCK_C0_0_12A);
            getOrCreateTagBuilder(BlockTags.FENCE_GATES)
                    .add(PALM_FENCE_GATE, BANANA_FENCE_GATE, CORN_FENCE_GATE, POISONED_FENCE_GATE, MAHOGANY_FENCE_GATE, PALE_OAK_FENCE_GATE, WOODEN_FENCE_GATE_RD20090515, WOODEN_FENCE_GATE_RD161348, WOODEN_FENCE_GATE_C0_0_14A,
                            WOODEN_FENCE_GATE_B1_8, WOODEN_FENCE_GATE_B1_9PRE5, BIRCH_FENCE_GATE_1_8, SPRUCE_FENCE_GATE_1_8, JUNGLE_FENCE_GATE_1_8, ACACIA_FENCE_GATE_1_8, DARK_OAK_FENCE_GATE_1_8);
            getOrCreateTagBuilder(BlockTags.INFINIBURN_END)
                    .add(BEDROCK_C0_0_12A);
            getOrCreateTagBuilder(BlockTags.LEAVES)
                    .add(PALM_LEAVES, BANANA_LEAVES, CORN_LEAVES, POISONED_LEAVES, MAHOGANY_LEAVES, PALE_OAK_LEAVES, FLOWERING_CHERRY_LEAVES, LEAVES_C0_0_14A, LEAVES_C0_0_15A, LEAVES_C0_24ST,
                            BIRCH_LEAVES_B1_2, SPRUCE_LEAVES_B1_2, JUNGLE_LEAVES_1_2, ACACIA_LEAVES_1_7, DARK_OAK_LEAVES_1_7);
            getOrCreateTagBuilder(BlockTags.LOGS_THAT_BURN)
                    .addTag(ModTags.Blocks.PALM_LOGS).addTag(ModTags.Blocks.BANANA_LOGS).addTag(ModTags.Blocks.CORN_LOGS).addTag(ModTags.Blocks.POISONED_LOGS).addTag(ModTags.Blocks.MAHOGANY_LOGS)
                    .addTag(ModTags.Blocks.PALE_OAK_LOGS)
                    .add(LOG_C0_0_14A, BIRCH_LOG_B1_2, BIRCH_LOG_1_7, SPRUCE_LOG_B1_2, SPRUCE_LOG_1_7, JUNGLE_LOG_1_2, JUNGLE_LOG_1_7, OAK_WOOD_1_3, BIRCH_WOOD_1_3, SPRUCE_WOOD_1_3, JUNGLE_WOOD_1_3,
                            ACACIA_LOG_1_7, ACACIA_WOOD_1_7, DARK_OAK_LOG_1_7, DARK_OAK_WOOD_1_7);
            getOrCreateTagBuilder(BlockTags.PLANKS)
                    .add(PALM_PLANKS, BANANA_PLANKS, CORN_PLANKS, POISONED_PLANKS, MAHOGANY_PLANKS, PALE_OAK_PLANKS, WOODEN_PLANKS_RD20090515, WOODEN_PLANKS_RD161348, WOODEN_PLANKS_C0_0_14A, WOODEN_PLANKS_C0_0_15A,
                            WOODEN_PLANKS_B1_9PRE5, BIRCH_PLANKS_1_2_4, SPRUCE_PLANKS_1_2_4, JUNGLE_PLANKS_1_2_4, ACACIA_PLANKS_1_7, DARK_OAK_PLANKS_1_7);
            getOrCreateTagBuilder(BlockTags.SAPLINGS)
                    .add(PALM_SAPLING, BANANA_SAPLING, CORN_SAPLING, POISONED_SAPLING, MAHOGANY_SAPLING, PALE_OAK_SAPLING, FLOWERING_CHERRY_SAPLING, SAPLING_RD161348, SAPLING_C0_0_13A, SAPLING_C0_24ST,
                            BIRCH_SAPLING_B1_5, SPRUCE_SAPLING_B1_5, JUNGLE_SAPLING_1_2, ACACIA_SAPLING_1_7, DARK_OAK_SAPLING_1_7);
            getOrCreateTagBuilder(BlockTags.SLABS)
                    .add(STONE_SLAB_C0_26ST, NETHER_BRICK_SLAB_1_4_6, QUARTZ_SLAB_1_5, RED_SANDSTONE_SLAB_1_8, PURPUR_SLAB_1_9, PRISMARINE_SLAB_1_13,
                            COBBLESTONE_SLAB_RD20090515, COBBLESTONE_SLAB_B1_3, COBBLESTONE_SLAB_B1_7, SANDSTONE_SLAB_B1_3, SANDSTONE_SLAB_1_2_4, BRICK_SLAB_C0_26ST, BRICK_SLAB_B1_8,
                            STONE_BRICK_SLAB_B1_8, RESIN_BRICK_SLAB);
            getOrCreateTagBuilder(BlockTags.STAIRS)
                    .add(COBBLESTONE_STAIRS_RD20090515, COBBLESTONE_STAIRS_INF20100629, COBBLESTONE_STAIRS_B1_7, BRICK_STAIRS_C0_26ST, BRICK_STAIRS_B1_8, STONE_BRICK_STAIRS_B1_8,
                            NETHER_BRICK_STAIRS_B1_9PRE, SANDSTONE_STAIRS_B1_2, SANDSTONE_STAIRS_1_3, QUARTZ_STAIRS_1_5, RED_SANDSTONE_STAIRS_1_8, PURPUR_STAIRS_1_9, PRISMARINE_STAIRS_1_13,
                            RESIN_BRICK_STAIRS);
            getOrCreateTagBuilder(BlockTags.WITHER_IMMUNE)
                    .add(BEDROCK_C0_0_12A);
            getOrCreateTagBuilder(BlockTags.WOODEN_BUTTONS)
                    .add(PALM_BUTTON, BANANA_BUTTON, CORN_BUTTON, POISONED_BUTTON, MAHOGANY_BUTTON, PALE_OAK_BUTTON, WOODEN_BUTTON_RD20090515, WOODEN_BUTTON_RD161348, WOODEN_BUTTON_C0_0_14A,
                            WOODEN_BUTTON_C0_0_15A, WOODEN_BUTTON_1_4, BIRCH_BUTTON_1_13, SPRUCE_BUTTON_1_13, JUNGLE_BUTTON_1_13, ACACIA_BUTTON_1_13, DARK_OAK_BUTTON_1_13);
            getOrCreateTagBuilder(BlockTags.WOODEN_DOORS)
                    .add(PALM_DOOR, BANANA_DOOR, CORN_DOOR, POISONED_DOOR, MAHOGANY_DOOR, PALE_OAK_DOOR, WOODEN_DOOR_INF20100607);
            getOrCreateTagBuilder(BlockTags.WOODEN_FENCES)
                    .add(PALM_FENCE, BANANA_FENCE, CORN_FENCE, POISONED_FENCE, MAHOGANY_FENCE, PALE_OAK_FENCE, WOODEN_FENCE_RD20090515, WOODEN_FENCE_RD161348, WOODEN_FENCE_C0_0_14A, WOODEN_FENCE_A1_0_17,
                            WOODEN_FENCE_B1_9PRE5, BIRCH_FENCE_1_8, SPRUCE_FENCE_1_8, JUNGLE_FENCE_1_8, ACACIA_FENCE_1_8, DARK_OAK_FENCE_1_8);
            getOrCreateTagBuilder(BlockTags.WOODEN_PRESSURE_PLATES)
                    .add(PALM_PRESSURE_PLATE, BANANA_PRESSURE_PLATE, CORN_PRESSURE_PLATE, POISONED_PRESSURE_PLATE, MAHOGANY_PRESSURE_PLATE, PALE_OAK_PRESSURE_PLATE,
                            BIRCH_PRESSURE_PLATE_1_13, SPRUCE_PRESSURE_PLATE_1_13, JUNGLE_PRESSURE_PLATE_1_13, ACACIA_PRESSURE_PLATE_1_13, DARK_OAK_PRESSURE_PLATE_1_13);
            getOrCreateTagBuilder(BlockTags.WOODEN_SLABS)
                    .add(PALM_SLAB, BANANA_SLAB, CORN_SLAB, POISONED_SLAB, MAHOGANY_SLAB, PALE_OAK_SLAB, WOODEN_SLAB_RD20090515, WOODEN_SLAB_RD161348, WOODEN_SLAB_C0_0_14A, WOODEN_SLAB_B1_3, WOODEN_SLAB_B1_9PRE5,
                            BIRCH_SLAB_1_3, SPRUCE_SLAB_1_3, JUNGLE_SLAB_1_3, ACACIA_SLAB_1_7, DARK_OAK_SLAB_1_7);
            getOrCreateTagBuilder(BlockTags.WOODEN_STAIRS)
                    .add(PALM_STAIRS, BANANA_STAIRS, CORN_STAIRS, POISONED_STAIRS, MAHOGANY_STAIRS, PALE_OAK_STAIRS, WOODEN_STAIRS_RD20090515, WOODEN_STAIRS_RD161348, WOODEN_STAIRS_C0_0_14A,
                            WOODEN_STAIRS_INF20100629, WOODEN_STAIRS_B1_9PRE5, BIRCH_STAIRS_1_3, SPRUCE_STAIRS_1_3, JUNGLE_STAIRS_1_3, ACACIA_STAIRS_1_7, DARK_OAK_STAIRS_1_7);
            getOrCreateTagBuilder(BlockTags.WOODEN_TRAPDOORS)
                    .add(PALM_TRAPDOOR, BANANA_TRAPDOOR, CORN_TRAPDOOR, POISONED_TRAPDOOR, MAHOGANY_TRAPDOOR, PALE_OAK_TRAPDOOR, TRAPDOOR_B1_6);
            getOrCreateTagBuilder(BlockTags.WALLS)
                    .add(COBBLESTONE_WALL_RD20090515, COBBLESTONE_WALL_C0_0_14A, COBBLESTONE_WALL_1_4, RESIN_BRICK_WALL);
            getOrCreateTagBuilder(BlockTags.WOOL)
                    .add(WHITE_CLOTH, LIGHT_GRAY_CLOTH_C0_0_20A, LIGHT_GRAY_CLOTH_C0_28A, DARK_GRAY_CLOTH_C0_0_20A, DARK_GRAY_CLOTH_C0_28A, RED_CLOTH, ORANGE_CLOTH, YELLOW_CLOTH, CHARTREUSE_CLOTH,
                            SPRING_GREEN_CLOTH, CYAN_CLOTH, CAPRI_CLOTH, ULTRAMARINE_CLOTH, VIOLET_CLOTH, PURPLE_CLOTH, MAGENTA_CLOTH, ROSE_CLOTH, LIGHT_GRAY_WOOL_B1_2,
                            GRAY_WOOL_B1_2, BLACK_WOOL_B1_2, BROWN_WOOL_B1_2, RED_WOOL_B1_2, ORANGE_WOOL_B1_2, YELLOW_WOOL_B1_2, LIME_WOOL_B1_2 , GREEN_WOOL_B1_2, CYAN_WOOL_B1_2 , LIGHT_BLUE_WOOL_B1_2,
                            BLUE_WOOL_B1_2 , PURPLE_WOOL_B1_2, MAGENTA_WOOL_B1_2, PINK_WOOL_B1_2, LIGHT_GRAY_WOOL_1_2_4, GRAY_WOOL_1_2_4, BLACK_WOOL_1_2_4, BROWN_WOOL_1_2_4, RED_WOOL_1_2_4,
                            ORANGE_WOOL_1_2_4, YELLOW_WOOL_1_2_4, LIME_WOOL_1_2_4, GREEN_WOOL_1_2_4, CYAN_WOOL_1_2_4, LIGHT_BLUE_WOOL_1_2_4, BLUE_WOOL_1_2_4, PURPLE_WOOL_1_2_4,
                            MAGENTA_WOOL_1_2_4, PINK_WOOL_1_2_4);
            getOrCreateTagBuilder(BlockTags.WOOL_CARPETS)
                    .add(WHITE_CLOTH_CARPET,
                            LIGHT_GRAY_CLOTH_CARPET_C0_0_20A, LIGHT_GRAY_CLOTH_CARPET_C0_28A, DARK_GRAY_CLOTH_CARPET_C0_0_20A, DARK_GRAY_CLOTH_CARPET_C0_28A, RED_CLOTH_CARPET, ORANGE_CLOTH_CARPET,
                            YELLOW_CLOTH_CARPET, CHARTREUSE_CLOTH_CARPET, SPRING_GREEN_CLOTH_CARPET, CYAN_CLOTH_CARPET, CAPRI_CLOTH_CARPET, ULTRAMARINE_CLOTH_CARPET, VIOLET_CLOTH_CARPET,
                            PURPLE_CLOTH_CARPET, MAGENTA_CLOTH_CARPET, ROSE_CLOTH_CARPET, GRAY_CARPET_B1_2, BLACK_CARPET_B1_2, BROWN_CARPET_B1_2, RED_CARPET_B1_2, ORANGE_CARPET_B1_2,
                            YELLOW_CARPET_B1_2, LIME_CARPET_B1_2, GREEN_CARPET_B1_2, CYAN_CARPET_B1_2, LIGHT_BLUE_CARPET_B1_2, BLUE_CARPET_B1_2, PURPLE_CARPET_B1_2,
                            MAGENTA_CARPET_B1_2, PINK_CARPET_B1_2, LIGHT_GRAY_CARPET_1_2_4, GRAY_CARPET_1_2_4, BLACK_CARPET_1_2_4, BROWN_CARPET_1_2_4,
                            RED_CARPET_1_2_4, ORANGE_CARPET_1_2_4, YELLOW_CARPET_1_2_4, LIME_CARPET_1_2_4, GREEN_CARPET_1_2_4, CYAN_CARPET_1_2_4, LIGHT_BLUE_CARPET_1_2_4,
                            BLUE_CARPET_1_2_4, PURPLE_CARPET_1_2_4, MAGENTA_CARPET_1_2_4, PINK_CARPET_1_2_4);
            getOrCreateTagBuilder(BlockTags.ENCHANTMENT_POWER_PROVIDER)
                    .add(BOOKSHELF_C0_26ST, BOOKSHELF_B1_9PRE5);
            getOrCreateTagBuilder(BlockTags.CLIMBABLE)
                    .add(LADDER_INF20100607, LADDER_INF20100618, VINES_B1_8);
            getOrCreateTagBuilder(BlockTags.SMALL_FLOWERS)
                    .add(GLOW_FLOWER, SHRUB_B1_6, ALLIUM_1_7, AZURE_BLUET_1_7, BLUE_ORCHID_1_7, LILAC_1_7, PEONY_1_7, ROSE_BUSH_1_7, SUNFLOWER_1_7, OXEYE_DAISY_1_7,
                            RED_TULIP_1_7, ORANGE_TULIP_1_7, WHITE_TULIP_1_7, PINK_TULIP_1_7);
            getOrCreateTagBuilder(ModTags.Blocks.CLASSIC_SPONGE_REPLACEABLE)
                    .add(Blocks.KELP, KELP_PLANT, Blocks.SEAGRASS, TALL_SEAGRASS, POWDER_SNOW);
            getOrCreateTagBuilder(ModTags.Blocks.OAK_CHAIRS)
                    .add(OAK_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.BIRCH_CHAIRS)
                    .add(BIRCH_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.SPRUCE_CHAIRS)
                    .add(SPRUCE_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.JUNGLE_CHAIRS)
                    .add(JUNGLE_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.ACACIA_CHAIRS)
                    .add(ACACIA_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.DARK_OAK_CHAIRS)
                    .add(DARK_OAK_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.CRIMSON_CHAIRS)
                    .add(CRIMSON_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.WARPED_CHAIRS)
                    .add(WARPED_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.MANGROVE_CHAIRS)
                    .add(MANGROVE_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.BAMBOO_CHAIRS)
                    .add(BAMBOO_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.CHERRY_CHAIRS)
                    .add(CHERRY_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.PALM_CHAIRS)
                    .add(PALM_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.BANANA_CHAIRS)
                    .add(BANANA_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.CORN_CHAIRS)
                    .add(CORN_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.POISONED_CHAIRS)
                    .add(POISONED_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.MAHOGANY_CHAIRS)
                    .add(MAHOGANY_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.PALE_OAK_CHAIRS)
                    .add(PALE_OAK_CHAIR);
            getOrCreateTagBuilder(ModTags.Blocks.CHAIRS)
                    .addTag(ModTags.Blocks.OAK_CHAIRS)
                    .addTag(ModTags.Blocks.SPRUCE_CHAIRS)
                    .addTag(ModTags.Blocks.BIRCH_CHAIRS)
                    .addTag(ModTags.Blocks.JUNGLE_CHAIRS)
                    .addTag(ModTags.Blocks.ACACIA_CHAIRS)
                    .addTag(ModTags.Blocks.DARK_OAK_CHAIRS)
                    .addTag(ModTags.Blocks.CRIMSON_CHAIRS)
                    .addTag(ModTags.Blocks.WARPED_CHAIRS)
                    .addTag(ModTags.Blocks.MANGROVE_CHAIRS)
                    .addTag(ModTags.Blocks.BAMBOO_CHAIRS)
                    .addTag(ModTags.Blocks.CHERRY_CHAIRS)
                    .addTag(ModTags.Blocks.PALM_CHAIRS)
                    .addTag(ModTags.Blocks.BANANA_CHAIRS)
                    .addTag(ModTags.Blocks.CORN_CHAIRS)
                    .addTag(ModTags.Blocks.POISONED_CHAIRS)
                    .addTag(ModTags.Blocks.MAHOGANY_CHAIRS)
                    .addTag(ModTags.Blocks.PALE_OAK_CHAIRS);
            getOrCreateTagBuilder(BlockTags.MAINTAINS_FARMLAND)
                    .add(BANANA_CROP);
            getOrCreateTagBuilder(BlockTags.DIRT)
                    .add(SANDY_DIRT, TROPICAL_MOSS);
            getOrCreateTagBuilder(BlockTags.RAILS)
                    .add(RAIL_INF20100618, POWERED_RAIL_B1_5, DETECTOR_RAIL_B1_5, ACTIVATOR_RAIL_1_5);

            getOrCreateTagBuilder(ModTags.Blocks.COCOA_BEANS_PLACEABLE)
                    .addTag(ModTags.Blocks.BANANA_LOGS)
                    .addTag(ModTags.Blocks.CORN_LOGS)
                    .addTag(ModTags.Blocks.POISONED_LOGS)
                    .addTag(ModTags.Blocks.MAHOGANY_LOGS);


            getOrCreateTagBuilder(ConventionalBlockTags.COAL_ORES)
                    .add(COAL_ORE_C0_0_14A, COAL_ORE_1_14);
            getOrCreateTagBuilder(ConventionalBlockTags.IRON_ORES)
                    .add(IRON_ORE_C0_0_14A, IRON_ORE_1_14, IRON_ORE_1_14_1);
            getOrCreateTagBuilder(ConventionalBlockTags.GOLD_ORES)
                    .add(GOLD_ORE_C0_0_14A, GOLD_ORE_C0_26ST, GOLD_ORE_1_14);
            getOrCreateTagBuilder(ConventionalBlockTags.DIAMOND_ORES)
                    .add(DIAMOND_ORE_IN20100128, DIAMOND_ORE_1_14);
            getOrCreateTagBuilder(ConventionalBlockTags.LAPIS_ORES)
                    .add(LAPIS_ORE_B1_2, LAPIS_ORE_1_14);
            getOrCreateTagBuilder(ConventionalBlockTags.EMERALD_ORES)
                    .add(RUBY_ORE, EMERALD_ORE_1_3, EMERALD_ORE_1_14);
            getOrCreateTagBuilder(ConventionalBlockTags.QUARTZ_ORES)
                    .add(QUARTZ_ORE_1_5);
        }
    }

    public static class BlocktopiaItemTagProvider extends FabricTagProvider.ItemTagProvider {
        public BlocktopiaItemTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
            super(output, completableFuture);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
            getOrCreateTagBuilder(ConventionalItemTags.BUCKETS)
                    .add(TROPICAL_WATER_BUCKET);
            getOrCreateTagBuilder(ItemTags.PIGLIN_LOVED)
                    .add(NETHERITE_INGOT, Items.NETHERITE_BLOCK);
            getOrCreateTagBuilder(ItemTags.EQUIPPABLE_ENCHANTABLE)
                    .add(asItem(CARVED_PUMPKIN_A1_2_0));
            getOrCreateTagBuilder(ItemTags.VANISHING_ENCHANTABLE)
                    .add(asItem(CARVED_PUMPKIN_A1_2_0));
            getOrCreateTagBuilder(ModTags.Items.LEGACY_BLOCKS)
                    .add(asItem(COBBLESTONE_RD20090515, COBBLESTONE_C0_0_14A, COBBLESTONE_B1_7, WOODEN_PLANKS_RD20090515, WOODEN_PLANKS_RD161348,
                            WOODEN_PLANKS_C0_0_14A, WOODEN_PLANKS_C0_0_15A, WOODEN_PLANKS_B1_9PRE5, SAPLING_RD161348, SAPLING_C0_0_13A,
                            SAPLING_C0_24ST, BEDROCK_C0_0_12A, SAND_C0_0_14A, SAND_C0_0_15A, SAND_B1_9PRE6, GRAVEL_C0_0_14A,
                            GRAVEL_C0_0_15A, GRAVEL_B1_9PRE5, GRAVEL_1_3, COAL_ORE_C0_0_14A, COAL_ORE_1_14, IRON_ORE_C0_0_14A,
                            IRON_ORE_1_14, IRON_ORE_1_14_1, GOLD_ORE_C0_0_14A, GOLD_ORE_C0_26ST, GOLD_ORE_1_14, LOG_C0_0_14A,
                            LEAVES_C0_0_14A, LEAVES_C0_0_15A, LEAVES_C0_24ST, SPONGE_C0_0_19A, SPONGE_1_8, WET_SPONGE_1_8,
                            GLASS_C0_0_19A, WHITE_CLOTH, LIGHT_GRAY_CLOTH_C0_0_20A, LIGHT_GRAY_CLOTH_C0_28A, DARK_GRAY_CLOTH_C0_0_20A,
                            DARK_GRAY_CLOTH_C0_28A, RED_CLOTH, ORANGE_CLOTH, YELLOW_CLOTH, CHARTREUSE_CLOTH, SPRING_GREEN_CLOTH,
                            CYAN_CLOTH, CAPRI_CLOTH, ULTRAMARINE_CLOTH, VIOLET_CLOTH, PURPLE_CLOTH, MAGENTA_CLOTH, ROSE_CLOTH,
                            GOLD_BLOCK_C0_0_20A, GOLD_BLOCK_C0_26ST, GOLD_BLOCK_A1_2_0, GOLD_BLOCK_B1_9PRE5, DANDELION_C0_0_20A, ROSE_C0_0_20A,
                            POPPY_1_7, RED_MUSHROOM_C0_0_20A, BROWN_MUSHROOM_C0_0_20A, STONE_SLAB_C0_26ST, IRON_BLOCK_C0_26ST, IRON_BLOCK_A1_2_0,
                            IRON_BLOCK_B1_9PRE5, TNT_C0_26ST, TNT_C0_28A, MOSSY_COBBLESTONE_C0_26ST, MOSSY_COBBLESTONE_B1_8, BRICKS_C0_26ST,
                            BRICKS_A1_0_11, BOOKSHELF_C0_26ST, BOOKSHELF_B1_9PRE5, OBSIDIAN_C0_28A, TORCH_IN20100124_2, DIAMOND_ORE_IN20100128,
                            DIAMOND_ORE_1_14, DIAMOND_BLOCK_IN20100128, DIAMOND_BLOCK_A1_2_0, DIAMOND_BLOCK_B1_9PRE5, CRAFTING_TABLE_IN20100131,
                            CRAFTING_TABLE_1_14, FURNACE_IN20100219, FURNACE_B1_2, LADDER_INF20100607,
                            LADDER_INF20100618, WOODEN_DOOR_INF20100607, WOODEN_STAIRS_RD20090515, WOODEN_STAIRS_RD161348,
                            WOODEN_STAIRS_C0_0_14A, WOODEN_STAIRS_INF20100629, WOODEN_STAIRS_B1_9PRE5, COBBLESTONE_STAIRS_RD20090515,
                            COBBLESTONE_STAIRS_INF20100629, COBBLESTONE_B1_7, REDSTONE_ORE_A1_0_1, REDSTONE_ORE_1_14, REDSTONE_TORCH_A1_0_1,
                            REDSTONE_WALL_TORCH_A1_0_1, SNOW_A1_0_4, ICE_A1_0_4, SNOW_BLOCK_A1_0_5, CLAY_BLOCK_A1_0_11, WOODEN_FENCE_RD20090515,
                            WOODEN_FENCE_RD161348, WOODEN_FENCE_C0_0_14A, WOODEN_FENCE_A1_0_17, WOODEN_FENCE_B1_9PRE5, NETHERRACK_A1_2_0,
                            NETHERRACK_B1_9PRE5, SOUL_SAND_A1_2_0, GLOWSTONE_A1_2_0, GLOWSTONE_B1_9PRE5, CARVED_PUMPKIN_A1_2_0,
                            JACK_O_LANTERN_A1_2_0, LIGHT_GRAY_WOOL_B1_2, GRAY_WOOL_B1_2, BLACK_WOOL_B1_2, BROWN_WOOL_B1_2, RED_WOOL_B1_2, ORANGE_WOOL_B1_2,
                            YELLOW_WOOL_B1_2, LIME_WOOL_B1_2 , GREEN_WOOL_B1_2, CYAN_WOOL_B1_2 , LIGHT_BLUE_WOOL_B1_2, BLUE_WOOL_B1_2 , PURPLE_WOOL_B1_2, MAGENTA_WOOL_B1_2, PINK_WOOL_B1_2,
                            LIGHT_GRAY_WOOL_1_2_4, GRAY_WOOL_1_2_4, BLACK_WOOL_1_2_4, BROWN_WOOL_1_2_4, RED_WOOL_1_2_4, ORANGE_WOOL_1_2_4, YELLOW_WOOL_1_2_4, LIME_WOOL_1_2_4,
                            GREEN_WOOL_1_2_4, CYAN_WOOL_1_2_4, LIGHT_BLUE_WOOL_1_2_4, BLUE_WOOL_1_2_4, PURPLE_WOOL_1_2_4, MAGENTA_WOOL_1_2_4, PINK_WOOL_1_2_4, LAPIS_ORE_B1_2, LAPIS_ORE_1_14,
                            LAPIS_BLOCK_B1_2, LAPIS_BLOCK_1_6, NOTE_BLOCK_B1_2, SANDSTONE_B1_2, SANDSTONE_1_2_4, BIRCH_LOG_B1_2, BIRCH_LOG_1_7, BIRCH_LEAVES_B1_2, SPRUCE_LOG_B1_2, SPRUCE_LOG_1_7,
                            SPRUCE_LEAVES_B1_2, CRYING_OBSIDIAN_B1_3, COBBLESTONE_SLAB_RD20090515, COBBLESTONE_SLAB_B1_3, COBBLESTONE_SLAB_B1_7,
                            WOODEN_SLAB_RD20090515, WOODEN_SLAB_RD161348, WOODEN_SLAB_C0_0_14A, WOODEN_SLAB_B1_3, WOODEN_SLAB_B1_9PRE5, SANDSTONE_SLAB_B1_3, SANDSTONE_SLAB_1_2_4,
                            SMOOTH_STONE_B1_3, BIRCH_SAPLING_B1_5, SPRUCE_SAPLING_B1_5, POWERED_RAIL_B1_5, DETECTOR_RAIL_B1_5, COBWEB_B1_5, DEAD_BUSH_B1_6, SHRUB_B1_6, SHORT_GRASS_B1_6, FERN_B1_6,
                            TRAPDOOR_B1_6, STONE_BRICKS_B1_8, CRACKED_STONE_BRICKS_B1_8, MOSSY_STONE_BRICKS_B1_8, INFESTED_COBBLESTONE_RD20090515, INFESTED_COBBLESTONE_C0_0_14A,
                            INFESTED_COBBLESTONE_B1_8, INFESTED_STONE_BRICKS_B1_8, BRICK_SLAB_C0_26ST, BRICK_SLAB_B1_8, STONE_BRICK_SLAB_B1_8, BRICK_STAIRS_C0_26ST, BRICK_STAIRS_B1_8,
                            STONE_BRICK_STAIRS_B1_8, GLASS_PANE_B1_8, WOODEN_FENCE_GATE_RD20090515, WOODEN_FENCE_GATE_RD161348, WOODEN_FENCE_GATE_C0_0_14A, WOODEN_FENCE_GATE_B1_8,
                            WOODEN_FENCE_GATE_B1_9PRE5, VINES_B1_8, MUSHROOM_STEM_B1_8, RED_MUSHROOM_BLOCK_B1_8, BROWN_MUSHROOM_BLOCK_B1_8, MELON_BLOCK_B1_8, NETHER_BRICKS_B1_9PRE,
                            NETHER_BRICK_STAIRS_B1_9PRE, NETHER_BRICK_FENCE_B1_9PRE, LILY_PAD_B1_9PRE, ENDSTONE_B1_9PRE4, JUNGLE_LOG_1_2, JUNGLE_LOG_1_7, JUNGLE_LEAVES_1_2, JUNGLE_SAPLING_1_2,
                            REDSTONE_LAMP_1_2, CHISELED_STONE_BRICKS_1_2, BIRCH_PLANKS_1_2_4, SPRUCE_PLANKS_1_2_4, JUNGLE_PLANKS_1_2_4, CUT_SANDSTONE_1_2_4, CHISELED_SANDSTONE_1_2_4,
                            BIRCH_SLAB_1_3, SPRUCE_SLAB_1_3, JUNGLE_SLAB_1_3, COCOA_1_3, RUBY_ORE, EMERALD_ORE_1_3, EMERALD_ORE_1_14, SANDSTONE_STAIRS_B1_2, SANDSTONE_STAIRS_1_3, EMERALD_BLOCK_1_3,
                            BIRCH_STAIRS_1_3, SPRUCE_STAIRS_1_3, JUNGLE_STAIRS_1_3, OAK_WOOD_1_3, BIRCH_WOOD_1_3, SPRUCE_WOOD_1_3, JUNGLE_WOOD_1_3, WOODEN_BUTTON_RD20090515, WOODEN_BUTTON_RD161348,
                            WOODEN_BUTTON_C0_0_14A, WOODEN_BUTTON_C0_0_15A, WOODEN_BUTTON_1_4, COBBLESTONE_WALL_RD20090515, COBBLESTONE_WALL_C0_0_14A, COBBLESTONE_WALL_1_4, NETHER_BRICK_SLAB_1_4_6,
                            QUARTZ_ORE_1_5, REDSTONE_BLOCK_1_5, ACTIVATOR_RAIL_1_5, QUARTZ_BLOCK_1_5, CHISELED_QUARTZ_BLOCK_1_5, QUARTZ_PILLAR_1_5, QUARTZ_SLAB_1_5, QUARTZ_STAIRS_1_5,
                            SMOOTH_SANDSTONE_1_5, SMOOTH_QUARTZ_1_5, LIGHT_GRAY_CLOTH_CARPET_C0_0_20A, LIGHT_GRAY_CLOTH_CARPET_C0_28A, DARK_GRAY_CLOTH_CARPET_C0_0_20A, DARK_GRAY_CLOTH_CARPET_C0_28A,
                            RED_CLOTH_CARPET, ORANGE_CLOTH_CARPET, YELLOW_CLOTH_CARPET, CHARTREUSE_CLOTH_CARPET, SPRING_GREEN_CLOTH_CARPET, CYAN_CLOTH_CARPET, CAPRI_CLOTH_CARPET, ULTRAMARINE_CLOTH_CARPET,
                            VIOLET_CLOTH_CARPET, PURPLE_CLOTH_CARPET, MAGENTA_CLOTH_CARPET, ROSE_CLOTH_CARPET, GRAY_CARPET_B1_2, BLACK_CARPET_B1_2, BROWN_CARPET_B1_2, RED_CARPET_B1_2,
                            ORANGE_CARPET_B1_2, YELLOW_CARPET_B1_2, LIME_CARPET_B1_2, GREEN_CARPET_B1_2, CYAN_CARPET_B1_2, LIGHT_BLUE_CARPET_B1_2, BLUE_CARPET_B1_2, PURPLE_CARPET_B1_2,
                            MAGENTA_CARPET_B1_2, PINK_CARPET_B1_2, LIGHT_GRAY_CARPET_1_2_4, GRAY_CARPET_1_2_4, BLACK_CARPET_1_2_4, BROWN_CARPET_1_2_4,
                            RED_CARPET_1_2_4, ORANGE_CARPET_1_2_4, YELLOW_CARPET_1_2_4, LIME_CARPET_1_2_4, GREEN_CARPET_1_2_4, CYAN_CARPET_1_2_4, LIGHT_BLUE_CARPET_1_2_4,
                            BLUE_CARPET_1_2_4, PURPLE_CARPET_1_2_4, MAGENTA_CARPET_1_2_4, PINK_CARPET_1_2_4, HAY_BALE_1_6, TERRACOTTA_1_6, COAL_BLOCK_1_6,
                            ALLIUM_1_7, AZURE_BLUET_1_7, BLUE_ORCHID_1_7, LILAC_1_7, PEONY_1_7, ROSE_BUSH_1_7, SUNFLOWER_1_7, OXEYE_DAISY_1_7,
                            RED_TULIP_1_7, ORANGE_TULIP_1_7, WHITE_TULIP_1_7, PINK_TULIP_1_7, LARGE_FERN_1_7, TALL_GRASS_1_7, PACKED_ICE_1_7, INFESTED_CRACKED_STONE_BRICKS_1_7,
                            INFESTED_MOSSY_STONE_BRICKS_1_7, INFESTED_CHISELED_STONE_BRICKS_1_7, RED_SAND_1_7, WHITE_STAINED_GLASS_1_7, ORANGE_STAINED_GLASS_1_7,
                            MAGENTA_STAINED_GLASS_1_7, LIGHT_BLUE_STAINED_GLASS_1_7, YELLOW_STAINED_GLASS_1_7, LIME_STAINED_GLASS_1_7, PINK_STAINED_GLASS_1_7,
                            GRAY_STAINED_GLASS_1_7, LIGHT_GRAY_STAINED_GLASS_1_7, CYAN_STAINED_GLASS_1_7, PURPLE_STAINED_GLASS_1_7, BLUE_STAINED_GLASS_1_7, BROWN_STAINED_GLASS_1_7,
                            GREEN_STAINED_GLASS_1_7, RED_STAINED_GLASS_1_7, BLACK_STAINED_GLASS_1_7, WHITE_STAINED_GLASS_PANE_1_7, ORANGE_STAINED_GLASS_PANE_1_7, MAGENTA_STAINED_GLASS_PANE_1_7,
                            LIGHT_BLUE_STAINED_GLASS_PANE_1_7, YELLOW_STAINED_GLASS_PANE_1_7, LIME_STAINED_GLASS_PANE_1_7, PINK_STAINED_GLASS_PANE_1_7, GRAY_STAINED_GLASS_PANE_1_7,
                            LIGHT_GRAY_STAINED_GLASS_PANE_1_7, CYAN_STAINED_GLASS_PANE_1_7, PURPLE_STAINED_GLASS_PANE_1_7, BLUE_STAINED_GLASS_PANE_1_7, BROWN_STAINED_GLASS_PANE_1_7,
                            GREEN_STAINED_GLASS_PANE_1_7, RED_STAINED_GLASS_PANE_1_7, BLACK_STAINED_GLASS_PANE_1_7, ACACIA_LOG_1_7, ACACIA_WOOD_1_7, ACACIA_LEAVES_1_7,
                            ACACIA_SAPLING_1_7, DARK_OAK_LOG_1_7, DARK_OAK_WOOD_1_7, DARK_OAK_LEAVES_1_7, DARK_OAK_SAPLING_1_7, ACACIA_PLANKS_1_7, ACACIA_STAIRS_1_7, ACACIA_SLAB_1_7, DARK_OAK_PLANKS_1_7,
                            DARK_OAK_STAIRS_1_7, DARK_OAK_SLAB_1_7, GRANITE_1_8, POLISHED_GRANITE_1_8, DIORITE_1_8, POLISHED_DIORITE_1_8, ANDESITE_1_8, POLISHED_ANDESITE_1_8, SLIME_BLOCK_1_8,
                            PRISMARINE_1_8, PRISMARINE_BRICKS_1_8, DARK_PRISMARINE_1_8, RED_SANDSTONE_1_8, CUT_RED_SANDSTONE_1_8, CHISELED_RED_SANDSTONE_1_8, SMOOTH_RED_SANDSTONE_1_8,
                            RED_SANDSTONE_SLAB_1_8, RED_SANDSTONE_STAIRS_1_8, BIRCH_FENCE_1_8, SPRUCE_FENCE_1_8, JUNGLE_FENCE_1_8, ACACIA_FENCE_1_8, DARK_OAK_FENCE_1_8, END_ROD_1_9,
                            ENDSTONE_BRICKS_1_9, PURPUR_BLOCK_1_9, PURPUR_PILLAR_1_9, PURPUR_SLAB_1_9, PURPUR_STAIRS_1_9, BONE_BLOCK_1_10, MAGMA_BLOCK_1_10,
                            NETHER_WART_BLOCK_1_10, NETHER_WART_BLOCK_1_14, RED_NETHER_BRICKS_1_10, BIRCH_BUTTON_1_13, SPRUCE_BUTTON_1_13, JUNGLE_BUTTON_1_13, ACACIA_BUTTON_1_13, DARK_OAK_BUTTON_1_13,
                            BIRCH_PRESSURE_PLATE_1_13, SPRUCE_PRESSURE_PLATE_1_13, JUNGLE_PRESSURE_PLATE_1_13, ACACIA_PRESSURE_PLATE_1_13, DARK_OAK_PRESSURE_PLATE_1_13, PRISMARINE_SLAB_1_13,
                            PRISMARINE_STAIRS_1_13));
            getOrCreateTagBuilder(ModTags.Items.PALM_LOGS)
                    .add(asItem(PALM_LOG, STRIPPED_PALM_LOG, PALM_WOOD, STRIPPED_PALM_WOOD));
            getOrCreateTagBuilder(ModTags.Items.LEGACY_COBBLESTONE)
                    .add(asItem(COBBLESTONE_RD20090515, COBBLESTONE_C0_0_14A, COBBLESTONE_B1_7));
            getOrCreateTagBuilder(ModTags.Items.BANANA_LOGS)
                    .add(asItem(BANANA_LOG, STRIPPED_BANANA_LOG, BANANA_WOOD, STRIPPED_BANANA_WOOD));
            getOrCreateTagBuilder(ModTags.Items.CORN_LOGS)
                    .add(asItem(CORN_LOG, STRIPPED_CORN_LOG, CORN_WOOD, STRIPPED_CORN_WOOD));
            getOrCreateTagBuilder(ModTags.Items.POISONED_LOGS)
                    .add(asItem(POISONED_LOG, STRIPPED_POISONED_LOG, POISONED_WOOD, STRIPPED_POISONED_WOOD));
            getOrCreateTagBuilder(ModTags.Items.MAHOGANY_LOGS)
                    .add(asItem(MAHOGANY_LOG, STRIPPED_MAHOGANY_LOG, MAHOGANY_WOOD, STRIPPED_MAHOGANY_WOOD));
            getOrCreateTagBuilder(ModTags.Items.PALE_OAK_LOGS)
                    .add(asItem(PALE_OAK_LOG, STRIPPED_PALE_OAK_LOG, PALE_OAK_WOOD, STRIPPED_PALE_OAK_WOOD));
            getOrCreateTagBuilder(ItemTags.FENCES)
                    .add(asItem(PALM_FENCE, BANANA_FENCE, CORN_FENCE, POISONED_FENCE, MAHOGANY_FENCE, PALE_OAK_FENCE, WOODEN_FENCE_RD161348, WOODEN_FENCE_C0_0_14A, WOODEN_FENCE_A1_0_17, WOODEN_FENCE_B1_9PRE5,
                            NETHER_BRICK_FENCE_B1_9PRE));
            getOrCreateTagBuilder(ItemTags.BOATS)
                    .add(ModItems.PALM_BOAT, BANANA_BOAT, CORN_BOAT, POISONED_BOAT, MAHOGANY_BOAT, PALE_OAK_BOAT);
            getOrCreateTagBuilder(ItemTags.CHEST_BOATS)
                    .add(ModItems.PALM_CHEST_BOAT, BANANA_CHEST_BOAT, CORN_CHEST_BOAT, POISONED_CHEST_BOAT, MAHOGANY_CHEST_BOAT, PALE_OAK_CHEST_BOAT);
            getOrCreateTagBuilder(ItemTags.LEAVES)
                    .add(asItem(PALM_LEAVES, BANANA_LEAVES, CORN_LEAVES, POISONED_LEAVES, MAHOGANY_LEAVES, PALE_OAK_LEAVES, FLOWERING_CHERRY_LEAVES, LEAVES_C0_0_14A, LEAVES_C0_0_15A, LEAVES_C0_24ST,
                            BIRCH_LEAVES_B1_2, SPRUCE_LEAVES_B1_2, JUNGLE_LEAVES_1_2, ACACIA_LEAVES_1_7, DARK_OAK_LEAVES_1_7));
            getOrCreateTagBuilder(ItemTags.LOGS_THAT_BURN)
                    .addTag(ModTags.Items.PALM_LOGS).addTag(ModTags.Items.BANANA_LOGS).addTag(ModTags.Items.CORN_LOGS).addTag(ModTags.Items.POISONED_LOGS)
                    .addTag(ModTags.Items.MAHOGANY_LOGS).addTag(ModTags.Items.PALE_OAK_LOGS)
                    .add(asItem(LOG_C0_0_14A, BIRCH_LOG_B1_2, BIRCH_LOG_1_7, SPRUCE_LOG_B1_2, SPRUCE_LOG_1_7, JUNGLE_LOG_1_2, JUNGLE_LOG_1_7, OAK_WOOD_1_3, BIRCH_WOOD_1_3,
                            SPRUCE_WOOD_1_3, JUNGLE_WOOD_1_3, ACACIA_LOG_1_7, ACACIA_WOOD_1_7, DARK_OAK_LOG_1_7, DARK_OAK_WOOD_1_7));
            getOrCreateTagBuilder(ItemTags.PLANKS)
                    .add(asItem(PALM_PLANKS, BANANA_PLANKS, CORN_PLANKS, POISONED_PLANKS, MAHOGANY_PLANKS, PALE_OAK_PLANKS, WOODEN_PLANKS_RD20090515, WOODEN_PLANKS_RD161348, WOODEN_PLANKS_C0_0_14A,
                            WOODEN_PLANKS_C0_0_15A, WOODEN_PLANKS_B1_9PRE5, BIRCH_PLANKS_1_2_4, SPRUCE_PLANKS_1_2_4, JUNGLE_PLANKS_1_2_4, ACACIA_PLANKS_1_7, DARK_OAK_PLANKS_1_7));
            getOrCreateTagBuilder(ItemTags.SAPLINGS)
                    .add(asItem(PALM_SAPLING, BANANA_SAPLING, CORN_SAPLING, POISONED_SAPLING, MAHOGANY_SAPLING, PALE_OAK_SAPLING, FLOWERING_CHERRY_SAPLING, SAPLING_RD161348, SAPLING_C0_0_13A, SAPLING_C0_24ST,
                            BIRCH_SAPLING_B1_5, SPRUCE_SAPLING_B1_5, JUNGLE_SAPLING_1_2, ACACIA_SAPLING_1_7, DARK_OAK_SAPLING_1_7));
            getOrCreateTagBuilder(ItemTags.SLABS)
                    .add(asItem(STONE_SLAB_C0_26ST, NETHER_BRICK_SLAB_1_4_6, QUARTZ_SLAB_1_5, PRISMARINE_SLAB_1_13,
                            COBBLESTONE_SLAB_RD20090515, COBBLESTONE_SLAB_B1_3, COBBLESTONE_SLAB_B1_7, SANDSTONE_SLAB_B1_3, SANDSTONE_SLAB_1_2_4, BRICK_SLAB_C0_26ST, BRICK_SLAB_B1_8,
                            STONE_BRICK_SLAB_B1_8, RED_SANDSTONE_SLAB_1_8, PURPUR_SLAB_1_9, RESIN_BRICK_SLAB));
            getOrCreateTagBuilder(ItemTags.STAIRS)
                    .add(asItem(COBBLESTONE_STAIRS_RD20090515, COBBLESTONE_STAIRS_INF20100629, COBBLESTONE_STAIRS_B1_7, NETHER_BRICK_STAIRS_B1_9PRE,
                            SANDSTONE_STAIRS_B1_2, SANDSTONE_STAIRS_1_3, QUARTZ_STAIRS_1_5, PRISMARINE_STAIRS_1_13, RESIN_BRICK_STAIRS));
            getOrCreateTagBuilder(ItemTags.WOODEN_BUTTONS)
                    .add(asItem(PALM_BUTTON, BANANA_BUTTON, CORN_BUTTON, POISONED_BUTTON, MAHOGANY_BUTTON, PALE_OAK_BUTTON, WOODEN_BUTTON_RD20090515, WOODEN_BUTTON_RD161348, WOODEN_BUTTON_C0_0_14A,
                            WOODEN_BUTTON_C0_0_15A, WOODEN_BUTTON_1_4, BIRCH_BUTTON_1_13, SPRUCE_BUTTON_1_13, JUNGLE_BUTTON_1_13, ACACIA_BUTTON_1_13, DARK_OAK_BUTTON_1_13));
            getOrCreateTagBuilder(ItemTags.WOODEN_DOORS)
                    .add(asItem(PALM_DOOR, BANANA_DOOR, CORN_DOOR, POISONED_DOOR, MAHOGANY_DOOR, PALE_OAK_DOOR, WOODEN_DOOR_INF20100607));
            getOrCreateTagBuilder(ItemTags.WOODEN_FENCES)
                    .add(asItem(PALM_FENCE, BANANA_FENCE, CORN_FENCE, POISONED_FENCE, MAHOGANY_FENCE, PALE_OAK_FENCE, WOODEN_FENCE_RD20090515, WOODEN_FENCE_RD161348, WOODEN_FENCE_C0_0_14A, WOODEN_FENCE_A1_0_17,
                            WOODEN_FENCE_B1_9PRE5, BIRCH_FENCE_1_8, SPRUCE_FENCE_1_8, JUNGLE_FENCE_1_8, ACACIA_FENCE_1_8, DARK_OAK_FENCE_1_8));
            getOrCreateTagBuilder(ItemTags.WOODEN_PRESSURE_PLATES)
                    .add(asItem(PALM_PRESSURE_PLATE, BANANA_PRESSURE_PLATE, CORN_PRESSURE_PLATE, POISONED_PRESSURE_PLATE, MAHOGANY_PRESSURE_PLATE, PALE_OAK_PRESSURE_PLATE,
                            BIRCH_PRESSURE_PLATE_1_13, SPRUCE_PRESSURE_PLATE_1_13, JUNGLE_PRESSURE_PLATE_1_13, ACACIA_PRESSURE_PLATE_1_13, DARK_OAK_PRESSURE_PLATE_1_13));
            getOrCreateTagBuilder(ItemTags.WOODEN_SLABS)
                    .add(asItem(PALM_SLAB, BANANA_SLAB, CORN_SLAB, POISONED_SLAB, MAHOGANY_SLAB, PALE_OAK_SLAB, BIRCH_SLAB_1_3, SPRUCE_SLAB_1_3, JUNGLE_SLAB_1_3, ACACIA_SLAB_1_7, DARK_OAK_SLAB_1_7));
            getOrCreateTagBuilder(ItemTags.WOODEN_STAIRS)
                    .add(asItem(PALM_STAIRS, BANANA_STAIRS, CORN_STAIRS, POISONED_STAIRS, MAHOGANY_STAIRS, PALE_OAK_STAIRS, WOODEN_STAIRS_RD20090515, WOODEN_STAIRS_RD161348, WOODEN_STAIRS_C0_0_14A,
                            WOODEN_STAIRS_INF20100629, WOODEN_STAIRS_B1_9PRE5, BIRCH_STAIRS_1_3, SPRUCE_STAIRS_1_3, JUNGLE_STAIRS_1_3, ACACIA_STAIRS_1_7, DARK_OAK_STAIRS_1_7));
            getOrCreateTagBuilder(ItemTags.WOODEN_TRAPDOORS)
                    .add(asItem(PALM_TRAPDOOR, BANANA_TRAPDOOR, CORN_TRAPDOOR, POISONED_TRAPDOOR, MAHOGANY_TRAPDOOR, PALE_OAK_TRAPDOOR, TRAPDOOR_B1_6));
            getOrCreateTagBuilder(ItemTags.STAIRS)
                    .add(asItem(COBBLESTONE_STAIRS_RD20090515, COBBLESTONE_STAIRS_INF20100629, COBBLESTONE_STAIRS_B1_7, BRICK_STAIRS_C0_26ST, BRICK_STAIRS_B1_8, STONE_BRICK_STAIRS_B1_8,
                            RED_SANDSTONE_STAIRS_1_8, PURPUR_STAIRS_1_9));
            getOrCreateTagBuilder(ItemTags.WALLS)
                    .add(asItem(COBBLESTONE_WALL_RD20090515, COBBLESTONE_WALL_C0_0_14A, COBBLESTONE_WALL_1_4, RESIN_BRICK_WALL));
            getOrCreateTagBuilder(ItemTags.WOOL)
                    .add(asItem(WHITE_CLOTH, LIGHT_GRAY_CLOTH_C0_0_20A, LIGHT_GRAY_CLOTH_C0_28A, DARK_GRAY_CLOTH_C0_0_20A, DARK_GRAY_CLOTH_C0_28A,
                            RED_CLOTH, ORANGE_CLOTH, YELLOW_CLOTH, CHARTREUSE_CLOTH, SPRING_GREEN_CLOTH, CYAN_CLOTH, CAPRI_CLOTH,
                            ULTRAMARINE_CLOTH, VIOLET_CLOTH, PURPLE_CLOTH, MAGENTA_CLOTH, ROSE_CLOTH, LIGHT_GRAY_WOOL_B1_2, GRAY_WOOL_B1_2, BLACK_WOOL_B1_2,
                            BROWN_WOOL_B1_2, RED_WOOL_B1_2, ORANGE_WOOL_B1_2, YELLOW_WOOL_B1_2, LIME_WOOL_B1_2 , GREEN_WOOL_B1_2, CYAN_WOOL_B1_2 , LIGHT_BLUE_WOOL_B1_2, BLUE_WOOL_B1_2 ,
                            PURPLE_WOOL_B1_2, MAGENTA_WOOL_B1_2, PINK_WOOL_B1_2, LIGHT_GRAY_WOOL_1_2_4, GRAY_WOOL_1_2_4, BLACK_WOOL_1_2_4, BROWN_WOOL_1_2_4, RED_WOOL_1_2_4, ORANGE_WOOL_1_2_4,
                            YELLOW_WOOL_1_2_4, LIME_WOOL_1_2_4, GREEN_WOOL_1_2_4, CYAN_WOOL_1_2_4, LIGHT_BLUE_WOOL_1_2_4, BLUE_WOOL_1_2_4, PURPLE_WOOL_1_2_4, MAGENTA_WOOL_1_2_4, PINK_WOOL_1_2_4));
            getOrCreateTagBuilder(ItemTags.WOOL_CARPETS)
                    .add(asItem(LIGHT_GRAY_CLOTH_CARPET_C0_0_20A, LIGHT_GRAY_CLOTH_CARPET_C0_28A, DARK_GRAY_CLOTH_CARPET_C0_0_20A, DARK_GRAY_CLOTH_CARPET_C0_28A, RED_CLOTH_CARPET, ORANGE_CLOTH_CARPET,
                            YELLOW_CLOTH_CARPET, CHARTREUSE_CLOTH_CARPET, SPRING_GREEN_CLOTH_CARPET, CYAN_CLOTH_CARPET, CAPRI_CLOTH_CARPET, ULTRAMARINE_CLOTH_CARPET, VIOLET_CLOTH_CARPET,
                            PURPLE_CLOTH_CARPET, MAGENTA_CLOTH_CARPET, ROSE_CLOTH_CARPET, GRAY_CARPET_B1_2, BLACK_CARPET_B1_2, BROWN_CARPET_B1_2, RED_CARPET_B1_2, ORANGE_CARPET_B1_2,
                            YELLOW_CARPET_B1_2, LIME_CARPET_B1_2, GREEN_CARPET_B1_2, CYAN_CARPET_B1_2, LIGHT_BLUE_CARPET_B1_2, BLUE_CARPET_B1_2, PURPLE_CARPET_B1_2,
                            MAGENTA_CARPET_B1_2, PINK_CARPET_B1_2, LIGHT_GRAY_CARPET_1_2_4, GRAY_CARPET_1_2_4, BLACK_CARPET_1_2_4, BROWN_CARPET_1_2_4,
                            RED_CARPET_1_2_4, ORANGE_CARPET_1_2_4, YELLOW_CARPET_1_2_4, LIME_CARPET_1_2_4, GREEN_CARPET_1_2_4, CYAN_CARPET_1_2_4, LIGHT_BLUE_CARPET_1_2_4,
                            BLUE_CARPET_1_2_4, PURPLE_CARPET_1_2_4, MAGENTA_CARPET_1_2_4, PINK_CARPET_1_2_4));
            getOrCreateTagBuilder(ModTags.Items.MONKEY_BREEDING_ITEMS)
                    .add(COCONUT, BANANA);

            getOrCreateTagBuilder(ModTags.Items.OAK_CHAIRS)
                    .add(asItem(OAK_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.BIRCH_CHAIRS)
                    .add(asItem(BIRCH_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.SPRUCE_CHAIRS)
                    .add(asItem(SPRUCE_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.JUNGLE_CHAIRS)
                    .add(asItem(JUNGLE_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.ACACIA_CHAIRS)
                    .add(asItem(ACACIA_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.DARK_OAK_CHAIRS)
                    .add(asItem(DARK_OAK_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.CRIMSON_CHAIRS)
                    .add(asItem(CRIMSON_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.WARPED_CHAIRS)
                    .add(asItem(WARPED_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.MANGROVE_CHAIRS)
                    .add(asItem(MANGROVE_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.BAMBOO_CHAIRS)
                    .add(asItem(BAMBOO_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.CHERRY_CHAIRS)
                    .add(asItem(CHERRY_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.PALM_CHAIRS)
                    .add(asItem(PALM_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.BANANA_CHAIRS)
                    .add(asItem(BANANA_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.CORN_CHAIRS)
                    .add(asItem(CORN_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.POISONED_CHAIRS)
                    .add(asItem(POISONED_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.MAHOGANY_CHAIRS)
                    .add(asItem(MAHOGANY_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.PALE_OAK_CHAIRS)
                    .add(asItem(PALE_OAK_CHAIR));
            getOrCreateTagBuilder(ModTags.Items.CHAIRS)
                    .addTag(ModTags.Items.OAK_CHAIRS)
                    .addTag(ModTags.Items.SPRUCE_CHAIRS)
                    .addTag(ModTags.Items.BIRCH_CHAIRS)
                    .addTag(ModTags.Items.JUNGLE_CHAIRS)
                    .addTag(ModTags.Items.ACACIA_CHAIRS)
                    .addTag(ModTags.Items.DARK_OAK_CHAIRS)
                    .addTag(ModTags.Items.CRIMSON_CHAIRS)
                    .addTag(ModTags.Items.WARPED_CHAIRS)
                    .addTag(ModTags.Items.MANGROVE_CHAIRS)
                    .addTag(ModTags.Items.BAMBOO_CHAIRS)
                    .addTag(ModTags.Items.CHERRY_CHAIRS)
                    .addTag(ModTags.Items.PALM_CHAIRS)
                    .addTag(ModTags.Items.BANANA_CHAIRS)
                    .addTag(ModTags.Items.CORN_CHAIRS)
                    .addTag(ModTags.Items.POISONED_CHAIRS)
                    .addTag(ModTags.Items.MAHOGANY_CHAIRS)
                    .addTag(ModTags.Items.PALE_OAK_CHAIRS);


            getOrCreateTagBuilder(ModTags.TrinketTags.RABBIT_SLOT)
                    .add(RABBIT, COOKED_RABBIT, RABBIT_HIDE, RABBIT_FOOT, RABBIT_TRINKET);
            getOrCreateTagBuilder(ModTags.TrinketTags.FISH_SLOT)
                    .add(FISH_TRINKET, COD, SALMON, TROPICAL_FISH, PUFFERFISH, COD_BUCKET, SALMON_BUCKET, TROPICAL_FISH_BUCKET, PUFFERFISH_BUCKET, COOKED_COD, COOKED_SALMON);
            getOrCreateTagBuilder(ModTags.TrinketTags.CAT_SLOT)
                    .add(CAT_TRINKET);

            getOrCreateTagBuilder(ModTags.Items.BOW_LOOTING_ENCHANTABLE)
                    .forceAddTag(ItemTags.SWORD_ENCHANTABLE).forceAddTag(ItemTags.BOW_ENCHANTABLE);
        }

        Item[] asItem(ItemConvertible... blocks) {
            Item[] items = new Item[blocks.length];
            for (int i = 0; i < blocks.length; i++) {
                items[i] = blocks[i].asItem();
            }
            return items;
        }
    }

    public static class BlocktopiaFluidTagProvider extends FabricTagProvider.FluidTagProvider {
        public BlocktopiaFluidTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
            super(output, completableFuture);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
            getOrCreateTagBuilder(ModTags.Fluids.CLASSIC_SPONGE_ABSORB)
                    .add(Fluids.WATER, Fluids.FLOWING_WATER, Fluids.LAVA, Fluids.FLOWING_LAVA, ModFluids.TROPICAL_WATER, ModFluids.FLOWING_TROPICAL_WATER);
            getOrCreateTagBuilder(FluidTags.WATER)
                    .add(ModFluids.TROPICAL_WATER, ModFluids.FLOWING_TROPICAL_WATER);
            getOrCreateTagBuilder(ModTags.Fluids.TROPICAL_WATER)
                    .add(ModFluids.TROPICAL_WATER, ModFluids.FLOWING_TROPICAL_WATER);
        }
    }

    public static class BlocktopiaBiomeTagProvider extends FabricTagProvider<Biome> {
        public BlocktopiaBiomeTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
            super(output, RegistryKeys.BIOME, registriesFuture);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
            getOrCreateTagBuilder(ModTags.Biomes.HAS_BANANA_TREE_HOUSE)
                    .add(ModBiomes.RAIN_FOREST_KEY);
            getOrCreateTagBuilder(ModTags.Biomes.HAS_MAHOGANY_TREE_HOUSE)
                    .add(ModBiomes.RAIN_FOREST_KEY);
            getOrCreateTagBuilder(ModTags.Biomes.HAS_FLOWERING_TREE_CHERRY_HOUSE)
                    .add(ModBiomes.RAIN_FOREST_KEY);
            getOrCreateTagBuilder(ModTags.Biomes.HAS_CORN_TREE_HOUSE)
                    .add(ModBiomes.RAIN_FOREST_KEY);
            getOrCreateTagBuilder(ModTags.Biomes.HAS_POISONED_TREE_HOUSE)
                    .add(ModBiomes.RAIN_FOREST_KEY);
        }
    }

    public static class BlocktopiaPOITagProvider extends FabricTagProvider<PointOfInterestType> {
        public BlocktopiaPOITagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
            super(output, RegistryKeys.POINT_OF_INTEREST_TYPE, registriesFuture);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
            getOrCreateTagBuilder(PointOfInterestTypeTags.ACQUIRABLE_JOB_SITE)
                    .add(ModVillagers.LEGACY_POI, ModVillagers.BEEKEEPER_POI);
        }
    }

    public static class BlocktopiaEntityTagProvider extends FabricTagProvider.EntityTypeTagProvider {
        public BlocktopiaEntityTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
            super(output, completableFuture);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
            getOrCreateTagBuilder(EntityTypeTags.FALL_DAMAGE_IMMUNE)
                    .add(ModEntityTypes.MONKEY);
            getOrCreateTagBuilder(EntityTypeTags.WITHER_FRIENDS)
                    .add(ModEntityTypes.MONKEY);
        }
    }
}
