package github.mcdatapack.blocktopia.datagen.provider;

import java.util.concurrent.CompletableFuture;

import github.mcdatapack.blocktopia.block.ModBlocks;
import github.mcdatapack.blocktopia.block.custom.BananaCropBlock;
import github.mcdatapack.blocktopia.block.custom.VerticalSlabBlock;
import github.mcdatapack.blocktopia.item.LegacyItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.TallPlantBlock;
import net.minecraft.block.enums.DoubleBlockHalf;
import net.minecraft.item.Items;
import net.minecraft.loot.LootPool;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.condition.BlockStatePropertyLootCondition;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.provider.number.ConstantLootNumberProvider;
import net.minecraft.predicate.StatePredicate;
import net.minecraft.registry.RegistryWrapper;

import static github.mcdatapack.blocktopia.block.FutureBlocks.*;
import static github.mcdatapack.blocktopia.item.LegacyItems.*;
import static github.mcdatapack.blocktopia.item.ModItems.BANANA;
import static github.mcdatapack.blocktopia.block.ModBlocks.*;
import static github.mcdatapack.blocktopia.block.LegacyBlocks.*;

public class BlocktopiaBlockLootTableProvider extends FabricBlockLootTableProvider {
    public BlocktopiaBlockLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(GOLD_ANVIL);
        addDrop(CHIPPED_GOLD_ANVIL);
        addDrop(DAMAGED_GOLD_ANVIL);
        addDrop(DIAMOND_ANVIL);
        addDrop(CHIPPED_DIAMOND_ANVIL);
        addDrop(DAMAGED_DIAMOND_ANVIL);
        addDrop(NETHERITE_ANVIL);
        addDrop(CHIPPED_NETHERITE_ANVIL);
        addDrop(DAMAGED_NETHERITE_ANVIL);

        BlockStatePropertyLootCondition.Builder builder2 = BlockStatePropertyLootCondition.builder(BANANA_CROP)
                .properties(StatePredicate.Builder.create().exactMatch(BananaCropBlock.AGE, BananaCropBlock.MAX_AGE));
        this.addDrop(BANANA_CROP, this.cropDrops(BANANA_CROP, BANANA, BANANA_CROP.asItem(), builder2));

        addDrop(FLUID_TANK);

        addDrop(TROPICAL_MOSS);
        addDrop(TROPICAL_MOSS_CARPET);
        addDrop(TROPICAL_FARM_LAND, TROPICAL_MOSS);

        addDrop(PAPER_BLOCK);
        addDrop(GUNPOWDER_BLOCK);
        addDrop(FIREWORK_BLOCK);

        addDrop(LEGACY_CUTTER);
        addDrop(WOODCUTTER);
        addDrop(DUPER);

        addDrop(SPONGE_TNT);

        addVerticalSlabDrops(ModBlocks.VERTICAL_OAK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SPRUCE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BIRCH_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_JUNGLE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_ACACIA_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_DARK_OAK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_MANGROVE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_CHERRY_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BAMBOO_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BAMBO_MOSAIC_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_CRIMSON_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_WARPED_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_STONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_COBBLESTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_MOSSY_COBBLESTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SMOOTH_STONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_STONE_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_MOSSY_STONE_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_GRANITE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_GRANITE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_DIORITE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_DIORITE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_ANDESITE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_ANDESITE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_COBBLED_DEEPSLATE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_DEEPSLATE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_DEEPSLATE_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_DEEPSLATE_TILE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_TUFF_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_TUFF_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_TUFF_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_MUD_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SANDSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SMOOTH_SANDSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_CUT_SANDSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_RED_SANDSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SMOOTH_RED_SANDSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_CUT_RED_SANDSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_PRISMARINE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BRISMARINE_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_DARK_PRISMARINE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_NETHER_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_RED_NETHER_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BLACKSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_ENDSTONE_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_PURPUR_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_QUARTZ_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SMOOTH_QUARTZ_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.EXPOSED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.WEATHERED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.OXIDIZED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.WAXED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.WAXED_EXPOSED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.WAXED_WEATHERED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.WAXED_OXIDIZED_VERTICAL_CUT_COPPER_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_COBBLESTONE_SLAB_RD20090515);
        addVerticalSlabDrops(ModBlocks.VERTICAL_COBBLESTONE_SLAB_B1_3);
        addVerticalSlabDrops(ModBlocks.VERTICAL_COBBLESTONE_SLAB_B1_7);
        addVerticalSlabDrops(ModBlocks.VERTICAL_WOODEN_SLAB_RD20090515);
        addVerticalSlabDrops(ModBlocks.VERTICAL_WOODEN_SLAB_RD161348);
        addVerticalSlabDrops(ModBlocks.VERTICAL_WOODEN_SLAB_C0_0_14A);
        addVerticalSlabDrops(ModBlocks.VERTICAL_WOODEN_SLAB_B1_3);
        addVerticalSlabDrops(ModBlocks.VERTICAL_WOODEN_SLAB_B1_9PRE5);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SANDSTONE_SLAB_B1_3);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SANDSTONE_SLAB_1_2_4);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BRICK_SLAB_C0_26ST);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BRICK_SLAB_B1_8);
        addVerticalSlabDrops(ModBlocks.VERTICAL_STONE_BRICK_SLAB_B1_8);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BIRCH_SLAB_1_3);
        addVerticalSlabDrops(ModBlocks.VERTICAL_SPRUCE_SLAB_1_3);
        addVerticalSlabDrops(ModBlocks.VERTICAL_JUNGLE_SLAB_1_3);
        addVerticalSlabDrops(ModBlocks.VERTICAL_NETHER_BRICK_SLAB_1_4_6);
        addVerticalSlabDrops(ModBlocks.VERTICAL_RED_SANDSTONE_SLAB_1_8);
        addVerticalSlabDrops(ModBlocks.VERTICAL_PURPUR_SLAB_1_9);
        addVerticalSlabDrops(ModBlocks.VERTICAL_PRISMARINE_SLAB_1_13);
        addVerticalSlabDrops(ModBlocks.VERTICAL_PALE_OAK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_RESIN_BRICK_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_PALM_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_BANANA_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_CORN_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_POISONED_SLAB);
        addVerticalSlabDrops(ModBlocks.VERTICAL_MAHOGANY_SLAB);

        addDrop(FLOWERING_CHERRY_SAPLING);
        addPottedPlantDrops(POTTED_FLOWERING_CHERRY_SAPLING);

        addDrop(GLOW_FLOWER);
        addPottedPlantDrops(POTTED_GLOW_FLOWER);

        addDrop(PALM_LOG);
        addDrop(STRIPPED_PALM_LOG);
        addDrop(PALM_WOOD);
        addDrop(STRIPPED_PALM_WOOD);
        addDrop(PALM_SAPLING);
        addPottedPlantDrops(POTTED_PALM_SAPLING);
        addDrop(PALM_PLANKS);
        addDrop(PALM_FENCE);
        addDrop(PALM_FENCE_GATE);
        addDrop(PALM_STAIRS);
        addDrop(PALM_PRESSURE_PLATE);
        addDrop(PALM_BUTTON);
        addDrop(PALM_TRAPDOOR);

        addDrop(BANANA_LOG);
        addDrop(STRIPPED_BANANA_LOG);
        addDrop(BANANA_WOOD);
        addDrop(STRIPPED_BANANA_WOOD);
        addDrop(BANANA_SAPLING);
        addPottedPlantDrops(POTTED_BANANA_SAPLING);
        addDrop(BANANA_PLANKS);
        addDrop(BANANA_FENCE);
        addDrop(BANANA_FENCE_GATE);
        addDrop(BANANA_STAIRS);
        addDrop(BANANA_PRESSURE_PLATE);
        addDrop(BANANA_BUTTON);
        addDrop(BANANA_TRAPDOOR);


        addDrop(CORN_LOG);
        addDrop(STRIPPED_CORN_LOG);
        addDrop(CORN_WOOD);
        addDrop(STRIPPED_CORN_WOOD);
        addDrop(CORN_SAPLING);
        addPottedPlantDrops(POTTED_CORN_SAPLING);
        addDrop(CORN_PLANKS);
        addDrop(CORN_FENCE);
        addDrop(CORN_FENCE_GATE);
        addDrop(CORN_STAIRS);
        addDrop(CORN_PRESSURE_PLATE);
        addDrop(CORN_BUTTON);
        addDrop(CORN_TRAPDOOR);

        addDrop(POISONED_LOG);
        addDrop(STRIPPED_POISONED_LOG);
        addDrop(POISONED_WOOD);
        addDrop(STRIPPED_POISONED_WOOD);
        addDrop(POISONED_SAPLING);
        addPottedPlantDrops(POTTED_POISONED_SAPLING);
        addDrop(POISONED_PLANKS);
        addDrop(POISONED_FENCE);
        addDrop(POISONED_FENCE_GATE);
        addDrop(POISONED_STAIRS);
        addDrop(POISONED_PRESSURE_PLATE);
        addDrop(POISONED_BUTTON);
        addDrop(POISONED_TRAPDOOR);

        addDrop(MAHOGANY_LOG);
        addDrop(STRIPPED_MAHOGANY_LOG);
        addDrop(MAHOGANY_WOOD);
        addDrop(STRIPPED_MAHOGANY_WOOD);
        addDrop(MAHOGANY_SAPLING);
        addPottedPlantDrops(POTTED_MAHOGANY_SAPLING);
        addDrop(MAHOGANY_PLANKS);
        addDrop(MAHOGANY_FENCE);
        addDrop(MAHOGANY_FENCE_GATE);
        addDrop(MAHOGANY_STAIRS);
        addDrop(MAHOGANY_PRESSURE_PLATE);
        addDrop(MAHOGANY_BUTTON);
        addDrop(MAHOGANY_TRAPDOOR);

        addDrop(COBBLESTONE_RD20090515);
        addDrop(COBBLESTONE_C0_0_14A);
        addDrop(COBBLESTONE_B1_7);
        addDrop(WOODEN_PLANKS_RD20090515);
        addDrop(WOODEN_PLANKS_RD161348);
        addDrop(WOODEN_PLANKS_C0_0_14A);
        addDrop(WOODEN_PLANKS_C0_0_15A);
        addDrop(WOODEN_PLANKS_B1_9PRE5);
        addDrop(LOG_C0_0_14A);
        addDrop(SAPLING_RD161348);
        addPottedPlantDrops(POTTED_SAPLING_RD161348);
        addDrop(SAPLING_C0_0_13A);
        addPottedPlantDrops(POTTED_SAPLING_C0_0_13A);
        addDrop(SAPLING_C0_24ST);
        addPottedPlantDrops(POTTED_SAPLING_C0_24ST);
        addDrop(SAND_C0_0_14A);
        addDrop(SAND_C0_0_15A);
        addDrop(SAND_B1_9PRE6);
        addDrop(GRAVEL_C0_0_14A);
        addDrop(GRAVEL_C0_0_15A);
        addDrop(GRAVEL_B1_9PRE5);
        addDrop(GRAVEL_1_3);
        addDrop(IRON_ORE_C0_0_14A);
        addDrop(IRON_ORE_1_14);
        addDrop(IRON_ORE_1_14_1);
        addDrop(GOLD_ORE_C0_0_14A);
        addDrop(GOLD_ORE_C0_26ST);
        addDrop(GOLD_ORE_1_14);
        addDrop(SPONGE_C0_0_19A);
        addDrop(SPONGE_1_8);
        addDrop(WET_SPONGE_1_8);
        addDropWithSilkTouch(GLASS_C0_0_19A);
        addDrop(WHITE_CLOTH);
        addDrop(LIGHT_GRAY_CLOTH_C0_0_20A);
        addDrop(LIGHT_GRAY_CLOTH_C0_28A);
        addDrop(DARK_GRAY_CLOTH_C0_0_20A);
        addDrop(DARK_GRAY_CLOTH_C0_28A);
        addDrop(RED_CLOTH);
        addDrop(ORANGE_CLOTH);
        addDrop(YELLOW_CLOTH);
        addDrop(CHARTREUSE_CLOTH);
        addDrop(SPRING_GREEN_CLOTH);
        addDrop(CYAN_CLOTH);
        addDrop(CAPRI_CLOTH);
        addDrop(ULTRAMARINE_CLOTH);
        addDrop(VIOLET_CLOTH);
        addDrop(PURPLE_CLOTH);
        addDrop(MAGENTA_CLOTH);
        addDrop(ROSE_CLOTH);
        addDrop(GOLD_BLOCK_C0_0_20A);
        addDrop(GOLD_BLOCK_C0_26ST);
        addDrop(GOLD_BLOCK_A1_2_0);
        addDrop(GOLD_BLOCK_B1_9PRE5);
        addDrop(DANDELION_C0_0_20A);
        addPottedPlantDrops(POTTED_DANDELIONS_C0_0_20A);
        addDrop(ROSE_C0_0_20A);
        addPottedPlantDrops(POTTED_ROSE_C0_0_20A);
        addDrop(POPPY_1_7);
        addPottedPlantDrops(POTTED_POPPY_1_7);
        addDrop(BROWN_MUSHROOM_C0_0_20A);
        addPottedPlantDrops(POTTED_BROWN_MUSHROOM_C0_0_20A);
        addDrop(RED_MUSHROOM_C0_0_20A);
        addPottedPlantDrops(POTTED_RED_MUSHROOM_C0_0_20A);
        addDrop(IRON_BLOCK_C0_26ST);
        addDrop(IRON_BLOCK_A1_2_0);
        addDrop(IRON_BLOCK_B1_9PRE5);
        addDrop(TNT_C0_26ST);
        addDrop(TNT_C0_28A);
        addDrop(MOSSY_COBBLESTONE_C0_26ST);
        addDrop(MOSSY_COBBLESTONE_B1_8);
        addDrop(BRICKS_C0_26ST);
        addDrop(BRICKS_A1_0_11);
        addDrop(BOOKSHELF_C0_26ST);
        addDrop(BOOKSHELF_B1_9PRE5);
        addDrop(OBSIDIAN_C0_28A);
        addDrop(DIAMOND_BLOCK_IN20100128);
        addDrop(DIAMOND_BLOCK_A1_2_0);
        addDrop(DIAMOND_BLOCK_B1_9PRE5);
        addDrop(CRAFTING_TABLE_IN20100131);
        addDrop(CRAFTING_TABLE_1_14);
        addDrop(FURNACE_IN20100219);
        addDrop(FURNACE_B1_2);
        addDrop(LADDER_INF20100607);
        addDrop(LADDER_INF20100618);
        addDrop(WOODEN_STAIRS_RD20090515);
        addDrop(WOODEN_STAIRS_RD161348);
        addDrop(WOODEN_STAIRS_C0_0_14A);
        addDrop(WOODEN_STAIRS_INF20100629);
        addDrop(WOODEN_STAIRS_B1_9PRE5);
        addDrop(COBBLESTONE_STAIRS_RD20090515);
        addDrop(COBBLESTONE_STAIRS_INF20100629);
        addDrop(COBBLESTONE_STAIRS_B1_7);
        addDrop(TORCH_IN20100124_2);
        addDrop(WALL_TORCH_IN20100124_2);
        addDrop(REDSTONE_TORCH_A1_0_1);
        addDrop(REDSTONE_WALL_TORCH_A1_0_1, REDSTONE_TORCH_A1_0_1);
        addDropWithSilkTouch(ICE_A1_0_4);
        addDrop(CLAY_BLOCK_A1_0_11);
        addDrop(WOODEN_FENCE_RD20090515);
        addDrop(WOODEN_FENCE_RD161348);
        addDrop(WOODEN_FENCE_C0_0_14A);
        addDrop(WOODEN_FENCE_A1_0_17);
        addDrop(WOODEN_FENCE_B1_9PRE5);
        addDrop(NETHERRACK_A1_2_0);
        addDrop(NETHERRACK_B1_9PRE5);
        addDrop(SOUL_SAND_A1_2_0);
        addDrop(GLOWSTONE_A1_2_0);
        addDrop(GLOWSTONE_B1_9PRE5);
        addDrop(CARVED_PUMPKIN_A1_2_0);
        addDrop(JACK_O_LANTERN_A1_2_0);
        addDrop(EXTENDED_REPEATER_TICK);
        addDrop(EXTENDED_REPEATER_SECOND);
        addDrop(EXTENDED_REPEATER_MINUTE);
        addDrop(LIGHT_GRAY_WOOL_B1_2);
        addDrop(GRAY_WOOL_B1_2);
        addDrop(BLACK_WOOL_B1_2);
        addDrop(BROWN_WOOL_B1_2);
        addDrop(RED_WOOL_B1_2);
        addDrop(ORANGE_WOOL_B1_2);
        addDrop(YELLOW_WOOL_B1_2);
        addDrop(LIME_WOOL_B1_2 );
        addDrop(GREEN_WOOL_B1_2);
        addDrop(CYAN_WOOL_B1_2 );
        addDrop(LIGHT_BLUE_WOOL_B1_2);
        addDrop(BLUE_WOOL_B1_2 );
        addDrop(PURPLE_WOOL_B1_2);
        addDrop(MAGENTA_WOOL_B1_2);
        addDrop(PINK_WOOL_B1_2);
        addDrop(LIGHT_GRAY_WOOL_1_2_4);
        addDrop(GRAY_WOOL_1_2_4);
        addDrop(BLACK_WOOL_1_2_4);
        addDrop(BROWN_WOOL_1_2_4);
        addDrop(RED_WOOL_1_2_4);
        addDrop(ORANGE_WOOL_1_2_4);
        addDrop(YELLOW_WOOL_1_2_4);
        addDrop(LIME_WOOL_1_2_4);
        addDrop(GREEN_WOOL_1_2_4);
        addDrop(CYAN_WOOL_1_2_4);
        addDrop(LIGHT_BLUE_WOOL_1_2_4);
        addDrop(BLUE_WOOL_1_2_4);
        addDrop(PURPLE_WOOL_1_2_4);
        addDrop(MAGENTA_WOOL_1_2_4);
        addDrop(PINK_WOOL_1_2_4);
        addDrop(LAPIS_BLOCK_B1_2);
        addDrop(LAPIS_BLOCK_1_6);
        addDrop(NOTE_BLOCK_B1_2);
        addDrop(SANDSTONE_B1_2);
        addDrop(SANDSTONE_1_2_4);
        addDrop(BIRCH_LOG_B1_2);
        addDrop(BIRCH_LOG_1_7);
        addDrop(SPRUCE_LOG_B1_2);
        addDrop(SPRUCE_LOG_1_7);
        addDrop(CRYING_OBSIDIAN_B1_3);
        addSlabDrops(COBBLESTONE_SLAB_RD20090515);
        addSlabDrops(COBBLESTONE_SLAB_B1_3);
        addSlabDrops(COBBLESTONE_SLAB_B1_7);
        addSlabDrops(WOODEN_SLAB_RD20090515);
        addSlabDrops(WOODEN_SLAB_RD161348);
        addSlabDrops(WOODEN_SLAB_C0_0_14A);
        addSlabDrops(WOODEN_SLAB_B1_3);
        addSlabDrops(WOODEN_SLAB_B1_9PRE5);
        addSlabDrops(SANDSTONE_SLAB_B1_3);
        addSlabDrops(SANDSTONE_SLAB_1_2_4);
        addDrop(SMOOTH_STONE_B1_3);
        addDrop(BIRCH_SAPLING_B1_5);
        addPottedPlantDrops(POTTED_BIRCH_SAPLING_B1_5);
        addDrop(SPRUCE_SAPLING_B1_5);
        addPottedPlantDrops(POTTED_SPRUCE_SAPLING_B1_5);
        addDrop(POWERED_RAIL_B1_5);
        addDrop(DETECTOR_RAIL_B1_5);
        addDrop(COBWEB_B1_5, block -> drops(block, LegacyItems.STRING_IN20100130));
        addDrop(DEAD_BUSH_B1_6, block -> dropsWithShears(block, applyExplosionDecay(block, ItemEntry.builder(Items.STICK))));
        addPottedPlantDrops(POTTED_DEAD_BUSH_B1_6);
        addDrop(SHRUB_B1_6, block -> dropsWithShears(block, applyExplosionDecay(block, ItemEntry.builder(Items.STICK))));
        addPottedPlantDrops(POTTED_SHRUB_B1_6);
        addPottedPlantDrops(POTTED_FERN_B1_6);
        addDrop(TRAPDOOR_B1_6);
        addDrop(STONE_BRICKS_B1_8);
        addDrop(CRACKED_STONE_BRICKS_B1_8);
        addDrop(MOSSY_STONE_BRICKS_B1_8);
        addSlabDrops(BRICK_SLAB_C0_26ST);
        addSlabDrops(BRICK_SLAB_B1_8);
        addSlabDrops(STONE_BRICK_SLAB_B1_8);
        addDrop(BRICK_STAIRS_C0_26ST);
        addDrop(BRICK_STAIRS_B1_8);
        addDrop(STONE_BRICK_STAIRS_B1_8);
        addDropWithSilkTouch(GLASS_PANE_B1_8);
        addDrop(WOODEN_FENCE_GATE_RD20090515);
        addDrop(WOODEN_FENCE_GATE_RD161348);
        addDrop(WOODEN_FENCE_GATE_C0_0_14A);
        addDrop(WOODEN_FENCE_GATE_B1_8);
        addDrop(WOODEN_FENCE_GATE_B1_9PRE5);
        addDrop(VINES_B1_8, block -> dropsWithSilkTouchOrShears(block, ItemEntry.builder(block)));
        addDropWithSilkTouch(MUSHROOM_STEM_B1_8);
        addDrop(RED_MUSHROOM_BLOCK_B1_8, block -> dropsWithSilkTouch(block, ItemEntry.builder(RED_MUSHROOM_C0_0_20A)));
        addDrop(BROWN_MUSHROOM_BLOCK_B1_8, block -> dropsWithSilkTouch(block, ItemEntry.builder(BROWN_MUSHROOM_C0_0_20A)));
        addDrop(MELON_BLOCK_B1_8, block -> dropsWithSilkTouch(block, ItemEntry.builder(Items.MELON_SLICE)));
        addDrop(NETHER_BRICKS_B1_9PRE);
        addDrop(NETHER_BRICK_STAIRS_B1_9PRE);
        addDrop(NETHER_BRICK_FENCE_B1_9PRE);
        addDrop(LILY_PAD_B1_9PRE);
        addDrop(ENDSTONE_B1_9PRE4);
        addDrop(JUNGLE_LOG_1_2);
        addDrop(JUNGLE_LOG_1_7);
        addDrop(JUNGLE_SAPLING_1_2);
        addPottedPlantDrops(POTTED_JUNGLE_SAPLING_1_2);
        addDrop(REDSTONE_LAMP_1_2);
        addDrop(CHISELED_STONE_BRICKS_1_2);
        addDrop(BIRCH_PLANKS_1_2_4);
        addDrop(SPRUCE_PLANKS_1_2_4);
        addDrop(JUNGLE_PLANKS_1_2_4);
        addDrop(CUT_SANDSTONE_1_2_4);
        addDrop(CHISELED_SANDSTONE_1_2_4);
        addSlabDrops(BIRCH_SLAB_1_3);
        addSlabDrops(SPRUCE_SLAB_1_3);
        addSlabDrops(JUNGLE_SLAB_1_3);
        addDrop(COCOA_1_3);
        addDrop(SANDSTONE_STAIRS_B1_2);
        addDrop(SANDSTONE_STAIRS_1_3);
        addDrop(EMERALD_BLOCK_1_3);
        addDrop(BIRCH_STAIRS_1_3);
        addDrop(SPRUCE_STAIRS_1_3);
        addDrop(JUNGLE_STAIRS_1_3);
        addDrop(OAK_WOOD_1_3);
        addDrop(BIRCH_WOOD_1_3);
        addDrop(SPRUCE_WOOD_1_3);
        addDrop(JUNGLE_WOOD_1_3);
        addDrop(WOODEN_BUTTON_RD20090515);
        addDrop(WOODEN_BUTTON_RD161348);
        addDrop(WOODEN_BUTTON_C0_0_14A);
        addDrop(WOODEN_BUTTON_C0_0_15A);
        addDrop(WOODEN_BUTTON_1_4);
        addDrop(COBBLESTONE_WALL_RD20090515);
        addDrop(COBBLESTONE_WALL_C0_0_14A);
        addDrop(COBBLESTONE_WALL_1_4);
        addDrop(NETHER_BRICK_SLAB_1_4_6);
        addDrop(REDSTONE_BLOCK_1_5);
        addDrop(ACTIVATOR_RAIL_1_5);
        addDrop(QUARTZ_BLOCK_1_5);
        addDrop(CHISELED_QUARTZ_BLOCK_1_5);
        addDrop(QUARTZ_PILLAR_1_5);
        addSlabDrops(QUARTZ_SLAB_1_5);
        addDrop(QUARTZ_STAIRS_1_5);
        addDrop(SMOOTH_SANDSTONE_1_5);
        addDrop(SMOOTH_QUARTZ_1_5);
        addDrop(WHITE_CLOTH_CARPET);
        addDrop(LIGHT_GRAY_CLOTH_CARPET_C0_0_20A);
        addDrop(LIGHT_GRAY_CLOTH_CARPET_C0_28A);
        addDrop(DARK_GRAY_CLOTH_CARPET_C0_0_20A);
        addDrop(DARK_GRAY_CLOTH_CARPET_C0_28A);
        addDrop(RED_CLOTH_CARPET);
        addDrop(ORANGE_CLOTH_CARPET);
        addDrop(YELLOW_CLOTH_CARPET);
        addDrop(CHARTREUSE_CLOTH_CARPET);
        addDrop(SPRING_GREEN_CLOTH_CARPET);
        addDrop(CYAN_CLOTH_CARPET);
        addDrop(CAPRI_CLOTH_CARPET);
        addDrop(ULTRAMARINE_CLOTH_CARPET);
        addDrop(VIOLET_CLOTH_CARPET);
        addDrop(PURPLE_CLOTH_CARPET);
        addDrop(MAGENTA_CLOTH_CARPET);
        addDrop(ROSE_CLOTH_CARPET);
        addDrop(GRAY_CARPET_B1_2);
        addDrop(BLACK_CARPET_B1_2);
        addDrop(BROWN_CARPET_B1_2);
        addDrop(RED_CARPET_B1_2);
        addDrop(ORANGE_CARPET_B1_2);
        addDrop(YELLOW_CARPET_B1_2);
        addDrop(LIME_CARPET_B1_2);
        addDrop(GREEN_CARPET_B1_2);
        addDrop(CYAN_CARPET_B1_2);
        addDrop(LIGHT_BLUE_CARPET_B1_2);
        addDrop(BLUE_CARPET_B1_2);
        addDrop(PURPLE_CARPET_B1_2);
        addDrop(MAGENTA_CARPET_B1_2);
        addDrop(PINK_CARPET_B1_2);
        addDrop(LIGHT_GRAY_CARPET_1_2_4);
        addDrop(GRAY_CARPET_1_2_4);
        addDrop(BLACK_CARPET_1_2_4);
        addDrop(BROWN_CARPET_1_2_4);
        addDrop(RED_CARPET_1_2_4);
        addDrop(ORANGE_CARPET_1_2_4);
        addDrop(YELLOW_CARPET_1_2_4);
        addDrop(LIME_CARPET_1_2_4);
        addDrop(GREEN_CARPET_1_2_4);
        addDrop(CYAN_CARPET_1_2_4);
        addDrop(LIGHT_BLUE_CARPET_1_2_4);
        addDrop(BLUE_CARPET_1_2_4);
        addDrop(PURPLE_CARPET_1_2_4);
        addDrop(MAGENTA_CARPET_1_2_4);
        addDrop(PINK_CARPET_1_2_4);
        addDrop(HAY_BALE_1_6);
        addDrop(TERRACOTTA_1_6);
        addDrop(COAL_BLOCK_1_6);
        addDrop(ALLIUM_1_7);
        addPottedPlantDrops(POTTED_ALLIUM_1_7);
        addDrop(AZURE_BLUET_1_7);
        addPottedPlantDrops(POTTED_AZURE_BLUET_1_7);
        addDrop(BLUE_ORCHID_1_7);
        addPottedPlantDrops(POTTED_BLUE_ORCHID_1_7);
        addDrop(LILAC_1_7, block -> this.dropsWithProperty(block, TallPlantBlock.HALF, DoubleBlockHalf.LOWER));
        addDrop(PEONY_1_7, block -> this.dropsWithProperty(block, TallPlantBlock.HALF, DoubleBlockHalf.LOWER));
        addDrop(ROSE_BUSH_1_7, block -> this.dropsWithProperty(block, TallPlantBlock.HALF, DoubleBlockHalf.LOWER));
        addDrop(SUNFLOWER_1_7, block -> this.dropsWithProperty(block, TallPlantBlock.HALF, DoubleBlockHalf.LOWER));
        addDrop(OXEYE_DAISY_1_7);
        addPottedPlantDrops(POTTED_OXEYE_DAISY_1_7);
        addDrop(RED_TULIP_1_7);
        addPottedPlantDrops(POTTED_RED_TULIP_1_7);
        addDrop(ORANGE_TULIP_1_7);
        addPottedPlantDrops(POTTED_ORANGE_TULIP_1_7);
        addDrop(WHITE_TULIP_1_7);
        addPottedPlantDrops(POTTED_WHITE_TULIP_1_7);
        addDrop(PINK_TULIP_1_7);
        addPottedPlantDrops(POTTED_PINK_TULIP_1_7);
        addDropWithSilkTouch(PACKED_ICE_1_7);
        addDrop(RED_SAND_1_7);
        addDropWithSilkTouch(WHITE_STAINED_GLASS_1_7);
        addDropWithSilkTouch(ORANGE_STAINED_GLASS_1_7);
        addDropWithSilkTouch(MAGENTA_STAINED_GLASS_1_7);
        addDropWithSilkTouch(LIGHT_BLUE_STAINED_GLASS_1_7);
        addDropWithSilkTouch(YELLOW_STAINED_GLASS_1_7);
        addDropWithSilkTouch(LIME_STAINED_GLASS_1_7);
        addDropWithSilkTouch(PINK_STAINED_GLASS_1_7);
        addDropWithSilkTouch(GRAY_STAINED_GLASS_1_7);
        addDropWithSilkTouch(LIGHT_GRAY_STAINED_GLASS_1_7);
        addDropWithSilkTouch(CYAN_STAINED_GLASS_1_7);
        addDropWithSilkTouch(PURPLE_STAINED_GLASS_1_7);
        addDropWithSilkTouch(BLUE_STAINED_GLASS_1_7);
        addDropWithSilkTouch(BROWN_STAINED_GLASS_1_7);
        addDropWithSilkTouch(GREEN_STAINED_GLASS_1_7);
        addDropWithSilkTouch(RED_STAINED_GLASS_1_7);
        addDropWithSilkTouch(BLACK_STAINED_GLASS_1_7);
        addDropWithSilkTouch(WHITE_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(ORANGE_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(MAGENTA_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(LIGHT_BLUE_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(YELLOW_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(LIME_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(PINK_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(GRAY_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(LIGHT_GRAY_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(CYAN_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(PURPLE_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(BLUE_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(BROWN_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(GREEN_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(RED_STAINED_GLASS_PANE_1_7);
        addDropWithSilkTouch(BLACK_STAINED_GLASS_PANE_1_7);
        addDrop(ACACIA_LOG_1_7);
        addDrop(ACACIA_WOOD_1_7);
        addDrop(ACACIA_SAPLING_1_7);
        addPottedPlantDrops(POTTED_ACACIA_SAPLING_1_7);
        addDrop(DARK_OAK_LOG_1_7);
        addDrop(DARK_OAK_WOOD_1_7);
        addDrop(DARK_OAK_SAPLING_1_7);
        addPottedPlantDrops(POTTED_DARK_OAK_SAPLING_1_7);
        addDrop(ACACIA_PLANKS_1_7);
        addDrop(ACACIA_STAIRS_1_7);
        addSlabDrops(ACACIA_SLAB_1_7);
        addDrop(DARK_OAK_PLANKS_1_7);
        addDrop(DARK_OAK_STAIRS_1_7);
        addSlabDrops(DARK_OAK_SLAB_1_7);
        addDrop(GRANITE_1_8);
        addDrop(POLISHED_GRANITE_1_8);
        addDrop(DIORITE_1_8);
        addDrop(POLISHED_DIORITE_1_8);
        addDrop(ANDESITE_1_8);
        addDrop(POLISHED_ANDESITE_1_8);
        addDrop(SLIME_BLOCK_1_8);
        addDrop(PRISMARINE_1_8);
        addDrop(PRISMARINE_BRICKS_1_8);
        addDrop(DARK_PRISMARINE_1_8);
        addDrop(RED_SANDSTONE_1_8);
        addDrop(CUT_RED_SANDSTONE_1_8);
        addDrop(CHISELED_RED_SANDSTONE_1_8);
        addDrop(SMOOTH_RED_SANDSTONE_1_8);
        addSlabDrops(RED_SANDSTONE_SLAB_1_8);
        addDrop(RED_SANDSTONE_STAIRS_1_8);
        addDrop(BIRCH_FENCE_1_8);
        addDrop(SPRUCE_FENCE_1_8);
        addDrop(JUNGLE_FENCE_1_8);
        addDrop(ACACIA_FENCE_1_8);
        addDrop(DARK_OAK_FENCE_1_8);
        addDrop(BIRCH_FENCE_GATE_1_8);
        addDrop(SPRUCE_FENCE_GATE_1_8);
        addDrop(JUNGLE_FENCE_GATE_1_8);
        addDrop(ACACIA_FENCE_GATE_1_8);
        addDrop(DARK_OAK_FENCE_GATE_1_8);
        addDrop(END_ROD_1_9);
        addDrop(ENDSTONE_BRICKS_1_9);
        addDrop(PURPUR_BLOCK_1_9);
        addDrop(PURPUR_PILLAR_1_9);
        addSlabDrops(PURPUR_SLAB_1_9);
        addDrop(PURPUR_STAIRS_1_9);
        addDrop(BONE_BLOCK_1_10);
        addDrop(MAGMA_BLOCK_1_10);
        addDrop(NETHER_WART_BLOCK_1_10);
        addDrop(NETHER_WART_BLOCK_1_14);
        addDrop(RED_NETHER_BRICKS_1_10);
        addDrop(BIRCH_BUTTON_1_13);
        addDrop(SPRUCE_BUTTON_1_13);
        addDrop(JUNGLE_BUTTON_1_13);
        addDrop(ACACIA_BUTTON_1_13);
        addDrop(DARK_OAK_BUTTON_1_13);
        addDrop(BIRCH_PRESSURE_PLATE_1_13);
        addDrop(SPRUCE_PRESSURE_PLATE_1_13);
        addDrop(JUNGLE_PRESSURE_PLATE_1_13);
        addDrop(ACACIA_PRESSURE_PLATE_1_13);
        addDrop(DARK_OAK_PRESSURE_PLATE_1_13);
        addSlabDrops(PRISMARINE_SLAB_1_13);
        addDrop(PRISMARINE_STAIRS_1_13);

        addDrop(COAL_ORE_C0_0_14A, block -> oreDrops(block, COAL_IN20100219));
        addDrop(COAL_ORE_1_14, block -> oreDrops(block, Items.COAL));
        addDrop(DIAMOND_ORE_IN20100128, block -> oreDrops(block, DIAMOND_IN20100128));
        addDrop(DIAMOND_ORE_1_14, block -> oreDrops(block, Items.DIAMOND));
        addDrop(REDSTONE_ORE_A1_0_1, block -> oreDrops(block, Items.REDSTONE));
        addDrop(REDSTONE_ORE_1_14, block -> oreDrops(block, Items.REDSTONE));
        addDrop(LAPIS_ORE_B1_2, block -> oreDrops(block, Items.LAPIS_LAZULI));
        addDrop(LAPIS_ORE_1_14, block -> oreDrops(block, Items.LAPIS_LAZULI));
        addDrop(BIRCH_LEAVES_B1_2, block -> leavesDrops(block, BIRCH_SAPLING_B1_5, SAPLING_DROP_CHANCE));
        addDrop(SPRUCE_LEAVES_B1_2, block -> leavesDrops(block, SPRUCE_SAPLING_B1_5, SAPLING_DROP_CHANCE));
        addDrop(JUNGLE_LEAVES_1_2, block -> leavesDrops(block, JUNGLE_SAPLING_1_2, SAPLING_DROP_CHANCE));
        addDrop(RUBY_ORE, block -> oreDrops(block, RUBY));
        addDrop(EMERALD_ORE_1_3, block -> oreDrops(block, EMERALD_1_3));
        addDrop(EMERALD_ORE_1_14, block -> oreDrops(block, Items.EMERALD));
        addDrop(QUARTZ_ORE_1_5, block -> oreDrops(block, Items.QUARTZ));
        addDrop(ACACIA_LEAVES_1_7, block -> leavesDrops(block, ACACIA_SAPLING_1_7, SAPLING_DROP_CHANCE));
        addDrop(DARK_OAK_LEAVES_1_7, block -> oakLeavesDrops(block, DARK_OAK_SAPLING_1_7, SAPLING_DROP_CHANCE));

        addDrop(PALE_OAK_LOG);
        addDrop(STRIPPED_PALE_OAK_LOG);
        addDrop(PALE_OAK_WOOD);
        addDrop(STRIPPED_PALE_OAK_WOOD);
        addDrop(PALE_OAK_LEAVES, block -> leavesDrops(block, PALE_OAK_SAPLING, 0.325F));
        addDrop(PALE_OAK_SAPLING);
        addDrop(PALE_OAK_PLANKS);
        addDrop(PALE_OAK_DOOR, this::doorDrops);
        addDrop(PALE_OAK_FENCE);
        addDrop(PALE_OAK_FENCE_GATE);
        addDrop(PALE_OAK_STAIRS);
        addDrop(PALE_OAK_SLAB, this::slabDrops);
        addDrop(PALE_OAK_PRESSURE_PLATE);
        addDrop(PALE_OAK_BUTTON);
        addDrop(PALE_OAK_TRAPDOOR);
        addDrop(PALE_OAK_SIGN);
        addDrop(PALE_OAK_HANGING_SIGN);
        addDrop(PALE_MOSS);
        addDrop(PALE_MOSS_CARPET);
        addDrop(PALE_HANGING_MOSS, BlocktopiaBlockLootTableProvider::dropsWithShears);
        addDrop(CLOSED_EYEBLOSSOM);
        addDrop(OPEN_EYEBLOSSOM);
        addDrop(RESIN_BLOCK);
        addDrop(RESIN_BRICKS);
        addDrop(RESIN_BRICK_STAIRS);
        addDrop(RESIN_BRICK_SLAB);
        addDrop(RESIN_BRICK_WALL);
        addDrop(CHISELED_RESIN_BRICKS);
        addDrop(WILDFLOWERS, this::flowerbedDrops);
        addDrop(LEAF_LITTERS, this::flowerbedDrops);
        addDrop(SHORT_DRY_GRASS);

        addDrop(BANANA_HANGING_MOSS, BlocktopiaBlockLootTableProvider::dropsWithShears);
        addDrop(CORN_HANGING_MOSS, BlocktopiaBlockLootTableProvider::dropsWithShears);
        addDrop(POISONED_HANGING_MOSS, BlocktopiaBlockLootTableProvider::dropsWithShears);
        addDrop(MAHOGANY_HANGING_MOSS, BlocktopiaBlockLootTableProvider::dropsWithShears);
        addDrop(FLOWERING_CHERRY_HANGING_MOSS, BlocktopiaBlockLootTableProvider::dropsWithShears);



        addDrop(XP_TRAP);
        addDrop(SANDY_DIRT, block -> drops(block, Blocks.DIRT));

       addDrop(OAK_CHAIR);
       addDrop(SPRUCE_CHAIR);
       addDrop(BIRCH_CHAIR);
       addDrop(JUNGLE_CHAIR);
       addDrop(ACACIA_CHAIR);
       addDrop(DARK_OAK_CHAIR);
       addDrop(CRIMSON_CHAIR);
       addDrop(WARPED_CHAIR);
       addDrop(MANGROVE_CHAIR);
       addDrop(BAMBOO_CHAIR);
       addDrop(CHERRY_CHAIR);
       addDrop(PALM_CHAIR);
       addDrop(BANANA_CHAIR);
       addDrop(CORN_CHAIR);
       addDrop(POISONED_CHAIR);
       addDrop(MAHOGANY_CHAIR);
       addDrop(PALE_OAK_CHAIR);
        addDrop(WOODEN_CHAIR_RD20090515);
        addDrop(WOODEN_CHAIR_RD161348);
        addDrop(WOODEN_CHAIR_C0_0_14A);
        addDrop(WOODEN_CHAIR_C0_0_15A);
        addDrop(WOODEN_CHAIR_B1_9PRE5);
        addDrop(BIRCH_CHAIR_1_2_4);
        addDrop(SPRUCE_CHAIR_1_2_4);
        addDrop(JUNGLE_CHAIR_1_2_4);
        addDrop(ACACIA_CHAIR_1_7);
        addDrop(DARK_OAK_CHAIR_1_7);
    }

    private void addVerticalSlabDrops(VerticalSlabBlock block) {
        addDrop(block, drop -> LootTable.builder()
                .pool(
                        LootPool.builder()
                                .rolls(ConstantLootNumberProvider.create(1.0F))
                                .with(
                                        this.applyExplosionDecay(
                                                drop,
                                                ItemEntry.builder(drop)
                                                        .apply(
                                                                SetCountLootFunction.builder(ConstantLootNumberProvider.create(2.0F))
                                                                        .conditionally(BlockStatePropertyLootCondition.builder(drop)
                                                                                .properties(StatePredicate.Builder.create().exactMatch(VerticalSlabBlock.TYPE, VerticalSlabBlock.VerticalSlabType.DOUBLE)))
                                                        )
                                        )
                                )
                ));
    }

    private void addDrop(Block[] blocks) {
        for (Block block : blocks)
            addDrop(block);
    }

    private void addSlabDrops(Block block) {
        addDrop(block, this::slabDrops);
    }
}
