package github.mcdatapack.blocktopia.datagen.provider;

import java.util.concurrent.CompletableFuture;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.registry.RegistryWrapper;

import static github.mcdatapack.blocktopia.init.blocks.BlockInit.*;
import static github.mcdatapack.blocktopia.init.blocks.LegacyBlocks.*;

public class BlocktopiaBlockLootTableProvider extends FabricBlockLootTableProvider {
    public BlocktopiaBlockLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(PAPER_BLOCK);
        addDrop(GUNPOWDER_BLOCK);
        addDrop(PALM_LOG);
        addDrop(STRIPPED_PALM_LOG);
        addDrop(PALM_WOOD);
        addDrop(STRIPPED_PALM_WOOD);
        addDrop(PALM_SAPLING);
        addPottedPlantDrops(POTTED_PALM_SAPLING);
        addDrop(PALM_PLANKS);
        addDrop(PALM_FENCE);
        addDrop(PALM_FENCE_GATE);
        addDrop(PALM_STAIRS);
        addDrop(PALM_PRESSURE_PLATE);
        addDrop(PALM_BUTTON);
        addDrop(PALM_TRAPDOOR);
        addDrop(PALM_SIGN);
        addDrop(PALM_WALL_SIGN, PALM_SIGN);
        addDrop(PALM_HANGING_SIGN);
        addDrop(PALM_WALL_HANGING_SIGN, PALM_HANGING_SIGN);
        addDrop(COBBLESTONE_RD20090515);
        addDrop(COBBLESTONE_C_0_0_14A);
        addDrop(COBBLESTONE_B1_7);
        addDrop(WOODEN_PLANKS_RD20090515);
        addDrop(WOODEN_PLANKS_RD161348);
        addDrop(WOODEN_PLANKS_C0_0_14A);
        addDrop(WOODEN_PLANKS_C0_0_15A);
        addDrop(WOODEN_PLANKS_B1_9PRE5);
        addDrop(LOG_C0_0_14A);
        addDrop(SAPLING_RD161348);
        addPottedPlantDrops(POTTED_SAPLING_RD161348);
        addDrop(SAPLING_C0_0_13A);
        addPottedPlantDrops(POTTED_SAPLING_C0_0_13A);
        addDrop(SAPLING_C0_24ST);
        addPottedPlantDrops(POTTED_SAPLING_C0_24ST);
        addDrop(SAND_C0_0_14A);
        addDrop(SAND_C0_0_15A);
        addDrop(SAND_B1_9PRE6);
        addDrop(GRAVEL_C0_0_14A);
        addDrop(GRAVEL_C0_0_15A);
        addDrop(GRAVEL_B1_9PRE5);
        addDrop(GRAVEL_1_3);
        addDrop(IRON_ORE_C0_0_14A);
        addDrop(IRON_ORE_1_14);
        addDrop(IRON_ORE_1_14_1);
        addDrop(GOLD_ORE_C0_0_14A);
        addDrop(GOLD_ORE_C0_26ST);
        addDrop(GOLD_ORE_1_14);
        addDrop(SPONGE_C0_0_19A);
        addDrop(SPONGE_1_8);
        addDrop(WET_SPONGE_1_8);
        addDropWithSilkTouch(GLASS_C0_0_19A);
        addDrop(WHITE_CLOTH);
        addDrop(LIGHT_GRAY_CLOTH_C0_0_20A);
        addDrop(LIGHT_GRAY_CLOTH_C0_28A);
        addDrop(DARK_GRAY_CLOTH_C0_0_20A);
        addDrop(DARK_GRAY_CLOTH_C0_28A);
        addDrop(RED_CLOTH);
        addDrop(ORANGE_CLOTH);
        addDrop(YELLOW_CLOTH);
        addDrop(CHARTREUSE_CLOTH);
        addDrop(SPRING_GREEN_CLOTH);
        addDrop(CYAN_CLOTH);
        addDrop(CAPRI_CLOTH);
        addDrop(ULTRAMARINE_CLOTH);
        addDrop(VIOLET_CLOTH);
        addDrop(PURPLE_CLOTH);
        addDrop(MAGENTA_CLOTH);
        addDrop(ROSE_CLOTH);
        addDrop(GOLD_BLOCK_C0_0_20A);
        addDrop(GOLD_BLOCK_C0_26ST);
        addDrop(GOLD_BLOCK_A1_2_0);
        addDrop(GOLD_BLOCK_B1_9PRE5);
        addDrop(DANDELION_C0_0_20A);
        addPottedPlantDrops(POTTED_DANDELIONS_C0_0_20A);
        addDrop(ROSE_C0_0_20A);
        addPottedPlantDrops(POTTED_ROSE_C0_0_20A);
        addDrop(POPPY_1_7);
        addPottedPlantDrops(POTTED_POPPY_1_7);
        addDrop(BROWN_MUSHROOM_C0_0_20A);
        addPottedPlantDrops(POTTED_BROWN_MUSHROOM_C0_0_20A);
        addDrop(RED_MUSHROOM_C0_0_20A);
        addPottedPlantDrops(POTTED_RED_MUSHROOM_C0_0_20A);
        addDrop(IRON_BLOCK_C0_26ST);
        addDrop(IRON_BLOCK_A1_2_0);
        addDrop(IRON_BLOCK_B1_9PRE5);
        addDrop(TNT_C0_26ST);
        addDrop(TNT_C0_28A);
        addDrop(MOSSY_COBBLESTONE_C0_26ST);
        addDrop(MOSSY_COBBLESTONE_B1_8);
        addDrop(BRICKS_C0_26ST);
        addDrop(BRICKS_A1_0_11);
        addDrop(BOOKSHELF_C0_26ST);
        addDrop(BOOKSHELF_B1_9PRE5);
        addDrop(OBSIDIAN_C0_28A);
        addDrop(DIAMOND_BLOCK_IN20100128);
        addDrop(DIAMOND_BLOCK_A1_2_0);
        addDrop(DIAMOND_BLOCK_B1_9PRE5);
        addDrop(CRAFTING_TABLE_IN20100131);
        addDrop(CRAFTING_TABLE_1_14);
        addDrop(FURNACE_IN20100219);
        addDrop(LIT_FURNACE_IN20100219);
        addDrop(FURNACE_B1_2);
        addDrop(LIT_FURNACE_B1_2);
        addDrop(LADDER_INF20100607);
        addDrop(LADDER_INF20100618);
        addDrop(WOODEN_STAIRS_RD20090515);
        addDrop(WOODEN_STAIRS_RD161348);
        addDrop(WOODEN_STAIRS_C0_0_14A);
        addDrop(WOODEN_STAIRS_INF20100629);
        addDrop(WOODEN_STAIRS_B1_9PRE5);
        addDrop(COBBLESTONE_STAIRS_RD20090515);
        addDrop(COBBLESTONE_STAIRS_C0_0_14A);
        addDrop(COBBLESTONE_STAIRS_B1_7);
        addDrop(SIGN_INF20100607);
        addDrop(WALL_SIGN_INF20100607);
        addDrop(TORCH_IN20100124_2);
        addDrop(WALL_TORCH_IN20100124_2);
        addDrop(REDSTONE_TORCH_A1_0_1);
        addDrop(REDSTONE_WALL_TORCH_A1_0_1);
        addDropWithSilkTouch(ICE_A1_0_4);
        addDrop(CLAY_BLOCK_A1_0_11);
        addDrop(WOODEN_FENCE_RD20090515);
        addDrop(WOODEN_FENCE_RD161348);
        addDrop(WOODEN_FENCE_C0_0_14A);
        addDrop(WOODEN_FENCE_A1_0_17);
        addDrop(WOODEN_FENCE_B1_9PRE5);
        addDrop(NETHERRACK_A1_2_0);
        addDrop(NETHERRACK_B1_9PRE5);
        addDrop(SOUL_SAND_A1_2_0);
        addDrop(GLOWSTONE_A1_2_0);
        addDrop(GLOWSTONE_B1_9PRE5);
        addDrop(CARVED_PUMPKIN_A1_2_0);
        addDrop(JACK_O_LANTERN_A1_2_0);
    }
}
