package github.mcdatapack.blocktopia.datagen.provider;

import github.mcdatapack.blocktopia.Blocktopia;
import github.mcdatapack.blocktopia.block.custom.ChairBlock;
import github.mcdatapack.blocktopia.block.custom.WoodCutterBlock;
import github.mcdatapack.blocktopia.block.entity.custom.FluidTankBlockEntity;
import github.mcdatapack.blocktopia.item.ModItemGroups;
import github.mcdatapack.blocktopia.block.ModBlocks;
import github.mcdatapack.blocktopia.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.text.MutableText;
import net.minecraft.text.Text;
import net.minecraft.text.TranslatableTextContent;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

import static github.mcdatapack.blocktopia.block.FutureBlocks.*;
import static github.mcdatapack.blocktopia.block.LegacyBlocks.*;
import static github.mcdatapack.blocktopia.block.ModBlocks.WOODCUTTER;
import static github.mcdatapack.blocktopia.item.FutureItems.*;
import static github.mcdatapack.blocktopia.item.FutureItems.RESIN_BRICK;
import static github.mcdatapack.blocktopia.item.LegacyItems.*;
import static github.mcdatapack.blocktopia.item.LegacyItems.RABBIT_STEW_1_8;
import static github.mcdatapack.blocktopia.item.ModItems.FUTURE_INGOT;

public class BlocktopiaLangProvider extends FabricLanguageProvider {
    public BlocktopiaLangProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "en_us", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder builder) {
        try {
            builder.add(Path.of(URI.create(String.valueOf(BlocktopiaLangProvider.class.getClassLoader().getResource("assets/blocktopia/notdatagen/lang/en_us.json")))));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        builder.add(ModBlocks.FLUID_TANK, "Fluid Tank");
        addText(builder, FluidTankBlockEntity.NAME, "Fluid Tank");
        builder.add(ModItemGroups.COLORED_BLOCKS_GROUP, "§2§lBlocktopia: §rColored Blocks");
        builder.add(ModItemGroups.LEGACY_ITEMS_GROUP, "§2§lBlocktopia: §rLegacy Items");
        addChairs(builder, ModBlocks.OAK_CHAIR, "Oak Chair");
        addChairs(builder, ModBlocks.BIRCH_CHAIR, "Birch Chair");
        addChairs(builder, ModBlocks.SPRUCE_CHAIR, "Spruce Chair");
        addChairs(builder, ModBlocks.JUNGLE_CHAIR, "Jungle Chair");
        addChairs(builder, ModBlocks.ACACIA_CHAIR, "Acacia Chair");
        addChairs(builder, ModBlocks.DARK_OAK_CHAIR, "Dark Oak Chair");
        addChairs(builder, ModBlocks.CRIMSON_CHAIR, "Crimson Chair");
        addChairs(builder, ModBlocks.WARPED_CHAIR, "Warped Chair");
        addChairs(builder, ModBlocks.MANGROVE_CHAIR, "Mangrove Chair");
        addChairs(builder, ModBlocks.BAMBOO_CHAIR, "Bamboo Chair");
        addChairs(builder, ModBlocks.CHERRY_CHAIR, "Cherry Chair");
        addChairs(builder, ModBlocks.PALM_CHAIR, "Palm Chair");
        addChairs(builder, ModBlocks.BANANA_CHAIR, "Banana Chair");
        addChairs(builder, ModBlocks.CORN_CHAIR, "Corn Chair");
        addChairs(builder, ModBlocks.POISONED_CHAIR, "Poisoned Chair");
        addChairs(builder, ModBlocks.MAHOGANY_CHAIR, "Mahogany Chair");
        addChairs(builder, ModBlocks.PALE_OAK_CHAIR, "Pale Oak Chair");
        builder.add(QUIVER_IN20091231_2255, "Quiver");
        builder.add(QUIVER_IN20100122_2251, "Quiver");
        builder.add(APPLE_IN20091231_2255, "Apple");
        builder.add(APPLE_1_4, "Apple");
        builder.add(COAL_IN20100128, "Coal");
        builder.add(COAL_IN20100219, "Coal");
        builder.add(COAL_1_3, "Coal");
        builder.add(DIAMOND_IN20100128, "Diamond");
        builder.add(DIAMOND_1_3, "Diamond");
        builder.add(GOLD_INGOT_IN20100128, "Gold Ingot");
        builder.add(GOLD_INGOT_IN20100129, "Gold Ingot");
        builder.add(IRON_INGOT_IN20100128, "Iron Ingot");
        builder.add(IRON_INGOT_IN20100129, "Iron Ingot");
        builder.add(BOWL_IN20100130, "Bowl");
        builder.add(MUSHROOM_STEW_IN20100130, "Mushroom Stew");
        builder.add(SULPHUR, "Sulphur");
        builder.add(STRING_IN20100130, "String");
        builder.add(FEATHER_IN20100130, "Feather");
        builder.add(FEATHER_IN20100206, "Feather");
        builder.add(BREAD_IN20100206, "Bread");
        builder.add(BREAD_1_4, "Bread");
        builder.add(WHEAT_IN20100206, "Wheat");
        builder.add(FLINT_IN20100219, "Flint");
        builder.add(FLINT_1_3, "Flint");
        builder.add(PORKCHOP_IN20100219, "Raw Porkchop");
        builder.add(PORKCHOP_1_4, "Raw Porkchop");
        builder.add(COOKED_PORKCHOP_IN20100219, "Cooked Porkchop");
        builder.add(COOKED_PORKCHOP_B1_8, "Cooked Porkchop");
        builder.add(COOKED_PORKCHOP_1_4, "Cooked Porkchop");
        builder.add(GOLDEN_APPLE_INF20100227, "Golden Apple");
        builder.add(LEATHER_A1_0_8, "Leather");
        builder.add(PAPER_A1_0_11, "Paper");
        builder.add(BOOK_A1_0_11, "Book");
        builder.add(CLAY_BALL_A1_0_11, "Clay Ball");
        builder.add(BRICK_A1_0_11, "Brick");
        builder.add(SLIMEBALL_A1_0_11, "Slimeball");
        builder.add(GLOWSTONE_DUST_A1_2_0, "Glowstone");
        builder.add(FISH_A1_2_0, "Raw Fish");
        builder.add(COOKED_FISH_A1_2_0, "Cooked Fish");
        builder.add(BONE_B1_2, "Bone");
        builder.add(BONE_MEAL_B1_2, "Bone Meal");
        builder.add(BONE_MEAL_1_3, "Bone Meal");
        builder.add(COOKIE_B1_4, "Cookie");
        builder.add(CHICKEN_B1_8, "Raw Chicken");
        builder.add(CHICKEN_1_4, "Raw Chicken");
        builder.add(COOKED_CHICKEN_B1_8, "Cooked Chicken");
        builder.add(COOKED_CHICKEN_1_4, "Cooked Chicken");
        builder.add(BEEF_B1_8, "Raw Beef");
        builder.add(BEEF_1_3, "Raw Beef");
        builder.add(BEEF_1_4, "Raw Beef");
        builder.add(COOKED_BEEF_B1_8, "Cooked Beef");
        builder.add(COOKED_BEEF_1_3, "Cooked Beef");
        builder.add(COOKED_BEEF_1_4, "Cooked Beef");
        builder.add(ROTTEN_FLESH_B1_8, "Rotten Flesh");
        builder.add(ROTTEN_FLESH_1_3, "Rotten Flesh");
        builder.add(GHAST_TEAR_B1_9PRE, "Ghast Tear");
        builder.add(GOLD_NUGGET_B1_9PRE, "Gold Nugget");
        builder.add(GOLD_NUGGET_1_3, "Gold Nugget");
        builder.add(BLAZE_POWDER_B1_9PRE2, "Blaze Powder");
        builder.add(FERMENTED_SPIDER_EYE_B1_9PRE2, "Fermented Spider Eye");
        builder.add(MAGMA_CREAM_B1_9PRE2, "Magma Cream");
        builder.add(MAGMA_CREAM_1_3, "Magma Cream");
        builder.add(SPIDER_EYE_B1_9PRE2, "Spider Eye");
        builder.add(GLISTERING_MELON_B1_9PRE4, "Glistering Melon Slice");
        builder.add(RUBY, "Ruby");
        builder.add(EMERALD_1_3, "Emerald");
        builder.add(ENCHANTED_GOLDEN_APPLE_1_3, "Enchanted Golden Apple");
        builder.add(GOLDEN_CARROT_1_4, "Golden Carrot");
        builder.add(BAKED_POTATO_1_4, "Baked Potato");
        builder.add(POISONOUS_POTATO_1_4, "Poisonous Potato");
        builder.add(NETHER_STAR_1_4, "Nether Star");
        builder.add(PUMPKIN_PIE_1_4, "Pumpkin Pie");
        builder.add(QUARTZ_1_5, "Nether Quartz");
        builder.add(CLOWNFISH_1_7, "Clownfish");
        builder.add(SALMON_1_7, "Raw Salmon");
        builder.add(COOKED_SALMON_1_7, "Cooked Salmon");
        builder.add(PUFFERFISH_1_7, "Pufferfish");
        builder.add(PRISMARINE_CRYSTAL_1_8, "Prismarine Crystals");
        builder.add(PRISMARINE_SHARD_1_8, "Prismarine Shard");
        builder.add(MUTTON_1_8, "Raw Mutton");
        builder.add(COOKED_MUTTON_1_8, "Cooked Mutton");
        builder.add(RABBIT_1_8, "Raw Rabbit");
        builder.add(COOKED_RABBIT_1_8, "Cooked Rabbit");
        builder.add(RABBIT_FOOT_1_8, "Rabbit Foot");
        builder.add(RABBIT_HIDE_1_8, "Rabbit Hide");
        builder.add(RABBIT_STEW_1_8, "Rabbit Stew");
        builder.add(LIGHT_GRAY_WOOL_B1_2, "Light Gray Wool");
        builder.add(GRAY_WOOL_B1_2, "Gray Wool");
        builder.add(BLACK_WOOL_B1_2, "Black Wool");
        builder.add(BROWN_WOOL_B1_2, "Brown Wool");
        builder.add(RED_WOOL_B1_2, "Red Wool");
        builder.add(ORANGE_WOOL_B1_2, "Orange Wool");
        builder.add(YELLOW_WOOL_B1_2, "Yellow Wool");
        builder.add(LIME_WOOL_B1_2 , "Lime Wool");
        builder.add(GREEN_WOOL_B1_2, "Green Wool");
        builder.add(CYAN_WOOL_B1_2 , "Cyan Wool");
        builder.add(LIGHT_BLUE_WOOL_B1_2, "Light Blue Wool");
        builder.add(BLUE_WOOL_B1_2 , "Blue Wool");
        builder.add(PURPLE_WOOL_B1_2, "Purple Wool");
        builder.add(MAGENTA_WOOL_B1_2, "Magenta Wool");
        builder.add(PINK_WOOL_B1_2, "Pink Wool");
        builder.add(LIGHT_GRAY_WOOL_1_2_4, "Light Gray Wool");
        builder.add(GRAY_WOOL_1_2_4, "Gray Wool");
        builder.add(BLACK_WOOL_1_2_4, "Black Wool");
        builder.add(BROWN_WOOL_1_2_4, "Brown Wool");
        builder.add(RED_WOOL_1_2_4, "Red Wool");
        builder.add(ORANGE_WOOL_1_2_4, "Orange Wool");
        builder.add(YELLOW_WOOL_1_2_4, "Yellow Wool");
        builder.add(LIME_WOOL_1_2_4, "Lime Wool");
        builder.add(GREEN_WOOL_1_2_4, "Green Wool");
        builder.add(CYAN_WOOL_1_2_4, "Cyan Wool");
        builder.add(LIGHT_BLUE_WOOL_1_2_4, "Light Blue Wool");
        builder.add(BLUE_WOOL_1_2_4, "Blue Wool");
        builder.add(PURPLE_WOOL_1_2_4, "Purple Wool");
        builder.add(MAGENTA_WOOL_1_2_4, "Magenta Wool");
        builder.add(PINK_WOOL_1_2_4, "Pink Wool");
        builder.add(CAKE_B1_2, "Cake");
        builder.add(LAPIS_ORE_B1_2, "Lapis Lazuli Ore");
        builder.add(LAPIS_ORE_1_14, "Lapis Lazuli Ore");
        builder.add(LAPIS_BLOCK_B1_2, "Block of Lapis Lazuli");
        builder.add(LAPIS_BLOCK_1_6, "Block of Lapis Lazuli");
        builder.add(NOTE_BLOCK_B1_2, "Note Block");
        builder.add(SANDSTONE_B1_2, "Sandstone");
        builder.add(SANDSTONE_1_2_4, "Sandstone");
        builder.add(BIRCH_LOG_B1_2, "Birch Log");
        builder.add(BIRCH_LOG_1_7, "Birch Log");
        builder.add(BIRCH_LEAVES_B1_2, "Birch Leaves");
        builder.add(SPRUCE_LOG_B1_2, "Spruce Log");
        builder.add(SPRUCE_LOG_1_7, "Spruce Log");
        builder.add(SPRUCE_LEAVES_B1_2, "Spruce Leaves");
        builder.add(CRYING_OBSIDIAN_B1_3, "Crying Obsidian");
        builder.add(COBBLESTONE_SLAB_RD20090515, "§4Cobblestone Slab");
        builder.add(COBBLESTONE_SLAB_B1_3, "Cobblestone Slab");
        builder.add(COBBLESTONE_SLAB_B1_7, "Cobblestone Slab");
        builder.add(WOODEN_SLAB_RD20090515, "§4Wooden Slab");
        builder.add(WOODEN_SLAB_RD161348, "§4Wooden Slab");
        builder.add(WOODEN_SLAB_C0_0_14A, "§4Wooden Slab");
        builder.add(WOODEN_SLAB_B1_3, "Wooden Slab");
        builder.add(WOODEN_SLAB_B1_9PRE5, "Wooden Slab");
        builder.add(SANDSTONE_SLAB_B1_3, "Sandstone Slab");
        builder.add(SANDSTONE_SLAB_1_2_4, "Sandstone Slab");
        builder.add(SMOOTH_STONE_B1_3, "Smooth Stone");
        builder.add(BIRCH_SAPLING_B1_5, "Birch Sapling");
        builder.add(SPRUCE_SAPLING_B1_5, "Spruce Sapling");
        builder.add(POWERED_RAIL_B1_5, "Powered Rail");
        builder.add(DETECTOR_RAIL_B1_5, "Detector Rail");
        builder.add(COBWEB_B1_5, "Cobweb");
        builder.add(DEAD_BUSH_B1_6, "Dead Bush");
        builder.add(SHRUB_B1_6, "Shrub");
        builder.add(SHORT_GRASS_B1_6, "Short Grass");
        builder.add(FERN_B1_6, "Fern");
        builder.add(TRAPDOOR_B1_6, "Wooden Trapdoor");
        builder.add(STONE_BRICKS_B1_8, "Stone Bricks");
        builder.add(CRACKED_STONE_BRICKS_B1_8, "Cracked Stone Bricks");
        builder.add(MOSSY_STONE_BRICKS_B1_8, "Mossy Stone Bricks");
        builder.add(INFESTED_COBBLESTONE_RD20090515, "§4Infested Cobblestone");
        builder.add(INFESTED_COBBLESTONE_C0_0_14A, "§4Infested Cobblestone");
        builder.add(INFESTED_COBBLESTONE_B1_8, "Infested Cobblestone");
        builder.add(INFESTED_STONE_BRICKS_B1_8, "Infested Stone Bricks");
        builder.add(BRICK_SLAB_C0_26ST, "§4Brick Slab");
        builder.add(BRICK_SLAB_B1_8, "Brick Slab");
        builder.add(STONE_BRICK_SLAB_B1_8, "Stone Brick Slab");
        builder.add(BRICK_STAIRS_C0_26ST, "§4Brick Stairs");
        builder.add(BRICK_STAIRS_B1_8, "Brick Stairs");
        builder.add(STONE_BRICK_STAIRS_B1_8, "Stone Brick Stairs");
        builder.add(GLASS_PANE_B1_8, "Glass Pane");
        builder.add(WOODEN_FENCE_GATE_RD20090515, "§4Wooden Fence Gate");
        builder.add(WOODEN_FENCE_GATE_RD161348, "§4Wooden Fence Gate");
        builder.add(WOODEN_FENCE_GATE_C0_0_14A, "§4Wooden Fence Gate");
        builder.add(WOODEN_FENCE_GATE_B1_8, "Wooden Fence Gate");
        builder.add(WOODEN_FENCE_GATE_B1_9PRE5, "Wooden Fence Gate");
        builder.add(VINES_B1_8, "Vines");
        builder.add(MUSHROOM_STEM_B1_8, "Mushroom Stem");
        builder.add(RED_MUSHROOM_BLOCK_B1_8, "Red Mushroom Block");
        builder.add(BROWN_MUSHROOM_BLOCK_B1_8, "Brown Mushroom Block");
        builder.add(MELON_BLOCK_B1_8, "Melon Block");
        builder.add(NETHER_BRICKS_B1_9PRE, "Nether Bricks");
        builder.add(NETHER_BRICK_STAIRS_B1_9PRE, "Nether Brick Stairs");
        builder.add(NETHER_BRICK_FENCE_B1_9PRE, "Nether Brick Fence");
        builder.add(LILY_PAD_B1_9PRE, "Lily Pad");
        builder.add(ENDSTONE_B1_9PRE4, "Endstone");
        builder.add(JUNGLE_LOG_1_2, "Jungle Log");
        builder.add(JUNGLE_LOG_1_7, "Jungle Log");
        builder.add(JUNGLE_LEAVES_1_2, "Jungle Leaves");
        builder.add(JUNGLE_SAPLING_1_2, "Jungle Sapling");
        builder.add(REDSTONE_LAMP_1_2, "Redstone Lamp");
        builder.add(CHISELED_STONE_BRICKS_1_2, "Chiseled Stone Bricks");
        builder.add(BIRCH_PLANKS_1_2_4, "Birch Planks");
        builder.add(SPRUCE_PLANKS_1_2_4, "Spruce Planks");
        builder.add(JUNGLE_PLANKS_1_2_4, "Jungle Planks");
        builder.add(CUT_SANDSTONE_1_2_4, "Cut Sandstone");
        builder.add(CHISELED_SANDSTONE_1_2_4, "Chiseled Sandstone");
        builder.add(BIRCH_SLAB_1_3, "Birch Slab");
        builder.add(SPRUCE_SLAB_1_3, "Spruce Slab");
        builder.add(JUNGLE_SLAB_1_3, "Jungle Slab");
        builder.add(COCOA_1_3, "Cocoa");
        builder.add(RUBY_ORE, "Ruby Ore");
        builder.add(EMERALD_ORE_1_3, "Emerald Ore");
        builder.add(EMERALD_ORE_1_14, "Emerald Ore");
        builder.add(SANDSTONE_STAIRS_B1_2, "§4Sandstone Stairs");
        builder.add(SANDSTONE_STAIRS_1_3, "Sandstone Stairs");
        builder.add(EMERALD_BLOCK_1_3, "Emerald Block");
        builder.add(BIRCH_STAIRS_1_3, "Birch Stairs");
        builder.add(SPRUCE_STAIRS_1_3, "Spruce Stairs");
        builder.add(JUNGLE_STAIRS_1_3, "Jungle Stairs");
        builder.add(OAK_WOOD_1_3, "Oak Wood");
        builder.add(BIRCH_WOOD_1_3, "Birch Wood");
        builder.add(SPRUCE_WOOD_1_3, "Spruce Wood");
        builder.add(JUNGLE_WOOD_1_3, "Jungle Wood");
        builder.add(WOODEN_BUTTON_RD20090515, "§4Wooden Button");
        builder.add(WOODEN_BUTTON_RD161348, "§4Wooden Button");
        builder.add(WOODEN_BUTTON_C0_0_14A, "§4Wooden Button");
        builder.add(WOODEN_BUTTON_C0_0_15A, "§4Wooden Button");
        builder.add(WOODEN_BUTTON_1_4, "Wooden Button");
        builder.add(COBBLESTONE_WALL_RD20090515, "§4Cobblestone Wall");
        builder.add(COBBLESTONE_WALL_C0_0_14A, "§4Cobblestone Wall");
        builder.add(COBBLESTONE_WALL_1_4, "Cobblestone Wall");
        builder.add(NETHER_BRICK_SLAB_1_4_6, "Nether Brick Slab");
        builder.add(QUARTZ_ORE_1_5, "Nether Quartz Ore");
        builder.add(REDSTONE_BLOCK_1_5, "Redstone Block");
        builder.add(ACTIVATOR_RAIL_1_5, "Activator Rail");
        builder.add(QUARTZ_BLOCK_1_5, "Quartz Block");
        builder.add(CHISELED_QUARTZ_BLOCK_1_5, "Chiseled Quartz Block");
        builder.add(QUARTZ_PILLAR_1_5, "Quartz Pillar");
        builder.add(QUARTZ_SLAB_1_5, "Quartz Slab");
        builder.add(QUARTZ_STAIRS_1_5, "Quartz Stairs");
        builder.add(SMOOTH_SANDSTONE_1_5, "Smooth Sandstone");
        builder.add(SMOOTH_QUARTZ_1_5, "Smooth Quartz");
        builder.add(WHITE_CLOTH_CARPET, "White Cloth Carpet");
        builder.add(LIGHT_GRAY_CLOTH_CARPET_C0_0_20A, "Light Gray Cloth Carpet");
        builder.add(LIGHT_GRAY_CLOTH_CARPET_C0_28A, "Light Gray Cloth Carpet");
        builder.add(DARK_GRAY_CLOTH_CARPET_C0_0_20A, "Dark Gray Cloth Carpet");
        builder.add(DARK_GRAY_CLOTH_CARPET_C0_28A, "Dark Gray Cloth Carpet");
        builder.add(RED_CLOTH_CARPET, "Red Cloth Carpet");
        builder.add(ORANGE_CLOTH_CARPET, "Orange Cloth Carpet");
        builder.add(YELLOW_CLOTH_CARPET, "Yellow Cloth Carpet");
        builder.add(CHARTREUSE_CLOTH_CARPET, "Chartreuse Cloth Carpet");
        builder.add(SPRING_GREEN_CLOTH_CARPET, "Spring Green Cloth Carpet");
        builder.add(CYAN_CLOTH_CARPET, "Cyan Cloth Carpet");
        builder.add(CAPRI_CLOTH_CARPET, "Capri Cloth Carpet");
        builder.add(ULTRAMARINE_CLOTH_CARPET, "Ultramarine Cloth Carpet");
        builder.add(VIOLET_CLOTH_CARPET, "Violet Cloth Carpet");
        builder.add(PURPLE_CLOTH_CARPET, "Purple Cloth Carpet");
        builder.add(MAGENTA_CLOTH_CARPET, "Magenta Cloth Carpet");
        builder.add(ROSE_CLOTH_CARPET, "Rose Cloth Carpet");
        builder.add(GRAY_CARPET_B1_2, "Gray Carpet");
        builder.add(BLACK_CARPET_B1_2, "Black Carpet");
        builder.add(BROWN_CARPET_B1_2, "Brown Carpet");
        builder.add(RED_CARPET_B1_2, "Red Carpet");
        builder.add(ORANGE_CARPET_B1_2, "Orange Carpet");
        builder.add(YELLOW_CARPET_B1_2, "Yellow Carpet");
        builder.add(LIME_CARPET_B1_2, "Lime Carpet");
        builder.add(GREEN_CARPET_B1_2, "Green Carpet");
        builder.add(CYAN_CARPET_B1_2, "Cyan Carpet");
        builder.add(LIGHT_BLUE_CARPET_B1_2, "Light Blue Carpet");
        builder.add(BLUE_CARPET_B1_2, "Blue Carpet");
        builder.add(PURPLE_CARPET_B1_2, "Purple Carpet");
        builder.add(MAGENTA_CARPET_B1_2, "Magenta Carpet");
        builder.add(PINK_CARPET_B1_2, "Pink Carpet");
        builder.add(LIGHT_GRAY_CARPET_1_2_4, "Light Gray Carpet");
        builder.add(GRAY_CARPET_1_2_4, "Gray Carpet");
        builder.add(BLACK_CARPET_1_2_4, "Black Carpet");
        builder.add(BROWN_CARPET_1_2_4, "Brown Carpet");
        builder.add(RED_CARPET_1_2_4, "Red Carpet");
        builder.add(ORANGE_CARPET_1_2_4, "Orange Carpet");
        builder.add(YELLOW_CARPET_1_2_4, "Yellow Carpet");
        builder.add(LIME_CARPET_1_2_4, "Lime Carpet");
        builder.add(GREEN_CARPET_1_2_4, "Green Carpet");
        builder.add(CYAN_CARPET_1_2_4, "Cyan Carpet");
        builder.add(LIGHT_BLUE_CARPET_1_2_4, "Light Blue Carpet");
        builder.add(BLUE_CARPET_1_2_4, "Blue Carpet");
        builder.add(PURPLE_CARPET_1_2_4, "Purple Carpet");
        builder.add(MAGENTA_CARPET_1_2_4, "Magenta Carpet");
        builder.add(PINK_CARPET_1_2_4, "Pink Carpet");
        builder.add(HAY_BALE_1_6, "Hay Bale");
        builder.add(TERRACOTTA_1_6, "Terracotta");
        builder.add(COAL_BLOCK_1_6, "Block of Coal");
        builder.add(ALLIUM_1_7, "Allium");
        builder.add(AZURE_BLUET_1_7, "Azure Bluet");
        builder.add(BLUE_ORCHID_1_7, "Blue Orchid");
        builder.add(LILAC_1_7, "Lilac");
        builder.add(PEONY_1_7, "Peony");
        builder.add(ROSE_BUSH_1_7, "Rose Bush");
        builder.add(SUNFLOWER_1_7, "Sunflower");
        builder.add(OXEYE_DAISY_1_7, "Oxeye Daisy");
        builder.add(RED_TULIP_1_7, "Red Tulip");
        builder.add(ORANGE_TULIP_1_7, "Orange Tulip");
        builder.add(WHITE_TULIP_1_7, "White Tulip");
        builder.add(PINK_TULIP_1_7, "Pink Tulip");
        builder.add(LARGE_FERN_1_7, "Large Fern");
        builder.add(TALL_GRASS_1_7, "Tall Grass");
        builder.add(PACKED_ICE_1_7, "Packed Ice");
        builder.add(INFESTED_CRACKED_STONE_BRICKS_1_7, "Infested Cracked Stone Bricks");
        builder.add(INFESTED_MOSSY_STONE_BRICKS_1_7, "Infested Mossy Stone Bricks");
        builder.add(INFESTED_CHISELED_STONE_BRICKS_1_7, "Infested Chiseled Stone Bricks");
        builder.add(RED_SAND_1_7, "Red Sand");
        builder.add(WHITE_STAINED_GLASS_1_7, "White Stained Glass");
        builder.add(ORANGE_STAINED_GLASS_1_7, "Orange Stained Glass");
        builder.add(MAGENTA_STAINED_GLASS_1_7, "Magenta Stained Glass");
        builder.add(LIGHT_BLUE_STAINED_GLASS_1_7, "Light Blue Stained Glass");
        builder.add(YELLOW_STAINED_GLASS_1_7, "Yellow Stained Glass");
        builder.add(LIME_STAINED_GLASS_1_7, "Lime Stained Glass");
        builder.add(PINK_STAINED_GLASS_1_7, "Pink Stained Glass");
        builder.add(GRAY_STAINED_GLASS_1_7, "Gray Stained Glass");
        builder.add(LIGHT_GRAY_STAINED_GLASS_1_7, "Light Gray Stained Glass");
        builder.add(CYAN_STAINED_GLASS_1_7, "Cyan Stained Glass");
        builder.add(PURPLE_STAINED_GLASS_1_7, "Purple Stained Glass");
        builder.add(BLUE_STAINED_GLASS_1_7, "Blue Stained Glass");
        builder.add(BROWN_STAINED_GLASS_1_7, "Brown Stained Glass");
        builder.add(GREEN_STAINED_GLASS_1_7, "Green Stained Glass");
        builder.add(RED_STAINED_GLASS_1_7, "Red Stained Glass");
        builder.add(BLACK_STAINED_GLASS_1_7, "Black Stained Glass");
        builder.add(WHITE_STAINED_GLASS_PANE_1_7, "White Stained Glass Pane");
        builder.add(ORANGE_STAINED_GLASS_PANE_1_7, "Orange Stained Glass Pane");
        builder.add(MAGENTA_STAINED_GLASS_PANE_1_7, "Magenta Stained Glass Pane");
        builder.add(LIGHT_BLUE_STAINED_GLASS_PANE_1_7, "Light Blue Stained Glass Pane");
        builder.add(YELLOW_STAINED_GLASS_PANE_1_7, "Yellow Stained Glass Pane");
        builder.add(LIME_STAINED_GLASS_PANE_1_7, "Lime Stained Glass Pane");
        builder.add(PINK_STAINED_GLASS_PANE_1_7, "Pink Stained Glass Pane");
        builder.add(GRAY_STAINED_GLASS_PANE_1_7, "Gray Stained Glass Pane");
        builder.add(LIGHT_GRAY_STAINED_GLASS_PANE_1_7, "Light Gray Stained Glass Pane");
        builder.add(CYAN_STAINED_GLASS_PANE_1_7, "Cyan Stained Glass Pane");
        builder.add(PURPLE_STAINED_GLASS_PANE_1_7, "Purple Stained Glass Pane");
        builder.add(BLUE_STAINED_GLASS_PANE_1_7, "Blue Stained Glass Pane");
        builder.add(BROWN_STAINED_GLASS_PANE_1_7, "Brown Stained Glass Pane");
        builder.add(GREEN_STAINED_GLASS_PANE_1_7, "Green Stained Glass Pane");
        builder.add(RED_STAINED_GLASS_PANE_1_7, "Red Stained Glass Pane");
        builder.add(BLACK_STAINED_GLASS_PANE_1_7, "Black Stained Glass Pane");
        builder.add(ACACIA_LOG_1_7, "Acacia Log");
        builder.add(ACACIA_WOOD_1_7, "Acacia Wood");
        builder.add(ACACIA_LEAVES_1_7, "Acacia Leaves");
        builder.add(ACACIA_SAPLING_1_7, "Acacia Sapling");
        builder.add(DARK_OAK_LOG_1_7, "Dark Oak Log");
        builder.add(DARK_OAK_WOOD_1_7, "Dark Oak Wood");
        builder.add(DARK_OAK_LEAVES_1_7, "Dark Oak Leaves");
        builder.add(DARK_OAK_SAPLING_1_7, "Dark Oak Sapling");
        builder.add(ACACIA_PLANKS_1_7, "Acacia Planks");
        builder.add(ACACIA_STAIRS_1_7, "Acacia Stairs");
        builder.add(ACACIA_SLAB_1_7, "Acacia Slab");
        builder.add(DARK_OAK_PLANKS_1_7, "Dark Oak Planks");
        builder.add(DARK_OAK_STAIRS_1_7, "Dark Oak Stairs");
        builder.add(DARK_OAK_SLAB_1_7, "Dark Oak Slab");
        builder.add(GRANITE_1_8, "Granite");
        builder.add(POLISHED_GRANITE_1_8, "Polished Granite");
        builder.add(DIORITE_1_8, "Diorite");
        builder.add(POLISHED_DIORITE_1_8, "Polished Diorite");
        builder.add(ANDESITE_1_8, "Andesite");
        builder.add(POLISHED_ANDESITE_1_8, "Polished Andesite");
        builder.add(SLIME_BLOCK_1_8, "Slime Block");
        builder.add(PRISMARINE_1_8, "Prismarine");
        builder.add(PRISMARINE_BRICKS_1_8, "Prismarine Bricks");
        builder.add(DARK_PRISMARINE_1_8, "Dark Prismarine");
        builder.add(RED_SANDSTONE_1_8, "Red Sandstone");
        builder.add(CUT_RED_SANDSTONE_1_8, "Cut Red Sandstone");
        builder.add(CHISELED_RED_SANDSTONE_1_8, "Chiseled Red Sandstone");
        builder.add(SMOOTH_RED_SANDSTONE_1_8, "Smooth Red Sandstone");
        builder.add(RED_SANDSTONE_SLAB_1_8, "Red Sandstone Slab");
        builder.add(RED_SANDSTONE_STAIRS_1_8, "Red Sandstone Stairs");
        builder.add(BIRCH_FENCE_1_8, "Birch Fence");
        builder.add(SPRUCE_FENCE_1_8, "Spruce Fence");
        builder.add(JUNGLE_FENCE_1_8, "Jungle Fence");
        builder.add(ACACIA_FENCE_1_8, "Acacia Fence");
        builder.add(DARK_OAK_FENCE_1_8, "Dark Oak Fence");
        builder.add(BIRCH_FENCE_GATE_1_8, "Birch Fence Gate");
        builder.add(SPRUCE_FENCE_GATE_1_8, "Spruce Fence Gate");
        builder.add(JUNGLE_FENCE_GATE_1_8, "Jungle Fence Gate");
        builder.add(ACACIA_FENCE_GATE_1_8, "Acacia Fence Gate");
        builder.add(DARK_OAK_FENCE_GATE_1_8, "Dark Oak Fence Gate");
        builder.add(END_ROD_1_9, "End Rod");
        builder.add(ENDSTONE_BRICKS_1_9, "Endstone Bricks");
        builder.add(PURPUR_BLOCK_1_9, "Purpur Block");
        builder.add(PURPUR_PILLAR_1_9, "Purpur Pillar");
        builder.add(PURPUR_SLAB_1_9, "Purpur Slab");
        builder.add(PURPUR_STAIRS_1_9, "Purpur Stairs");
        builder.add(BONE_BLOCK_1_10, "Bone Block");
        builder.add(MAGMA_BLOCK_1_10, "Magma Block");
        builder.add(NETHER_WART_BLOCK_1_10, "Nether Wart Block");
        builder.add(NETHER_WART_BLOCK_1_14, "Nether Wart Block");
        builder.add(RED_NETHER_BRICKS_1_10, "Red Nether Bricks");
        builder.add(BIRCH_BUTTON_1_13, "Birch Button");
        builder.add(SPRUCE_BUTTON_1_13, "Spruce Button");
        builder.add(JUNGLE_BUTTON_1_13, "Jungle Button");
        builder.add(ACACIA_BUTTON_1_13, "Acacia Button");
        builder.add(DARK_OAK_BUTTON_1_13, "Dark Oak Button");
        builder.add(BIRCH_PRESSURE_PLATE_1_13, "Birch Pressure Plate");
        builder.add(SPRUCE_PRESSURE_PLATE_1_13, "Spruce Pressure Plate");
        builder.add(JUNGLE_PRESSURE_PLATE_1_13, "Jungle Pressure Plate");
        builder.add(ACACIA_PRESSURE_PLATE_1_13, "Acacia Pressure Plate");
        builder.add(DARK_OAK_PRESSURE_PLATE_1_13, "Dark Oak Pressure Plate");
        builder.add(PRISMARINE_SLAB_1_13, "Prismarine Slab");
        builder.add(PRISMARINE_STAIRS_1_13, "Prismarine Stairs");
        builder.add(ModItems.END_DIAMOND_CHERRY, "End Diamond Cherry");
        builder.add(ModItems.ENCHANTED_END_DIAMOND_CHERRY, "Enchanted End Diamond Cherry");
        builder.add(ModItems.SPAWNER_MINECART, "Spawner Minecart");
        builder.add(PALE_OAK_LOG, "Pale Oak Log");
        builder.add(STRIPPED_PALE_OAK_LOG, "Stripped Pale Oak Log");
        builder.add(PALE_OAK_WOOD, "Pale Oak Wood");
        builder.add(STRIPPED_PALE_OAK_WOOD, "Stripped Pale Oak Wood");
        builder.add(PALE_OAK_LEAVES, "Pale Oak Leaves");
        builder.add(PALE_OAK_SAPLING, "Pale Oak Sapling");
        builder.add(PALE_OAK_PLANKS, "Pale Oak Planks");
        builder.add(PALE_OAK_DOOR, "Pale Oak Door");
        builder.add(PALE_OAK_FENCE, "Pale Oak Fence");
        builder.add(PALE_OAK_FENCE_GATE, "Pale Oak Fence Gate");
        builder.add(PALE_OAK_STAIRS, "Pale Oak Stairs");
        builder.add(PALE_OAK_SLAB, "Pale Oak Slab");
        builder.add(PALE_OAK_PRESSURE_PLATE, "Pale Oak Pressure Plate");
        builder.add(PALE_OAK_BUTTON, "Pale Oak Button");
        builder.add(PALE_OAK_TRAPDOOR, "Pale Oak Trapdoor");
        builder.add(PALE_OAK_SIGN, "Pale Oak Sign");
        builder.add(PALE_OAK_HANGING_SIGN, "Pale Oak Hanging Sign");
        builder.add(PALE_OAK_BOAT, "Pale Oak Boat");
        builder.add(PALE_OAK_CHEST_BOAT, "Pale Oak Chest Boat");
        builder.add(PALE_MOSS, "Pale Moss");
        builder.add(PALE_MOSS_CARPET, "Pale Moss Carpet");
        builder.add(PALE_HANGING_MOSS, "Pale Hanging Moss");
        builder.add(CLOSED_EYEBLOSSOM, "Closed Eyeblossom");
        builder.add(OPEN_EYEBLOSSOM, "Open Eyeblossom");
        builder.add(RESIN_CLUMP, "Resin Clump");
        builder.add(RESIN_BRICK, "Resin Brick");
        builder.add(RESIN_BLOCK, "Resin Block");
        builder.add(RESIN_BRICKS, "Resin Bricks");
        builder.add(RESIN_BRICK_STAIRS, "Resin Brick Stairs");
        builder.add(RESIN_BRICK_SLAB, "Resin Brick Slab");
        builder.add(RESIN_BRICK_WALL, "Resin Brick Wall");
        builder.add(CHISELED_RESIN_BRICKS, "Chiseled Resin Bricks");
        builder.add(WILDFLOWERS, "Wildflowers");
        builder.add(LEAF_LITTERS, "Leaf Litters");
        builder.add(SHORT_DRY_GRASS, "Short Dry Grass");
        builder.add(FUTURE_INGOT, "Future Ingot");
        builder.add(WOODCUTTER, "Woodcutter");
        builder.add(ModItemGroups.FUTURE_BLOCKS_AND_ITEMS, "§2§lBlocktopia: §rFuture Blocks and Items");
        addText(builder, WoodCutterBlock.TITLE, "Woodcutter");
    }

    private void addChairs(TranslationBuilder builder, ChairBlock[] blocks, String baseName) {
        builder.add(blocks[0], baseName);
        builder.add(blocks[1], "White " + baseName);
        builder.add(blocks[2], "Orange " + baseName);
        builder.add(blocks[3], "Magenta " + baseName);
        builder.add(blocks[4], "Light Blue " + baseName);
        builder.add(blocks[5], "Yellow " + baseName);
        builder.add(blocks[6], "Lime " + baseName);
        builder.add(blocks[7], "Pink " + baseName);
        builder.add(blocks[8], "Gray " + baseName);
        builder.add(blocks[9], "Light Gray " + baseName);
        builder.add(blocks[10], "Cyan " + baseName);
        builder.add(blocks[11], "Purple " + baseName);
        builder.add(blocks[12], "Blue " + baseName);
        builder.add(blocks[13], "Brown " + baseName);
        builder.add(blocks[14], "Green " + baseName);
        builder.add(blocks[15], "Red " + baseName);
        builder.add(blocks[16], "Black " + baseName);
        builder.add(blocks[17], "Chartreuse " + baseName);
        builder.add(blocks[18], "Spring Green " + baseName);
        builder.add(blocks[19], "Capri " + baseName);
        builder.add(blocks[20], "Ultramarine " + baseName);
        builder.add(blocks[21], "Violet " + baseName);
        builder.add(blocks[22], "Rose " + baseName);
    }

    private static void addText(@NotNull TranslationBuilder builder, @NotNull Text text, @NotNull String value) {
        if (text.getContent() instanceof TranslatableTextContent translatableTextContent) {
            builder.add(translatableTextContent.getKey(), value);
        } else {
            Blocktopia.LOGGER.warn("Failed to add translation for text: {}", text.getString());
        }
    }
}
