package github.mcdatapack.blocktopia.item;

import github.mcdatapack.blocktopia.Blocktopia;
import github.mcdatapack.blocktopia.block.ModBlocks;
import github.mcdatapack.blocktopia.block.LegacyBlocks;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.block.Block;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.text.Text;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@SuppressWarnings("unused")
public interface ModItemGroups {
    RegistryKey<ItemGroup> LEGACY_BLOCKS_GROUP = register("legacy_blocks_group", FabricItemGroup.builder()
            .displayName(Text.translatable("itemGroup.blocktopia.legacy_blocks"))
            .icon(LegacyBlocks.COBBLESTONE_RD20090515.asItem()::getDefaultStack)
            .entries((displayContext, entries) -> {
                entries.add(LegacyBlocks.COBBLESTONE_RD20090515);
                entries.add(LegacyBlocks.COBBLESTONE_C_0_0_14A);
                entries.add(LegacyBlocks.COBBLESTONE_B1_7);
                entries.add(LegacyBlocks.WOODEN_PLANKS_RD20090515);
                entries.add(LegacyBlocks.WOODEN_PLANKS_RD161348);
                entries.add(LegacyBlocks.WOODEN_PLANKS_C0_0_14A);
                entries.add(LegacyBlocks.WOODEN_PLANKS_C0_0_15A);
                entries.add(LegacyBlocks.WOODEN_PLANKS_B1_9PRE5);
                entries.add(LegacyBlocks.SAPLING_RD161348);
                entries.add(LegacyBlocks.SAPLING_C0_0_13A);
                entries.add(LegacyBlocks.SAPLING_C0_24ST);
                entries.add(LegacyBlocks.BEDROCK_C0_0_12A);
                entries.add(LegacyBlocks.SAND_C0_0_14A);
                entries.add(LegacyBlocks.SAND_C0_0_15A);
                entries.add(LegacyBlocks.SAND_B1_9PRE6);
                entries.add(LegacyBlocks.GRAVEL_C0_0_14A);
                entries.add(LegacyBlocks.GRAVEL_C0_0_15A);
                entries.add(LegacyBlocks.GRAVEL_B1_9PRE5);
                entries.add(LegacyBlocks.GRAVEL_1_3);
                entries.add(LegacyBlocks.COAL_ORE_C0_0_14A);
                entries.add(LegacyBlocks.COAL_ORE_1_14);
                entries.add(LegacyBlocks.IRON_ORE_C0_0_14A);
                entries.add(LegacyBlocks.IRON_ORE_1_14);
                entries.add(LegacyBlocks.IRON_ORE_1_14_1);
                entries.add(LegacyBlocks.GOLD_ORE_C0_0_14A);
                entries.add(LegacyBlocks.GOLD_ORE_C0_26ST);
                entries.add(LegacyBlocks.GOLD_ORE_1_14);
                entries.add(LegacyBlocks.LOG_C0_0_14A);
                entries.add(LegacyBlocks.LEAVES_C0_0_14A);
                entries.add(LegacyBlocks.LEAVES_C0_0_15A);
                entries.add(LegacyBlocks.LEAVES_C0_24ST);
                entries.add(LegacyBlocks.SPONGE_C0_0_19A);
                entries.add(LegacyBlocks.SPONGE_1_8);
                entries.add(LegacyBlocks.WET_SPONGE_1_8);
                entries.add(LegacyBlocks.GLASS_C0_0_19A);
                entries.add(LegacyBlocks.WHITE_CLOTH);
                entries.add(LegacyBlocks.LIGHT_GRAY_CLOTH_C0_0_20A);
                entries.add(LegacyBlocks.LIGHT_GRAY_CLOTH_C0_28A);
                entries.add(LegacyBlocks.DARK_GRAY_CLOTH_C0_0_20A);
                entries.add(LegacyBlocks.DARK_GRAY_CLOTH_C0_28A);
                entries.add(LegacyBlocks.RED_CLOTH);
                entries.add(LegacyBlocks.ORANGE_CLOTH);
                entries.add(LegacyBlocks.YELLOW_CLOTH);
                entries.add(LegacyBlocks.CHARTREUSE_CLOTH);
                entries.add(LegacyBlocks.SPRING_GREEN_CLOTH);
                entries.add(LegacyBlocks.CYAN_CLOTH);
                entries.add(LegacyBlocks.CAPRI_CLOTH);
                entries.add(LegacyBlocks.ULTRAMARINE_CLOTH);
                entries.add(LegacyBlocks.VIOLET_CLOTH);
                entries.add(LegacyBlocks.PURPLE_CLOTH);
                entries.add(LegacyBlocks.MAGENTA_CLOTH);
                entries.add(LegacyBlocks.ROSE_CLOTH);
                entries.add(LegacyBlocks.GOLD_BLOCK_C0_0_20A);
                entries.add(LegacyBlocks.GOLD_BLOCK_C0_26ST);
                entries.add(LegacyBlocks.GOLD_BLOCK_A1_2_0);
                entries.add(LegacyBlocks.GOLD_BLOCK_B1_9PRE5);
                entries.add(LegacyBlocks.DANDELION_C0_0_20A);
                entries.add(LegacyBlocks.ROSE_C0_0_20A);
                entries.add(LegacyBlocks.POPPY_1_7);
                entries.add(LegacyBlocks.RED_MUSHROOM_C0_0_20A);
                entries.add(LegacyBlocks.BROWN_MUSHROOM_C0_0_20A);
                entries.add(LegacyBlocks.STONE_SLAB_C0_26ST);
                entries.add(LegacyBlocks.IRON_BLOCK_C0_26ST);
                entries.add(LegacyBlocks.IRON_BLOCK_A1_2_0);
                entries.add(LegacyBlocks.IRON_BLOCK_B1_9PRE5);
                entries.add(LegacyBlocks.TNT_C0_26ST);
                entries.add(LegacyBlocks.TNT_C0_28A);
                entries.add(LegacyBlocks.MOSSY_COBBLESTONE_C0_26ST);
                entries.add(LegacyBlocks.MOSSY_COBBLESTONE_B1_8);
                entries.add(LegacyBlocks.BRICKS_C0_26ST);
                entries.add(LegacyBlocks.BRICKS_A1_0_11);
                entries.add(LegacyBlocks.BOOKSHELF_C0_26ST);
                entries.add(LegacyBlocks.BOOKSHELF_B1_9PRE5);
                entries.add(LegacyBlocks.OBSIDIAN_C0_28A);
                entries.add(LegacyBlocks.TORCH_IN20100124_2);
                entries.add(LegacyBlocks.DIAMOND_ORE_IN20100128);
                entries.add(LegacyBlocks.DIAMOND_ORE_1_14);
                entries.add(LegacyBlocks.DIAMOND_BLOCK_IN20100128);
                entries.add(LegacyBlocks.DIAMOND_BLOCK_A1_2_0);
                entries.add(LegacyBlocks.DIAMOND_BLOCK_B1_9PRE5);
                entries.add(LegacyBlocks.CRAFTING_TABLE_IN20100131);
                entries.add(LegacyBlocks.CRAFTING_TABLE_1_14);
                entries.add(LegacyBlocks.FURNACE_IN20100219);
                entries.add(LegacyBlocks.LIT_FURNACE_IN20100219);
                entries.add(LegacyBlocks.FURNACE_B1_2);
                entries.add(LegacyBlocks.LIT_FURNACE_B1_2);
                entries.add(LegacyBlocks.LADDER_INF20100607);
                entries.add(LegacyBlocks.LADDER_INF20100618);
                entries.add(LegacyBlocks.WOODEN_DOOR_INF20100607);
                entries.add(LegacyBlocks.WOODEN_STAIRS_RD20090515);
                entries.add(LegacyBlocks.WOODEN_STAIRS_RD161348);
                entries.add(LegacyBlocks.WOODEN_STAIRS_C0_0_14A);
                entries.add(LegacyBlocks.WOODEN_STAIRS_INF20100629);
                entries.add(LegacyBlocks.WOODEN_STAIRS_B1_9PRE5);
                entries.add(LegacyBlocks.COBBLESTONE_STAIRS_RD20090515);
                entries.add(LegacyBlocks.COBBLESTONE_STAIRS_INF20100629);
                entries.add(LegacyBlocks.COBBLESTONE_STAIRS_B1_7);
                entries.add(LegacyBlocks.REDSTONE_ORE_A1_0_1);
                entries.add(LegacyBlocks.REDSTONE_ORE_1_14);
                entries.add(LegacyBlocks.REDSTONE_TORCH_A1_0_1);
                entries.add(LegacyBlocks.SNOW_A1_0_4);
                entries.add(LegacyBlocks.ICE_A1_0_4);
                entries.add(LegacyBlocks.SNOW_BLOCK_A1_0_5);
                entries.add(LegacyBlocks.WOODEN_FENCE_RD20090515);
                entries.add(LegacyBlocks.WOODEN_FENCE_RD161348);
                entries.add(LegacyBlocks.WOODEN_FENCE_C0_0_14A);
                entries.add(LegacyBlocks.WOODEN_FENCE_A1_0_17);
                entries.add(LegacyBlocks.WOODEN_FENCE_B1_9PRE5);
                entries.add(LegacyBlocks.NETHERRACK_A1_2_0);
                entries.add(LegacyBlocks.NETHERRACK_B1_9PRE5);
                entries.add(LegacyBlocks.SOUL_SAND_A1_2_0);
                entries.add(LegacyBlocks.GLOWSTONE_A1_2_0);
                entries.add(LegacyBlocks.GLOWSTONE_B1_9PRE5);
                entries.add(LegacyBlocks.CARVED_PUMPKIN_A1_2_0);
                entries.add(LegacyBlocks.JACK_O_LANTERN_A1_2_0);
                //entries.add(LIGHT_GRAY_WOOL_B1_2);
                //entries.add(GRAY_WOOL_B1_2 );
                //entries.add(BLACK_WOOL_B1_2);
                //entries.add(BROWN_WOOL_B1_2);
                //entries.add(RED_WOOL_B1_2);
                //entries.add(ORANGE_WOOL_B1_2);
                //entries.add(YELLOW_WOOL_B1_2);
                //entries.add(LIME_WOOL_B1_2 );
                //entries.add(GREEN_WOOL_B1_2);
                //entries.add(CYAN_WOOL_B1_2 );
                //entries.add(LIGHT_BLUE_WOOL_B1_2);
                //entries.add(BLUE_WOOL_B1_2 );
                //entries.add(PURPLE_WOOL_B1_2);
                //entries.add(MAGENTA_WOOL_B1_2);
                //entries.add(PINK_WOOL_B1_2 );
                //entries.add(LIGHT_GRAY_WOOL_1_2_4);
                //entries.add(GRAY_WOOL_1_2_4);
                //entries.add(BLACK_WOOL_1_2_4);
                //entries.add(BROWN_WOOL_1_2_4);
                //entries.add(RED_WOOL_1_2_4);
                //entries.add(ORANGE_WOOL_1_2_4);
                //entries.add(YELLOW_WOOL_1_2_4);
                //entries.add(LIME_WOOL_1_2_4);
                //entries.add(GREEN_WOOL_1_2_4);
                //entries.add(CYAN_WOOL_1_2_4);
                //entries.add(LIGHT_BLUE_WOOL_1_2_4);
                //entries.add(BLUE_WOOL_1_2_4);
                //entries.add(PURPLE_WOOL_1_2_4);
                //entries.add(MAGENTA_WOOL_1_2_4);
                //entries.add(PINK_WOOL_1_2_4);
                //entries.add(CAKE_B1_2);
                //entries.add(LAPIS_ORE_B1_2);
                //entries.add(LAPIS_ORE_1_14);
                //entries.add(LAPIS_BLOCK_B1_2);
                //entries.add(LAPIS_BLOCK_1_6);
                //entries.add(NOTE_BLOCK_B1_2);
                //entries.add(SANDSTONE_B1_2);
                //entries.add(SANDSTONE_1_2_4);
                //entries.add(BIRCH_LOG_B1_2);
                //entries.add(BIRCH_LOG_1_7 );
                //entries.add(BIRCH_LEAVES_B1_2 );
                //entries.add(SPRUCE_LOG_B1_2);
                //entries.add(SPRUCE_LOG_1_7);
                //entries.add(SPRUCE_LEAVES_B1_2);
                //entries.add(COBBLESTONE_SLAB_RD20090515 );
                //entries.add(COBBLESTONE_SLAB_B1_3);
                //entries.add(COBBLESTONE_SLAB_B1_7);
                //entries.add(WOODEN_SLAB_RD20090515);
                //entries.add(WOODEN_SLAB_RD161348);
                //entries.add(WOODEN_SLAB_C0_0_14A);
                //entries.add(WOODEN_SLAB_B1_3);
                //entries.add(WOODEN_SLAB_B1_9PRE5);
                //entries.add(SANDSTONE_SLAB_B1_2);
                //entries.add(SANDSTONE_SLAB_1_2_4);
                //entries.add(SMOOTH_STONE_B1_3);
                //entries.add(BIRCH_SAPLING_B1_5);
                //entries.add(SPRUCE_SAPLING_B1_5);
                //entries.add(RAIL_INF20100618);
                //entries.add(POWERED_RAIL_B1_5 );
                //entries.add(DETECTOR_RAIL_B1_5);
                //entries.add(COBWEB_B1_5);
                //entries.add(DEAD_BUSH_B1_6);
                //entries.add(SHRUB_B1_6);
                //entries.add(SHORT_GRASS_B1_6);
                //entries.add(FERN_B1_6);
                //entries.add(TRAPDOOR_B1_6);
                //entries.add(STONE_BRICKS_B1_8);
                //entries.add(CRACKED_STONE_BRICKS_B1_8);
                //entries.add(MOSSY_STONE_BRICKS_B1_8);
            }).build());
    RegistryKey<ItemGroup> NATURAL_BLOCKS_GROUP = register("natural_blocks_group", FabricItemGroup.builder()
            .displayName(Text.translatable("itemGroup.blocktopia.natural_blocks"))
            .icon(ModBlocks.TROPICAL_MOSS.asItem()::getDefaultStack)
            .entries((displayContext, entries) -> {
                entries.add(ModBlocks.TROPICAL_MOSS);
                entries.add(ModBlocks.TROPICAL_MOSS_CARPET);
                entries.add(ModBlocks.SANDY_DIRT);
                entries.add(ModItems.TROPICAL_WATER_BUCKET);
                entries.add(ModBlocks.OAK_CHAIR[0]);
                entries.add(ModBlocks.SPRUCE_CHAIR[0]);
                entries.add(ModBlocks.BIRCH_CHAIR[0]);
                entries.add(ModBlocks.JUNGLE_CHAIR[0]);
                entries.add(ModBlocks.ACACIA_CHAIR[0]);
                entries.add(ModBlocks.DARK_OAK_CHAIR[0]);
                entries.add(ModBlocks.CRIMSON_CHAIR[0]);
                entries.add(ModBlocks.WARPED_CHAIR[0]);
                entries.add(ModBlocks.MANGROVE_CHAIR[0]);
                entries.add(ModBlocks.BAMBOO_CHAIR[0]);
                entries.add(ModBlocks.CHERRY_CHAIR[0]);
                entries.add(ModBlocks.PALM_LEAVES);
                entries.add(ModBlocks.PALM_SAPLING);
                entries.add(ModBlocks.PALM_LOG);
                entries.add(ModBlocks.STRIPPED_PALM_LOG);
                entries.add(ModBlocks.PALM_WOOD);
                entries.add(ModBlocks.STRIPPED_PALM_WOOD);
                entries.add(ModBlocks.PALM_PLANKS);
                entries.add(ModBlocks.PALM_STAIRS);
                entries.add(ModBlocks.PALM_SLAB);
                entries.add(ModBlocks.PALM_FENCE);
                entries.add(ModBlocks.PALM_FENCE_GATE);
                entries.add(ModBlocks.PALM_PRESSURE_PLATE);
                entries.add(ModBlocks.PALM_BUTTON);
                entries.add(ModBlocks.PALM_DOOR);
                entries.add(ModBlocks.PALM_TRAPDOOR);
                entries.add(ModBlocks.PALM_CHAIR[0]);
                entries.add(ModItems.PALM_BOAT);
                entries.add(ModItems.PALM_CHEST_BOAT);
                entries.add(ModBlocks.PALM_SIGN);
                entries.add(ModBlocks.PALM_HANGING_SIGN);
                entries.add(ModBlocks.BANANA_LEAVES);
                entries.add(ModBlocks.BANANA_SAPLING);
                entries.add(ModBlocks.BANANA_LOG);
                entries.add(ModBlocks.STRIPPED_BANANA_LOG);
                entries.add(ModBlocks.BANANA_WOOD);
                entries.add(ModBlocks.STRIPPED_BANANA_WOOD);
                entries.add(ModBlocks.BANANA_PLANKS);
                entries.add(ModBlocks.BANANA_STAIRS);
                entries.add(ModBlocks.BANANA_SLAB);
                entries.add(ModBlocks.BANANA_FENCE);
                entries.add(ModBlocks.BANANA_FENCE_GATE);
                entries.add(ModBlocks.BANANA_PRESSURE_PLATE);
                entries.add(ModBlocks.BANANA_BUTTON);
                entries.add(ModBlocks.BANANA_DOOR);
                entries.add(ModBlocks.BANANA_TRAPDOOR);
                entries.add(ModBlocks.BANANA_CHAIR[0]);
                entries.add(ModItems.BANANA_BOAT);
                entries.add(ModItems.BANANA_CHEST_BOAT);
                entries.add(ModBlocks.BANANA_SIGN);
                entries.add(ModBlocks.BANANA_HANGING_SIGN);
                entries.add(ModBlocks.CORN_LEAVES);
                entries.add(ModBlocks.CORN_SAPLING);
                entries.add(ModBlocks.CORN_LOG);
                entries.add(ModBlocks.STRIPPED_CORN_LOG);
                entries.add(ModBlocks.CORN_WOOD);
                entries.add(ModBlocks.STRIPPED_CORN_WOOD);
                entries.add(ModBlocks.CORN_PLANKS);
                entries.add(ModBlocks.CORN_STAIRS);
                entries.add(ModBlocks.CORN_SLAB);
                entries.add(ModBlocks.CORN_FENCE);
                entries.add(ModBlocks.CORN_FENCE_GATE);
                entries.add(ModBlocks.CORN_PRESSURE_PLATE);
                entries.add(ModBlocks.CORN_BUTTON);
                entries.add(ModBlocks.CORN_DOOR);
                entries.add(ModBlocks.CORN_TRAPDOOR);
                entries.add(ModBlocks.CORN_CHAIR[0]);
                entries.add(ModItems.CORN_BOAT);
                entries.add(ModItems.CORN_CHEST_BOAT);
                entries.add(ModBlocks.CORN_SIGN);
                entries.add(ModBlocks.CORN_HANGING_SIGN);
                entries.add(ModBlocks.POISONED_LEAVES);
                entries.add(ModBlocks.POISONED_SAPLING);
                entries.add(ModBlocks.POISONED_LOG);
                entries.add(ModBlocks.STRIPPED_POISONED_LOG);
                entries.add(ModBlocks.POISONED_WOOD);
                entries.add(ModBlocks.STRIPPED_POISONED_WOOD);
                entries.add(ModBlocks.POISONED_PLANKS);
                entries.add(ModBlocks.POISONED_STAIRS);
                entries.add(ModBlocks.POISONED_SLAB);
                entries.add(ModBlocks.POISONED_FENCE);
                entries.add(ModBlocks.POISONED_FENCE_GATE);
                entries.add(ModBlocks.POISONED_PRESSURE_PLATE);
                entries.add(ModBlocks.POISONED_BUTTON);
                entries.add(ModBlocks.POISONED_DOOR);
                entries.add(ModBlocks.POISONED_TRAPDOOR);
                entries.add(ModBlocks.POISONED_CHAIR[0]);
                entries.add(ModItems.POISONED_BOAT);
                entries.add(ModItems.POISONED_CHEST_BOAT);
                entries.add(ModBlocks.POISONED_SIGN);
                entries.add(ModBlocks.POISONED_HANGING_SIGN);
                entries.add(ModBlocks.MAHOGANY_LEAVES);
                entries.add(ModBlocks.MAHOGANY_SAPLING);
                entries.add(ModBlocks.MAHOGANY_LOG);
                entries.add(ModBlocks.STRIPPED_MAHOGANY_LOG);
                entries.add(ModBlocks.MAHOGANY_WOOD);
                entries.add(ModBlocks.STRIPPED_MAHOGANY_WOOD);
                entries.add(ModBlocks.MAHOGANY_PLANKS);
                entries.add(ModBlocks.MAHOGANY_STAIRS);
                entries.add(ModBlocks.MAHOGANY_SLAB);
                entries.add(ModBlocks.MAHOGANY_FENCE);
                entries.add(ModBlocks.MAHOGANY_FENCE_GATE);
                entries.add(ModBlocks.MAHOGANY_PRESSURE_PLATE);
                entries.add(ModBlocks.MAHOGANY_BUTTON);
                entries.add(ModBlocks.MAHOGANY_DOOR);
                entries.add(ModBlocks.MAHOGANY_TRAPDOOR);
                entries.add(ModBlocks.MAHOGANY_CHAIR[0]);
                entries.add(ModItems.MAHOGANY_BOAT);
                entries.add(ModItems.MAHOGANY_CHEST_BOAT);
                entries.add(ModBlocks.MAHOGANY_SIGN);
                entries.add(ModBlocks.MAHOGANY_HANGING_SIGN);
                entries.add(ModBlocks.FLOWERING_CHERRY_LEAVES);
                entries.add(ModBlocks.FLOWERING_CHERRY_SAPLING);
                entries.add(ModItems.CHERRY);
                entries.add(ModItems.GOLDEN_CHERRY);
                entries.add(ModItems.ENCHANTED_GOLDEN_CHERRY);
                entries.add(ModItems.DIAMOND_CHERRY);
                entries.add(ModItems.ENCHANTED_DIAMOND_CHERRY);
                entries.add(ModItems.NETHERITE_CHERRY);
                entries.add(ModItems.ENCHANTED_NETHERITE_CHERRY);
                entries.add(ModItems.DEEPSLATE_EMERALD_CHERRY);
                entries.add(ModItems.ENCHANTED_DEEPSLATE_EMERALD_CHERRY);
                entries.add(ModItems.COCONUT);
                entries.add(ModItems.GOLDEN_COCONUT);
                entries.add(ModItems.ENCHANTED_GOLDEN_COCONUT);
                entries.add(ModItems.BANANA);
                entries.add(ModBlocks.BANANA_CROP);
                entries.add(ModItems.ENCHANTED_GOLDEN_CARROT);
                entries.add(ModItems.GOLDEN_POTATO);
                entries.add(ModItems.ENCHANTED_GOLDEN_POTATO);
                entries.add(ModItems.GOLDEN_BAKED_POTATO);
                entries.add(ModItems.ENCHANTED_GOLDEN_BAKED_POTATO);
                entries.add(ModBlocks.GLOW_FLOWER);
            }).build());

    RegistryKey<ItemGroup> COLORED_BLOCKS_GROUP = register("colored_blocks", FabricItemGroup.builder()
            .displayName(Text.translatable("itemGroup.blocktopia.colored_blocks"))
            .icon(ModBlocks.OAK_CHAIR[1].asItem()::getDefaultStack)
            .entries((displayContext, entries) -> {
                add(entries, ModBlocks.OAK_CHAIR);
                add(entries, ModBlocks.SPRUCE_CHAIR);
                add(entries, ModBlocks.BIRCH_CHAIR);
                add(entries, ModBlocks.JUNGLE_CHAIR);
                add(entries, ModBlocks.ACACIA_CHAIR);
                add(entries, ModBlocks.DARK_OAK_CHAIR);
                add(entries, ModBlocks.CRIMSON_CHAIR);
                add(entries, ModBlocks.WARPED_CHAIR);
                add(entries, ModBlocks.MANGROVE_CHAIR);
                add(entries, ModBlocks.BAMBOO_CHAIR);
                add(entries, ModBlocks.CHERRY_CHAIR);
                add(entries, ModBlocks.PALM_CHAIR);
                add(entries, ModBlocks.BANANA_CHAIR);
                add(entries, ModBlocks.CORN_CHAIR);
                add(entries, ModBlocks.POISONED_CHAIR);
                add(entries, ModBlocks.MAHOGANY_CHAIR);
            })
            .build());

    RegistryKey<ItemGroup> OTHER_ITEMS_AND_BLOCKS_GROUP = register("other_items_and_blocks", FabricItemGroup.builder()
            .displayName(Text.translatable("itemGroup.blocktopia.other_items_and_blocks"))
            .icon(ModBlocks.SMALL_CHEST.asItem()::getDefaultStack)
            .entries((displayContext, entries) -> {
                entries.add(ModBlocks.GUNPOWDER_BLOCK);
                entries.add(ModBlocks.PAPER_BLOCK);
                entries.add(ModBlocks.FIREWORK_BLOCK);
                entries.add(ModBlocks.SMALL_CHEST);
                entries.add(ModBlocks.DUPER);
                entries.add(ModBlocks.LEGACY_CUTTER);
                entries.add(ModBlocks.XP_TRAP);
                entries.add(ModBlocks.SPONGE_TNT);
                entries.add(ModBlocks.EXTENDED_REPEATER_TICK);
                entries.add(ModBlocks.EXTENDED_REPEATER_SECOND);
                entries.add(ModBlocks.EXTENDED_REPEATER_MINUTE);
                entries.add(ModItems.CREATIVE_INGOT);
                entries.add(ModItems.CREATIVE_NUGGET);
                entries.add(ModItems.GIANT_SPAWN_EGG);
                entries.add(ModItems.ILLUSIONER_SPAWN_EGG);
                entries.add(ModItems.MONKEY_SPAWN_EGG);
                entries.add(ModItems.RABBIT_TRINKET);
                entries.add(ModItems.FISH_TRINKET);
                entries.add(ModItems.CAT_TRINKET);
            })
            .build());

    private static void add(ItemGroup.Entries entries, ItemConvertible[] items) {
        Arrays.stream(items).forEach(entries::add);
    }

    private static RegistryKey<ItemGroup> register(String name, ItemGroup itemGroup) {
        Registry.register(Registries.ITEM_GROUP, Blocktopia.id(name), itemGroup);
        return Registries.ITEM_GROUP.getKey(itemGroup).get();
    }

    static void load() {}
}
